Update wallet settings page to the latest UI
planetdecred/godcr pull request #1007
Opened 2022-06-26 19:14 UTC by devchoplife

Closes #987

2022-06-29 09:28 UTC, Sirmorrison requested changes

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +					},
```suggestion
					func(gtx C) D {
								if !pg.wallet.IsWatchingOnlyWallet() {
									return pg.changePassphrase()(gtx)
								}
								return layout.Dimensions{}
					},
					pg.stakeshuffle(),
					pg.debug(),
					pg.dangerZone(),
```

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +							label:     pg.Theme.Body2("mixed"), // TODO
localized string

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +							label:     pg.Theme.Body2("unmixed"), // TODO
localize string

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +								layout.Rigid(pg.Theme.Label(values.TextSize16, "Allow spending from unmixed accounts").Layout),
localize string

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +								pg.Toast.Notify("Spending passphrase updated")
localize string

2022-06-29 09:28 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +						ConfirmPasswordHint("Confirm new spending passphrase").
localize string

2022-06-30 07:50 UTC, JustinBeBoy commented
App crash when cancel change passphrase

![image](https://user-images.githubusercontent.com/19331824/176622817-a5f188cd-23f8-40cd-a710-712f50becbdc.png)

2022-06-30 08:07 UTC, devchoplife commented
> App crash when cancel change passphrase
> 
> ![image](https://user-images.githubusercontent.com/19331824/176622817-a5f188cd-23f8-40cd-a710-712f50becbdc.png)

I created an issue here #1006

2022-07-01 15:55 UTC, JustinBeBoy submitted a review, later dismissed

2022-07-05 18:03 UTC, Sirmorrison requested changes

2022-07-05 18:03 UTC, Sirmorrison commented on ui/values/localizable/en.go
> +"spendingPasswordUpdated" = "Spending passphrase updated";
Revert please.. it should be `Password`

2022-07-13 06:56 UTC, Sirmorrison requested changes
I noticed that to access the wallet setting page, you have to go through the wallets page.

According to the design, the wallet settings page should be accessed from the more page >> settings option.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/27733432/178670188-68f451d6-a021-48c2-ade3-8e0e08f03103.png">

The wallet page as been deprecated in #1008 however, till this PR is merged, leave the design as it is.. Just move wallet setting to more >>> settings.

2022-07-13 06:56 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +}
This is only used once.. we can remove.

2022-07-13 06:56 UTC, Sirmorrison commented on ui/page/wallets/wallet_settings_page.go
> +}
```suggestion
func (pg *WalletSettingsPage) subSection(gtx C, title string, body layout.Widget) D {
	return layout.Inset{Top: values.MarginPadding5, Bottom: values.MarginPadding15}.Layout(gtx, func(gtx C) D {
		return layout.Flex{}.Layout(gtx,
			layout.Rigid(pg.Theme.Body1(title).Layout),
			layout.Flexed(1, func(gtx C) D {
				return layout.E.Layout(gtx, body)
			}),
		)
	})
}
```

2022-07-18 08:22 UTC, Sirmorrison requested changes
This was the review request 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/27733432/179470788-d777d804-4b74-43ca-81d8-ffb6a255b89d.png">

you dont need the wallet setting option as added.
the settings is now the new wallet setting.. meaning clicking on the `settings` option should open the `wallet settings page`

<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/179471491-00aad701-d66c-4637-9d5c-2a76c15c671e.png">

Also, move wallet_settings_page.go file from the `info` package to the root directory `page`

2022-07-18 08:22 UTC, Sirmorrison commented on ui/page/info/wallet_settings_page.go
> +}
```suggestion
func (pg *WalletSettingsPage) subSection(gtx C, title string, body layout.Widget) D {
	return layout.Inset{Top: values.MarginPadding5, Bottom: values.MarginPadding15}.Layout(gtx, func(gtx C) D {
		return layout.Flex{}.Layout(gtx,
			layout.Rigid(pg.Theme.Body1(title).Layout),
			layout.Flexed(1, func(gtx C) D {
				return layout.E.Layout(gtx, body)
			}),
		)
	})
}
```

this `subSectionLabel` was only used once.

2022-07-18 15:56 UTC, Sirmorrison commented
Ok.. the PR looks good so far.

Since we are still on the wallet settings page.. kindly update the UI including the following sections.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/27733432/179552401-c2b59614-2a14-43b6-877e-2f30ae18a310.png">

2022-07-20 07:51 UTC, Sirmorrison approved these changes

2022-07-20 07:52 UTC, merged