V2 overview page
planetdecred/godcr pull request #1008
Opened 2022-06-27 09:38 UTC by Sirmorrison

Fix #985

2022-07-12 10:44 UTC, JustinBeBoy requested changes

2022-07-12 10:44 UTC, JustinBeBoy commented on ui/decredmaterial/progressbar.go
> +		val := (progress / mp.total) * 100
why you  don't check mp.total values, I have got case mp.total = 0

2022-07-12 10:44 UTC, JustinBeBoy commented on ui/page/info/info_page.go
> +func NewInfoPage(l *load.Load) *WalletInfo {
why change the name of the page to info but keep the id as "Overview"?

2022-07-12 10:49 UTC, JustinBeBoy commented
**- The progress didn't work**
![00000](https://user-images.githubusercontent.com/19331824/178472950-953d9021-f85c-460c-9c38-dabf13e13d5c.PNG)

**- Title tab not show**
![0000](https://user-images.githubusercontent.com/19331824/178473171-78149e5f-6f1e-4981-a57b-0cda6809f457.PNG)

**- Sync progress showing wrong**
![0](https://user-images.githubusercontent.com/19331824/178473346-4cbf910a-7977-4aba-974a-9b6c120688fe.PNG)

**- Wallet info not show**
![aaaaa](https://user-images.githubusercontent.com/19331824/178473642-d4675152-2bcd-47dd-b7b1-658e1a4174b3.PNG)

2022-07-13 12:13 UTC, Sirmorrison commented
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/178729911-4ed09972-2826-4b77-ab82-692d58d44d98.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/178730008-cd716e66-6cf0-47c2-8673-a66febe832c7.png">

resolved progress bar bug..

2022-07-14 16:13 UTC, JustinBeBoy approved these changes

2022-07-14 16:20 UTC, merged

2022-07-14 17:01 UTC, dreacot reviewed
LGTM