Fix wallet selector page not scrollable
planetdecred/godcr pull request #1011
Opened 2022-06-27 15:22 UTC by song50119

Fix #1010

2022-06-28 13:38 UTC, Sirmorrison requested changes
The entire page scrolls which should not be.. the title and create wallet button should not scroll.

2022-07-12 09:04 UTC, itswisdomagain requested changes
The debug setting option to reset the DEX client is no longer available. I'm unable to properly test this PR.

Also, on app load, the select wallet page also prompts to select a DEX server. Not sure what the idea for that is. Do you need to select a wallet AND a DEX server? Can you proceed by just selecting a DEX server but not selecting a wallet? Where page does that lead to?

2022-07-12 09:04 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +func (md *AddDexModal) saveDexServer(host string, cert []byte) {
Why are these details saved here after successful fee payment? Doesn't the official dex client library handle this?

2022-07-18 08:42 UTC, Sirmorrison commented
66 transaction(s) indexed in total
2022-07-18 09:41:06.125 [INF] DLWL: [108] Connected block 000000094322b5a7f2d4f8aab243d11b7bad8f9e2a9d8ab4f54ab06fdaf742fd, height 958821, 0 wallet transaction(s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x4dca74a]

goroutine 844 [running]:
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).listenForTxNotifications.func1()
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/components/wallet_selector.go:399 +0x14a
created by github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).listenForTxNotifications
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/components/wallet_selector.go:389 +0xfc
sirmorrison@sirmorrisons-MacBook-Pro godcr-gio % 

its crashing... and you need to rebase.

2022-07-27 18:59 UTC, Sirmorrison approved these changes

2022-07-27 22:56 UTC, dreacot approved these changes
LGTM

2022-07-28 05:54 UTC, merged