Multi: v2 staking design
planetdecred/godcr pull request #1016
Opened 2022-07-18 19:37 UTC by Sirmorrison

Resolves #981 
Fix #1014
Fix #976 
Fix #1005
Fix #1022 
Fix #978

- [x] Fix wallet selector page display when app loads for the first time.
- [x] Fix backup modal notification display for wallet that don't have their seed phrase backed up.
- [x] Update the staking layout to the v2 layout design
- [x] Update stake shuffle and staking page to single wallet selector approach (needed to test the account selector)
- [x] Fix crash when staking page button is clicked twice
- [x] Fix ticket list refresh bug
- [x] Fix app crash when the settings button is clicked when a watch only wallet is selected.

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/27733432/181623862-e021277e-88de-4735-881d-c25d8b643280.png">

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/27733432/181623955-6a1a97ed-4ef6-4b9e-8ebd-2c6404fb3322.png">

2022-07-26 14:05 UTC, dreacot commented
Description needs to be updated, because from what i'm seeing it looks like the work is incomplete, and that might have been intentional as follow up PRs are planned, but i'm not sure, can the description state the overall expectation of this PR(including what's purposely left out) and it we are expecting follow up PRs on this

2022-07-26 15:12 UTC, Sirmorrison commented
> Description needs to be updated, because from what i'm seeing it looks like the work is incomplete, and that might have been intentional as follow up PRs are planned, but i'm not sure, can the description state the overall expectation of this PR(including what's purposely left out) and it we are expecting follow up PRs on this

The PR resolves everything mentioned above. The next PR is the tx details page, and that does not really have anything to do with this PR.

2022-07-26 15:35 UTC, dreacot requested changes, later dismissed
1. Navigating to the staking page cause a overall lag of the app for a couple of seconds.

![Screenshot from 2022-07-26 16-19-05](https://user-images.githubusercontent.com/25265396/181045028-b6ec4ad3-387d-4c28-84b6-dba2f8d29733.png)

2. All tickets are showing at once which isn't efficient and most likely the cause of the lag. the list should be paginated.

3. clicking on the settings icon on the staking page causes a crash

4. The statistic dialog is no same as that of the desing
![Screenshot from 2022-07-26 16-24-31](https://user-images.githubusercontent.com/25265396/181046397-b2facd2c-db25-4594-93e9-e127c0f68894.png)
![Screenshot from 2022-07-26 16-25-28](https://user-images.githubusercontent.com/25265396/181046444-dc524a5e-f9f9-4225-9d9d-574850b8799b.png)

![Screenshot from 2022-07-26 16-26-54](https://user-images.githubusercontent.com/25265396/181046807-eeb42db7-773a-4cee-b362-669dfee908c7.png)
5. there should be more right margin after the settings icon, and `stake` should be in bold

![Screenshot from 2022-07-26 16-28-58](https://user-images.githubusercontent.com/25265396/181047326-a7bed639-3361-411b-a548-ebc252451408.png)
6. This section should be titled`Tickets` and the icons don't seem to be on par with the provided figma design

7. the hover on tickets doesn't have a proper padding
![Screenshot from 2022-07-26 16-30-25](https://user-images.githubusercontent.com/25265396/181047793-fe149e19-34c4-451c-8326-ddf099681f07.png)
![Screenshot from 2022-07-26 16-30-17](https://user-images.githubusercontent.com/25265396/181047798-bc0fe3d5-ee9d-442e-a544-e7e8acbf49eb.png)

8. The staking details page doesn't yet seem to be on par with the figma design

2022-07-26 15:44 UTC, Sirmorrison commented
> 2\. All tickets are showing at once which isn't efficient and most likely the cause of the lag. the list should be paginated.

* `clicking on the settings icon on the staking page causes a crash` attach log please
* `All tickets are showing at once which isn't efficient and most likely the cause of the lag. the list should be paginated.` for this, we will need to open a new PR
probably fix with the tx page. #939
* `The statistic dialog is no same as that of the desing` there is a default godcr modal design which was used. Having to implement this design means changing the godcr modal design which wont be uniform. Was to bring it up on the design group.. Skipped my mind. 
* `The staking details page doesn't yet seem to be on par with the figma design` this is coming in a different PR as the design is a tx details design overhaul.

2022-07-26 15:48 UTC, dreacot commented
> clicking on the settings icon on the staking page causes a crash attach log please
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x120a09b]

goroutine 14 [running]:
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout.func2({{{0x0, 0x0}, {0x114, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:181 +0x3b
gioui.org/layout.Flex.Layout({0xfa, 0x3d, 0x0, 0x0}, {{{0x0, 0x0}, {0x134, 0xf41fc}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x134, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:89 +0x85
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x134, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x134, 0x0}, {0x134, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:88 +0xe5
gioui.org/layout.Inset.Layout({0x1bd0120, 0x0, 0x0, 0x80000000}, {{{0x134, 0x0}, {0x134, 0xf41fc}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x14c, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:86 +0x109
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0xe6, 0xea, 0xed, 0xff}, {0x8, 0x8, 0x8, 0x8}, 0x40000000}, {{{0x14c, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/border.go:21 +0x98
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x14c, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:84 +0x1d6
gioui.org/layout.Stack.Layout({0xff}, {{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:47 +0x2aa
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:108 +0x238
gioui.org/layout.Inset.Layout({0x417c8a, 0x0, 0x41a154, 0x0}, {{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:44 +0x109
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xffffffffffffffff, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x0, {{0xe6, 0xea, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:42 +0xe5
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout(0xc003526f00, {0x1dcc100, 0xc00043d3b0}, {{{0x14c, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:170 +0x4a5
github.com/planetdecred/godcr/ui/page/staking.(*ticketBuyerModal).Layout.func2.1.1({{{0x14c, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/staking/stake_modal.go:126 +0x87
gioui.org/layout.Inset.Layout({0x5d0c, 0x0, 0x2899440, 0xc0}, {{{0x14c, 0x0}, {0x14c, 0xf4214}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/page/staking.(*ticketBuyerModal).Layout.func2.1({{{0x14c, 0x0}, {0x14c, 0xf422c}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/staking/stake_modal.go:125 +0xaf
gioui.org/layout.Flex.Layout({0x0, 0x0, 0x0, 0x0}, {{{0x14c, 0x0}, {0x14c, 0xf422c}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/page/staking.(*ticketBuyerModal).Layout.func2({{{0x14c, 0x0}, {0x14c, 0xf422c}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/staking/stake_modal.go:120 +0x255
gioui.org/layout.Inset.Layout({0x3df6, 0x0, 0x3df5, 0x0}, {{{0x14c, 0x0}, {0x14c, 0xf422c}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.2.2({{{0x14c, 0x0}, {0x14c, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/modal.go:167 +0x85
gioui.org/layout.(*List).Layout(0xc0061bd800, {{{0x14c, 0x0}, {0x14c, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/list.go:117 +0x17c
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.2({{{0x14c, 0x0}, {0x14c, 0x196}}, {0x3f800000, 0x3f800000}, {0x1d7bbe0, 0xc00001f8e8}, {0xc0b020fccc6fe14c, 0xa3fb47b13, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/modal.go:166 +0x2bd
gioui.org/layout.Flex.Layout({0xf2, 0x3d, 0x0, 0x0}, {{{0x0, 0x0}, {0x14c, 0x1c4}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gi [...]

2022-07-27 23:08 UTC, dreacot reviewed
clicking the settings icon isn't working, is that intentional?

2022-07-28 05:53 UTC, Sirmorrison commented
> clicking the settings icon isn't working, is that intentional?

if you are using a watch only wallet, yes it wont work as its watch only. but other wallets works.

2022-07-28 10:59 UTC, dreacot commented
> > clicking the settings icon isn't working, is that intentional?
> 
> if you are using a watch only wallet, yes it wont work as its watch only. but other wallets works.

alright, there's nothing indicating that, maybe we should use a toast?

2022-07-28 15:51 UTC, JustinBeBoy commented
> > > clicking the settings icon isn't working, is that intentional?
> > 
> > 
> > if you are using a watch only wallet, yes it wont work as its watch only. but other wallets works.
> 
> alright, there's nothing indicating that, maybe we should use a toast?

or shouldn't show it

2022-07-28 16:01 UTC, JustinBeBoy requested changes
1. After confirm automatic Ticket Purchase the switcher not turn on then turn off without notice for user the reason. 

2. Should uppercase the first character
![image](https://user-images.githubusercontent.com/19331824/181583385-5343df66-00b7-4118-9be5-5b7cbcb9c11a.png)

2022-07-28 16:18 UTC, JustinBeBoy commented on ui/page/staking/stake_info.go
> +							pg.dataRows("Can Buy", pg.CalculateTotalTicketsCanBuy()),
Add "Can Buy" to the localize string

2022-07-28 16:19 UTC, JustinBeBoy commented
We don't use description of ticket like mockup ?

![image](https://user-images.githubusercontent.com/19331824/181588040-fbbae4ee-113f-453f-be93-766d2f8beda4.png)

2022-07-28 18:43 UTC, Sirmorrison commented
* After confirm automatic Ticket Purchase the switcher not turn on then turn off without notice for user the reason.
this seems to be a backend issue and will be resolved from dcrlibwallet. 


> We don't use description of ticket like mockup ?
> 
> ![image](https://user-images.githubusercontent.com/19331824/181588040-fbbae4ee-113f-453f-be93-766d2f8beda4.png)

I dont understand this comment please.

Can you share a screenshot of the UI that did not align?

2022-07-29 15:25 UTC, dreacot commented
LGTM @JustinBeBoy are you still having concerns?

2022-07-30 07:00 UTC, JustinBeBoy approved these changes

2022-07-30 07:44 UTC, merged