Handle event after deleted wallet
planetdecred/godcr pull request #1023
Opened 2022-07-27 14:57 UTC by JustinBeBoy

Resolve #977

2022-07-27 18:52 UTC, Sirmorrison requested changes
PR looks good. 

the code on line https://github.com/planetdecred/godcr/pull/1023/files#diff-1d583a6bf9ea9ef5e81bcff9c1e9f3bccfd9ab414092d5515ff838424907ab4fL402 is redundant. kindle remove it.

2022-07-27 22:26 UTC, dreacot approved these changes, later dismissed
LGTM

2022-07-28 06:50 UTC, JustinBeBoy commented
> PR looks good.
> 
> the code on line https://github.com/planetdecred/godcr/pull/1023/files#diff-1d583a6bf9ea9ef5e81bcff9c1e9f3bccfd9ab414092d5515ff838424907ab4fL402 is redundant. kindle remove it.

it's not redundant, it need to close current page and modal

2022-07-28 18:37 UTC, Sirmorrison approved these changes

2022-07-28 18:38 UTC, merged