Fix top nav dark mode color
planetdecred/godcr pull request #1049
Opened 2022-08-25 13:56 UTC by Sirmorrison

Fix #1043 

This pr fix text color on the top nav when in dark mode
replace hidden icon button with image icon
clean up hidden icon lines of code 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/27733432/186684275-01e277e1-0120-4f20-aa90-2b52fa03d134.png">

2022-08-26 02:38 UTC, JustinBeBoy requested changes

2022-08-26 02:38 UTC, JustinBeBoy commented on ui/page/main_page.go
> +	tooltip           *decredmaterial.Tooltip
tooltip not use in this page so need to remove it

2022-08-26 02:38 UTC, JustinBeBoy commented on ui/page/main_page.go
> +	mp.tooltip = mp.Theme.Tooltip()
remove it

2022-08-26 02:40 UTC, JustinBeBoy commented
please improve icon button show/hide balance when hover

<img width="800" alt="image" src="https://user-images.githubusercontent.com/19331824/186804717-8eac3ec8-2eaf-4f7a-a1a6-9120f3718dca.png">

2022-08-26 18:23 UTC, dreacot submitted a review, later dismissed
As stated by @JustinBeBoy , the hover on the hide icon is flaky. I think we are good to merge once that is fixed

2022-08-29 06:30 UTC, Sirmorrison commented
> please improve icon button show/hide balance when hover
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/19331824/186804717-8eac3ec8-2eaf-4f7a-a1a6-9120f3718dca.png">

The issue with the hover is the custom clickable... I will just have it removed.

2022-08-29 11:05 UTC, devchoplife reviewed
Looks good
Please resolve conversations

2022-08-29 14:16 UTC, JustinBeBoy approved these changes

2022-08-29 14:59 UTC, merged