use universal suggestion widgets for all editors
planetdecred/godcr pull request #128
Opened 2020-06-03 14:09 UTC by oshorefueled

### Resolves

Issue #126 

### What's new

This PR replaces the previous seed suggestion implementation. Rather than use defining suggestion seeds for each editor, it uses the same suggestion widgets for all editors only displaying them on active editors.

2020-06-03 14:30 UTC, Sirmorrison requested changes
<img width="485" alt="image" src="https://user-images.githubusercontent.com/27733432/83649809-86f0a880-a5af-11ea-87b0-df7fb43fec95.png">


So there is an issue here. if the seed suggestion shows up and i dont select any option at first and it leaves the screen, After clearing the editor field and trying again no suggestions show up.
Even if i move to the next editor nothing shows up. i looks like the code breaks at the point if there is no suggestion in the first editor.

To have this to work again i will need to restart the application.

2020-06-05 05:54 UTC, Sirmorrison requested changes
<img width="587" alt="image" src="https://user-images.githubusercontent.com/27733432/83840773-53b93100-a6f7-11ea-8d32-965e836ff250.png">

Nice work so far just a couple of observation that could be addressed.
* i noticed that the initial implementation of this page, when a seed suggestion is selected, the editor focus is moved to the next available editor field. However, currently i will have to select the next editor field manually. 
for example the screenshot below i just selected a suggestion; the focus is supposed to move to number 2 howver its still on number 1.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/27733432/83841243-62ecae80-a6f8-11ea-8863-e116bd2feb7b.png">

* After the wallet is successfully restored, if you try to restore a wallet again, i noticed the seeds from the previous wallet restoration still exist (first screenshot). I believe the fields are supposed to be cleared after a successful wallet restoration.
* In the even a user mixes seed phrases up while inputting them, he gets an error telling him his seed phrase is not accurate however say which seed position is the giving the issue and with this the user will have to enter the seed phrases again from scratch. Currently, the user will have to manually delete all 33 seed phrases from the input fields which is lot of work. Can we add a `RESET` button to the page to clear all the fields?

2020-06-05 12:36 UTC, oshorefueled commented
your first and second bullet points was implemented on the last push. Your last bullet point would be on a separate pull request. This PR is only to fix the suggestion seeds flickering on scroll.

2020-06-05 13:19 UTC, Sirmorrison submitted a review, later dismissed
PR has passed all checks so far Looks good to go.

2020-06-05 14:44 UTC, beansgum approved these changes

2020-06-05 14:51 UTC, merged