add seed backup page
planetdecred/godcr pull request #163
Opened 2020-06-25 08:48 UTC by oshorefueled

#### Resolves

Issue #144 

#### What's new

This PR adds the seed backup page to the app. 

#### Relevant screenshots or logs
Backup button on wallets page
<img width="500" alt="Screenshot 2020-06-25 at 9 46 12 AM" src="https://user-images.githubusercontent.com/15804688/85687381-bbe0ae80-b6c8-11ea-817e-eb6b89f7adcc.png">

<img width="500" alt="Screenshot 2020-06-24 at 10 42 42 PM" src="https://user-images.githubusercontent.com/15804688/85687049-6b695100-b6c8-11ea-9199-ee1cbf7c96f9.png">

<img width="500" alt="Screenshot 2020-06-24 at 10 42 53 PM" src="https://user-images.githubusercontent.com/15804688/85687184-8d62d380-b6c8-11ea-9594-4aaa89d21375.png">

<img width="500" alt="Screenshot 2020-06-24 at 10 43 22 PM" src="https://user-images.githubusercontent.com/15804688/85687514-d87ce680-b6c8-11ea-9750-0f68a771ae79.png">

<img width="500" alt="Screenshot 2020-06-24 at 10 52 05 PM" src="https://user-images.githubusercontent.com/15804688/85687551-dfa3f480-b6c8-11ea-84d3-93649faf58c6.png">

<img width="500" alt="Screenshot 2020-06-24 at 10 52 23 PM" src="https://user-images.githubusercontent.com/15804688/85687613-ef233d80-b6c8-11ea-9b7c-8f89ad95db5e.png">

2020-06-25 12:17 UTC, Sirmorrison requested changes

2020-06-25 12:17 UTC, Sirmorrison commented on ui/seed_backup_page.go
> +}
time.AfterFunc() runs within a go routine by default. and you are currently using it with another go routine making it 2 go routines per call. why so?

2020-06-26 00:39 UTC, Sirmorrison commented
I noticed that if i am on the **Verify seed phrase** page (2/2) and i click the back button it sends me straight to the wallet home page. 

Is there a way i could use the back button to navigate to the previous page rather than the home page. Reason is, what if the user wants to verify something on the page (1/2) he will have to start the process all over again.

2020-06-26 00:54 UTC, Sirmorrison requested changes

2020-06-26 00:54 UTC, Sirmorrison commented on ui/seed_backup_page.go
> +				pg.error = "Failed to verify. Please go through every word and try again."
The error message here and on line 515 are repeating. Kind initialize a variable for this.

2020-06-26 00:54 UTC, Sirmorrison commented on ui/seed_backup_page.go
> +						pg.action.Background = pg.theme.Color.Primary
`pg.action.Background = pg.theme.Color.Primary` is repeated about 3 times sames as `pg.action.Color = pg.theme.Color.InvText`

These 2 can be added to `updateActionBackground()` and `updateActionColor()` respectively and called where needed.

2020-06-26 07:42 UTC, oshorefueled commented
> I noticed that if i am on the **Verify seed phrase** page (2/2) and i click the back button it sends me straight to the wallet home page.
> 
> Is there a way i could use the back button to navigate to the previous page rather than the home page. Reason is, what if the user wants to verify something on the page (1/2) he will have to start the process all over again.

That's the same behaviour on the mobile.

2020-06-27 14:27 UTC, Sirmorrison approved these changes
PR looks good to go.

2020-06-27 14:55 UTC, beansgum approved these changes

2020-06-27 20:40 UTC, merged