Tab indicator change
planetdecred/godcr pull request #176
Opened 2020-07-02 17:06 UTC by oshorefueled

####  Resolves
Issue #171. 

This PR replaces the previous tab change event implementation that was based on change variable with a slice implementation. Whenever there's a change event on the tab widget, the event is added to the event slice. The event slice is cleared on the next frame, enough time for every part of the app watching the event.

2020-07-06 22:06 UTC, Sirmorrison requested changes

2020-07-06 22:06 UTC, Sirmorrison commented on ui/overview_page.go
> +		toTransactions:     c.theme.Button("see all"),
Mobile says `See all` not `see all`

2020-07-06 22:06 UTC, Sirmorrison commented
Kind rebase the PR.

2020-07-07 17:14 UTC, Sirmorrison commented on ui/overview_page.go
> +		toTransactions:     c.theme.Button("see all"),
<img width="803" alt="image" src="https://user-images.githubusercontent.com/27733432/86817934-99ae3f80-c07d-11ea-827f-34c6b8b73b6f.png">

this review was not implemented.

2020-07-07 17:28 UTC, Sirmorrison approved these changes
PR looks good

2020-07-07 17:44 UTC, beansgum approved these changes

2020-07-07 17:46 UTC, merged