implement create/restore landing page
planetdecred/godcr pull request #22
Opened 2020-01-26 16:24 UTC by metaclips

### Resolves

Issue #

### What's new

_A detailed description of what this pull request adds_

### Relevant screenshots or logs

_If applicable, add screenshots or log entries to help explain your problem._

### Additional context

_Add any other context about the problem here._

2020-02-19 23:21 UTC, oluwandabira requested changes

2020-02-19 23:21 UTC, RogueElement commented on ui/themes/materialplus/materialplus.go
> +func RGB(c uint32) color.RGBA {
comment

2020-02-19 23:21 UTC, RogueElement commented on ui/themes/materialplus/materialplus.go
> +func argb(c uint32) color.RGBA {
comment

2020-02-19 23:21 UTC, RogueElement commented on ui/widgets/imagebutton.go
> +type ImageButton struct {
comment

2020-02-19 23:21 UTC, RogueElement commented on ui/window/window.go
> +	win.window = app.NewWindow(app.Title("GoDcr - decred wallet"), app.Size(unit.Dp(550), unit.Dp(800)))
Don't set the size (or at least don't set it to portrait)

2020-02-19 23:21 UTC, RogueElement commented on ui/widgets/imagebutton.go
> +	vmin := gtx.Constraints.Height.Min
Preferably `wmin` and `hmin` as that makes more sense

2020-02-20 00:18 UTC, oluwandabira requested changes

2020-02-20 00:18 UTC, RogueElement commented on ui/widgets/imagebutton.go
> +// Layout renders the select instance on screen
select?

2020-02-20 00:18 UTC, RogueElement commented on ui/themes/materialplus/materialplus.go
>  func argb(c uint32) color.RGBA {
really?

2020-02-20 00:18 UTC, RogueElement commented on ui/themes/materialplus/materialplus.go
> +// RGB converts Hex to RGBA
could this be a little more descriptive

2020-02-20 00:42 UTC, oluwandabira requested changes

2020-02-20 00:42 UTC, RogueElement commented on ui/page/landing.go
>  // and cannot find any wallets.
Please remove. It's outdated now

2020-02-20 00:42 UTC, RogueElement commented on ui/themes/materialplus/materialplus.go
> +func argb(c uint32) color.RGBA {
So they do the same thing?

2020-02-20 00:49 UTC, metaclips commented on ui/themes/materialplus/materialplus.go
> +func argb(c uint32) color.RGBA {
argb sets alpha color code

2020-04-10 14:08 UTC, metaclips commented
This is obsolete as button layout widget has been push upstream

2020-04-10 14:08 UTC, closed without merging