Notifications messages show in fixed postion
planetdecred/godcr pull request #235
Opened 2020-08-11 13:06 UTC by song50119

### Resolves

Issue #227 

<img width="912" alt="Screen Shot 2020-08-11 at 00 48 56" src="https://user-images.githubusercontent.com/9800579/89900450-f87f4f80-dc0d-11ea-8fa7-903f7286fac1.png">
<img width="912" alt="Screen Shot 2020-08-11 at 00 55 17" src="https://user-images.githubusercontent.com/9800579/89900478-ff0dc700-dc0d-11ea-8170-91fc133316ce.png">

2020-08-11 22:24 UTC, dreacot requested changes
![Screenshot from 2020-08-11 22-34-41](https://user-images.githubusercontent.com/25265396/89951340-228f3c80-dc23-11ea-8ed8-202f0fcefcb8.png)

The send page covers a portion of the notification, the padding of the notification looks like it's too much 

I'm running elementary os 5.1.7(Built on Ubuntu 18.04.4 LTS)
This screenshot above is the default window size of godcr

2020-08-12 15:40 UTC, song50119 commented
@dreacot thank for bring it up. Since the screen resolution is diffs, so I set minimum message height smaller

2020-08-12 20:01 UTC, dreacot commented
@song50119 the issue is fixed now

2020-08-13 18:41 UTC, oshorefueled approved these changes

2020-08-13 18:41 UTC, merged