Godcr newui
planetdecred/godcr pull request #262
Opened 2020-11-11 20:52 UTC by Sirmorrison

Fix #259 
Close #260 
This PR Implements the new Godcr UI Navigation, overview page and transactions page.

Transaction pages
==================
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/98862909-e9f04080-2467-11eb-99e0-98476a560073.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/27733432/98862856-dc3abb00-2467-11eb-8ca6-b13355322f06.png">

Overview Page
==================

<img width="794" alt="image" src="https://user-images.githubusercontent.com/27733432/98863012-0be9c300-2468-11eb-9bf1-3c78bda7ac42.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/27733432/98863040-160bc180-2468-11eb-8434-1794beabba72.png">

2020-11-16 20:23 UTC, oshorefueled requested changes

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/collapsible.go
> +	// line                  *Line
remove commented code

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/collapsible.go
> +	// c.line.Color.A = 140
remove commented code

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/collapsible.go
> +		// }),
remove commented code

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/combo.go
> +type Combo struct {
I'm not sure what a "combo" means. Seems like dropdown would be a better name.

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/combo.go
> +
you can remove the space

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/combo.go
> +						// }
remove commented code

2020-11-16 20:23 UTC, oshorefueled commented on ui/decredmaterial/combo.go
> +func (c *Combo) drawlayout(gtx layout.Context, isPopUp bool, body layout.Widget) layout.Dimensions {
use camel casing for the method name

2020-11-16 20:23 UTC, oshorefueled commented on ui/overview_page.go
> +			txnWidgets.statusIcon.Scale = 0.03
add a comment describing what these constants are for

2020-11-16 22:03 UTC, oshorefueled requested changes

2020-11-16 22:03 UTC, oshorefueled commented on ui/page.go
> +		)
why wasn't the tab widget modified to do this?

2020-11-16 22:03 UTC, oshorefueled commented on ui/transaction_details_page.go
> +			// }),
remove commented code

2020-11-16 22:03 UTC, oshorefueled commented on ui/transactions_page.go
> +	// "github.com/decred/dcrd/dcrutil"
remove commented code

2020-11-16 22:03 UTC, oshorefueled commented on ui/wallet_page.go
> +	// }
remove commented code

2020-11-17 22:11 UTC, Sirmorrison commented on ui/page.go
> +		)
No idea. This can be revisited when the PR is merged to prevent further stalling in the project.

2020-11-25 13:40 UTC, oshorefueled approved these changes

2020-11-25 13:41 UTC, merged