Settings page
planetdecred/godcr pull request #298
Opened 2021-01-11 23:38 UTC by Sirmorrison

Fix #295 
This Pr implement godcr settings page

<img width="797" alt="image" src="https://user-images.githubusercontent.com/27733432/104250425-e67c3400-546d-11eb-8918-8b2b7d913bd0.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/104250499-04499900-546e-11eb-9e34-669c111eb5f8.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/27733432/104250677-5f7b8b80-546e-11eb-930f-af372ff8e898.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/27733432/104250715-75894c00-546e-11eb-9854-49d3098518dd.png">

2021-01-13 10:43 UTC, oshorefueled requested changes

2021-01-13 10:43 UTC, oshorefueled commented on ui/modal_templates.go
> +func (m *ModalTemplate) passwordStrenght(th *decredmaterial.Theme, editors ...*widget.Editor) {
passwordStrength is misspelt

2021-01-13 10:43 UTC, oshorefueled commented on ui/page.go
> +func (page pageCommon) subPageBackAndTitleLayout(gtx layout.Context, sp SubPage) layout.Dimensions {
You can ignore stop words when creating function, method or  variable names. This would be better as "subpageBackTitleLayout". or better yet, simply "subpageHeader".

2021-01-13 10:43 UTC, oshorefueled commented on ui/page.go
> +func (page pageCommon) subPageEventHandle(sp SubPage) {
method name could be "subpageEventHandler" or "handleSubpageEvents".

2021-01-13 10:43 UTC, oshorefueled commented on ui/settings_page.go
> +	pg.changePass.Inset = zeroInset
put this in a single line

2021-01-13 10:43 UTC, oshorefueled commented on wallet/commands.go
> +// StartSync starts the multiwallet SPV sync
There's a conflict in the comment and method name

2021-01-13 10:43 UTC, oshorefueled commented on ui/window.go
> +				}
This seems redundant. The shutdown channel seems to already be closed when the system DestroyEvent is triggered.

2021-01-13 10:43 UTC, oshorefueled commented on ui/settings_page.go
> +					pg.wal.RestartSpvSync()
Is restarting sync the same as rescanning blocks?

2021-01-13 13:04 UTC, oshorefueled commented
Old spending password doesn't get cleared when I use the cancel button or when I successfully change my wallet password

<img width="796" alt="Screenshot 2021-01-13 at 14 03 40" src="https://user-images.githubusercontent.com/15804688/104455919-3c54f700-55a8-11eb-94d7-77cd628aab3c.png">

2021-01-13 13:06 UTC, oshorefueled commented
Kindly change the label on the remove wallet modal to "Spending password"
<img width="797" alt="Screenshot 2021-01-13 at 14 05 22" src="https://user-images.githubusercontent.com/15804688/104456038-65758780-55a8-11eb-951c-1f3a234ad600.png">

2021-01-14 07:33 UTC, Sirmorrison commented
> Old spending password doesn't get cleared when I use the cancel button or when I successfully change my wallet password
> 
> <img alt="Screenshot 2021-01-13 at 14 03 40" width="796" src="https://user-images.githubusercontent.com/15804688/104455919-3c54f700-55a8-11eb-94d7-77cd628aab3c.png">

resolved

2021-01-18 17:38 UTC, oshorefueled commented
Kindly make the change in the mockup to the settings page.

![Screenshot 2021-01-18 at 18 38 06](https://user-images.githubusercontent.com/15804688/104947637-5b92c080-59bc-11eb-8ec2-54fa7a30cbe2.png)

2021-01-19 11:46 UTC, oshorefueled approved these changes, later dismissed

2021-01-22 09:30 UTC, oshorefueled approved these changes

2021-01-22 09:33 UTC, merged