Transaction, overview UI & code cleanup
planetdecred/godcr pull request #356
Opened 2021-03-29 10:38 UTC by oshorefueled

This PR resolves issue #344. 

It also:
* contains code clean ups which include the addition of components.go, util.go and depricated.go file. Appropriate
   comments were added to each file describing the code that they contain. 
* modifies the progress bar widget. The default progress bar sets the max height to 4DP which doesn't allow a 8DP 
  height as specified in the overview mockup.
* adds a separator widget eliminating the need to initialize a Line object when initializing a page. And also repeatedly
  setting the width of the line. The same code is also present in PR #330.
* adds a Container type which is simply wrapper to the layout.Inset type to help differentiate when it is used as 
   padding or margin. Its purpose is to help visualize the structure of a layout by just reading the code.
* makes the transaction row layout reusable by both the transactions and overview page.

2021-03-30 14:18 UTC, JustinBeBoy commented
- The right margin is not aligned
<img alt="" height="500" src="https://user-images.githubusercontent.com/19331824/113003501-fec23c00-919c-11eb-911f-08f5ac74af9c.PNG">

- The button wrong text when wallet status is offline
<img alt="" height="500" src="https://user-images.githubusercontent.com/19331824/113003848-4e086c80-919d-11eb-93ab-866d6f4c3dfe.PNG">

2021-03-30 15:08 UTC, JustinBeBoy requested changes

2021-03-30 15:08 UTC, JustinBeBoy commented on ui/decredmaterial/progressbar.go
> +			fillColor := p.Color
The progress color is "41BE53" and background is E6EAED

2021-03-30 15:17 UTC, JustinBeBoy commented
The margin is 24
![11111](https://user-images.githubusercontent.com/19331824/113013133-a5aad600-91a5-11eb-962d-4be3e5690bfd.PNG)

2021-03-31 21:19 UTC, oshorefueled commented on ui/decredmaterial/progressbar.go
> +			fillColor := p.Color
Yes, the colours for the track and progress are set on the pages using the progress bar widget

2021-03-31 21:20 UTC, oshorefueled commented
> * The button wrong text when wallet status is offline
> 
> <img alt="" height="500" src="https://user-images.githubusercontent.com/19331824/113003848-4e086c80-919d-11eb-93ab-866d6f4c3dfe.PNG">

I'm not sure how to reproduce that error, you can create that as an issue and it will be resolved on another PR.

2021-04-07 13:08 UTC, dreacot approved these changes

2021-04-07 13:09 UTC, dreacot approved these changes

2021-04-07 15:00 UTC, C-ollins approved these changes

2021-04-07 15:27 UTC, JustinBeBoy approved these changes

2021-04-07 15:36 UTC, merged