Update ticket page
planetdecred/godcr pull request #395
Opened 2021-04-30 15:06 UTC by song50119

Resolves #387

2021-05-04 23:14 UTC, oshorefueled requested changes

2021-05-04 23:14 UTC, oshorefueled commented on go.sum
> -gioui.org v0.0.0-20210228180843-e1248651c871/go.mod h1:Y+uS7hHMvku1Q+ooaoq6fYD5B2LGoT8JtFgvmYmRzTw=
There's no go.mod file committed on this PR, a go.sum shouldn't be committed either.

2021-05-04 23:14 UTC, oshorefueled commented on ui/compontents.go
> +		acctName := wallSelect.Accounts[page.wallAcctSelector.selectedPurchaseTicketAccount].Name
`wallSelect.Accounts[page.wallAcctSelector.selectedPurchaseTicketAccount]` can be assigned to a variable ass "acc". You can then access the name as `acc.Name` and balance as  `acc.TotalBalance`

2021-05-04 23:14 UTC, oshorefueled commented on ui/page.go
> +	ticketRevokedIcon2,
Why do we have icons repeated with integer increments in their names? They seem to be the same icons.

2021-05-04 23:14 UTC, oshorefueled commented on wallet/commands.go
> +		}
This looks like a new vspd instance is created every time the PurchaseTicket method is called.

2021-05-04 23:15 UTC, oshorefueled commented
Recent activity doesn't look like it's taking account of every wallet created. I have tickets that are more recent than 109 days.

<img width="562" alt="Screenshot 2021-05-05 at 00 06 58" src="https://user-images.githubusercontent.com/15804688/117081014-e793e280-ad36-11eb-8ca9-13bce1758014.png">

2021-05-05 03:27 UTC, song50119 commented on ui/page.go
> +	ticketRevokedIcon2,
Same icon but different size

2021-05-10 17:00 UTC, oshorefueled approved these changes

2021-05-10 17:25 UTC, merged