update the editor design of the restore page
planetdecred/godcr pull request #419
Opened 2021-05-17 21:46 UTC by dreacot

Resolves #408 

This PR fixes the following;
- extend vertical line to reach horizontal borders
- make width of editors id to be the same
- make the vertical line bolder
- make the editor's content change to blue while focused

**Screenshots**
<img width="800" alt="Screenshot 2021-05-17 at 10 36 14 PM" src="https://user-images.githubusercontent.com/25265396/118560543-8c63e600-b761-11eb-968b-38eb0572babf.png">

2021-05-18 01:12 UTC, C-ollins requested changes
Input size is too large
<img src="https://user-images.githubusercontent.com/19960200/118575363-36516b80-b77e-11eb-8721-f5c31553eef3.png" width="500">

2021-05-18 01:49 UTC, C-ollins approved these changes, later dismissed

2021-05-20 14:11 UTC, oshorefueled requested changes

2021-05-20 14:11 UTC, oshorefueled commented on ui/decredmaterial/editor.go
> +				gtx.Constraints.Min.X = int(gtx.Metric.PxPerDp) * 40
replace the explicit DPI conversion with the standard unit type as done in PR #418

2021-05-20 14:55 UTC, oshorefueled approved these changes

2021-05-20 14:55 UTC, merged