Add progress bar to material plus theme
planetdecred/godcr pull request #42
Opened 2020-02-04 23:56 UTC by oshorefueled

### Resolves

Issue #23 

### What's new
adds a progressbar to the custom material theme

### Relevant screenshots or logs
<img width="799" alt="Screenshot 2020-02-05 at 12 54 21 AM" src="https://user-images.githubusercontent.com/15804688/73798083-1af16580-47b2-11ea-80bf-08d23642a5a0.png">

2020-02-05 14:04 UTC, hydra0210 requested changes

2020-02-05 14:04 UTC, yaowork commented on ui/page/ui-test.go
> +		},
Please move this above the load button

2020-02-05 14:04 UTC, codemaestro64 commented on ui/values/colors.go
> +)
There's a file that declares colors already (```ui/colors,go```). Please use that instead.

2020-02-11 18:00 UTC, oluwandabira approved these changes

2020-02-11 23:13 UTC, oluwandabira requested changes

2020-02-11 23:13 UTC, RogueElement commented on ui/themes/materialplus/progressbar.go
> +}
The fields should just be exported.

2020-02-11 23:53 UTC, oluwandabira approved these changes

2020-02-12 00:01 UTC, merged