Restore page
planetdecred/godcr pull request #43
Opened 2020-02-05 18:34 UTC by song50119

### Resolves

Issue #16

### What's new

Test

2020-02-07 14:51 UTC, song50119 commented
Add radio buttons page "Spending password and PIN"
<img width="912" alt="Screen Shot 2020-02-07 at 21 47 58" src="https://user-images.githubusercontent.com/9800579/74038917-8a09cc80-49f3-11ea-96a0-9197fa302bb5.png">

2020-02-08 12:26 UTC, oluwandabira submitted a review, later dismissed

2020-02-19 14:28 UTC, oluwandabira requested changes

2020-02-19 14:28 UTC, RogueElement commented on ui/page/landing.go
> +			}
`if pg.restoreWdg.Clicked(gtx)` is duplicated

2020-02-19 14:28 UTC, RogueElement commented on ui/page/restore.go
> +	pg.editorSendingPin = &widget.Editor{SingleLine: true}
No more pin

2020-02-19 14:28 UTC, RogueElement commented on ui/page/restore.go
> +		pg.confirmErrorMsg.Text = "Please enter confirm password"
"Please enter confirm password" => "Confirm password"

2020-02-19 14:28 UTC, RogueElement commented on ui/page/restore.go
> +		pg.confirmErrorMsg.Text = "Password and confirm password do not match"
"Password and confirm password do not match" => "Passwords do no match"

2020-02-19 14:28 UTC, RogueElement commented on ui/page/restore.go
> +			if resp.Err != nil {
See #32 for how to handle non-blocking wallet commands. TLDR: page issues the command, window receives the result.

2020-02-20 19:46 UTC, oluwandabira requested changes

2020-02-20 19:46 UTC, RogueElement commented on ui/page/restore.go
> +		pg.states[StateWalletRespondedError] = nil
delete the key

2020-02-20 19:46 UTC, RogueElement commented on ui/page/restore.go
> +		pg.states[StateWalletRestored] = nil
delete the key

2020-02-20 19:46 UTC, RogueElement commented on ui/page/restore.go
> +	if pg.states[StateWalletRestored] == nil {
check for the existence of the key

2020-02-20 19:46 UTC, RogueElement commented on ui/page/restore.go
> +	if pg.states[StateWalletRespondedError] == nil {
check for the existence of the key

2020-02-21 10:59 UTC, oluwandabira submitted a review, later dismissed

2020-03-10 14:09 UTC, oshorefueled requested changes

2020-03-10 14:09 UTC, oshorefueled commented on ui/restore_page.go
> +					win.gtx.Constraints.Width.Min = 210
you should avoid using hardcoded values in your code.

2020-03-10 18:15 UTC, oluwandabira requested changes

2020-03-10 18:15 UTC, RogueElement commented on ui/window.go
> +				win.KeysEventsHandler()
Pass the key event as an argument to `win.KeysEventsHandler`

2020-03-10 18:15 UTC, RogueElement commented on ui/handle_input.go
> +func (win *Window) KeysEventsHandler() {
This should take the key event as an argument since it is only used within this scope.

2020-03-10 18:15 UTC, RogueElement commented on ui/widgets.go
> +	seedsSuggestions        []string
Not widgets.

2020-03-10 18:15 UTC, RogueElement commented on ui/widgets.go
> +	keyEvent                *key.Event
Unnecessary.

2020-03-10 18:15 UTC, RogueElement commented on ui/widgets.go
> +	seedsSuggestionsBtn     [2]widget.Button
Input widget.

2020-03-14 14:59 UTC, oluwandabira submitted a review, later dismissed

2020-03-15 17:35 UTC, metaclips approved these changes
UI functionality looks good

2020-03-15 22:38 UTC, oluwandabira approved these changes

2020-03-15 23:20 UTC, oshorefueled approved these changes

2020-03-15 23:23 UTC, merged