Add info tooltip to a ticket page
planetdecred/godcr pull request #448
Opened 2021-05-31 15:18 UTC by JustinBeBoy

This PR resolve #428 

This PR all tooltip in LIVE and info of ticket in ticket page

2021-06-02 10:42 UTC, oshorefueled requested changes

2021-06-02 10:42 UTC, oshorefueled commented on ui/components.go
> +		}
a switch statement would be much cleaner here

2021-06-02 10:42 UTC, oshorefueled commented on ui/components.go
> +		message2 := ""
```suggestion
		var title, message, message2 string
```

2021-06-02 10:42 UTC, oshorefueled commented on ui/components.go
> +		status := c.theme.Label(values.MarginPadding14, t.Info.Status)
```suggestion
		status := c.theme.Body2(t.Info.Status)
```

2021-06-10 02:27 UTC, Sirmorrison requested changes

2021-06-10 02:27 UTC, Sirmorrison commented on ui/components.go
> +}
```suggestion
		st.icon.Scale = .5
		return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
			layout.Rigid(func(gtx C) D {
				return layout.Flex{Axis: layout.Horizontal}.Layout(gtx,
					layout.Rigid(st.icon.Layout),
					layout.Rigid(toolTipContent(gtx, layout.Inset{Top: values.MarginPadding4}, status.Layout)),
				)
			}),
			layout.Rigid(toolTipContent(gtx, layout.Inset{Top: values.MarginPadding8}, titleLabel.Layout)),
			layout.Rigid(toolTipContent(gtx, layout.Inset{Top: values.MarginPadding8}, messageLabel.Layout)),
			layout.Rigid(func(gtx C) D {
				if message2 != "" {
					toolTipContent(gtx, layout.Inset{Top: values.MarginPadding8}, messageLabel.Layout)
				}
				return layout.Dimensions{}
			}),
		)
	})
}

func toolTipContent(gtx layout.Context, inset layout.Inset, body layout.Widget) layout.Widget {
	return func(gtx C) D {
		return inset.Layout(gtx, body)
	}
}
```

2021-06-10 02:27 UTC, Sirmorrison commented on ui/tickets_page.go
> +						return ticketCard(gtx, c, &tickets[index], tooltip)
```suggestion
						return ticketCard(gtx, c, &tickets[index], c.theme.Tooltip())
```

2021-06-11 04:32 UTC, Sirmorrison requested changes, later dismissed

2021-06-11 04:32 UTC, Sirmorrison commented on ui/components.go
> +					}),
You seem to have skipped this. kindly move `st.icon.Scale = .5` to line 675 or to line 641. it really does not need to be where it is.
```suggestion
					layout.Rigid(st.icon.Layout),
```

2021-06-12 10:31 UTC, oshorefueled approved these changes

2021-06-12 19:47 UTC, merged