Ticket page design details
planetdecred/godcr pull request #458
Opened 2021-06-03 15:21 UTC by tuhalang

Resolve #449 
- Fix breaking into new line of wallet title in ticket card
- Add live data for progress bar and time
- Add icon timer

2021-06-12 20:37 UTC, oshorefueled commented
* The ticket status and wallet name on the ticket cards still break into a new line on my display. 
* If the lifecycle of a ticket is complete, it shouldn't display the time left till completion. Kindly check the mockups
   on Figma to correct the current implementation.
* The ticket should read 14d not 14 days. Hours should be 8h not < 1 day.
<img width="558" alt="Screenshot 2021-06-12 at 21 29 52" src="https://user-images.githubusercontent.com/15804688/121788460-5af60300-cbc5-11eb-9513-b073fd071399.png">

2021-08-23 13:54 UTC, Sirmorrison requested changes

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +
Remove space

2021-08-23 13:54 UTC, Sirmorrison commented on ui/decredmaterial/theme.go
> +// mulAlpha scales all color components.go by alpha/255.
Kindly revert this... the  comments is talking about the component not the file.

2021-08-23 13:54 UTC, Sirmorrison commented on ui/load/load.go
> +// for code you feel might be shared with other components.go in the future. Before adding code here, ask yourself, can
Kindly revert this... the comments is talking about the component not the file.

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/components/components.go
> +// components.go contain layout code that are shared by multiple pages but aren't widely used enough to be defined as
Kindly revert this... the comments is talking about the component package not the file.

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/components/components.go
> +// ticketActivityRow layouts out ticket info, display ticket activities on the tickets_page.go and tickets_activity_page
Kindly revert this.

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +									}
```suggestion
									if totalTime == 0 {
										return layout.Dimensions{}
									}
```

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +										txt.TextSize = unit.Sp(12)
```suggestion
										txt.TextSize = values.TextSize12
```

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +										txt.TextSize = unit.Sp(14)
```suggestion
										txt.TextSize = values.TextSize14
```

2021-08-23 13:54 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +// ticketActivityRow layouts out ticket info, display ticket activities on the tickets_page.go and tickets_activity_page
Revert this

2021-08-25 08:03 UTC, Sirmorrison requested changes
> * The ticket status and wallet name on the ticket cards still break into a new line on my display.
> * If the lifecycle of a ticket is complete, it shouldn't display the time left till completion. Kindly check the mockups
>   on Figma to correct the current implementation.
> * The ticket should read 14d not 14 days. Hours should be 8h not < 1 day.
> 
> <img alt="Screenshot 2021-06-12 at 21 29 52" width="558" src="https://user-images.githubusercontent.com/15804688/121788460-5af60300-cbc5-11eb-9513-b073fd071399.png">

These comments does not seem to have been resolved.
The progress bar also does not seem to work from my end.

2021-08-25 08:03 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +											txt.Text = fmt.Sprintf("%d%s", timeBehind, unit)
This does not seem to be taking effect as the ticket age still shows as `day` instead of `d`
 
![image](https://user-images.githubusercontent.com/27733432/130748779-94aa7e87-6f86-4e90-9089-28207150bc45.png)

2021-08-25 12:58 UTC, tuhalang commented on ui/page/tickets/utils.go
> +											txt.Text = fmt.Sprintf("%d%s", timeBehind, unit)
![image](https://user-images.githubusercontent.com/33905113/130794724-588324c7-6d82-4e42-8317-e37f9379f6ef.png)

2021-08-25 12:59 UTC, tuhalang commented on ui/page/tickets/utils.go
> +											txt.Text = fmt.Sprintf("%d%s", timeBehind, unit)
i see every things is ok

2021-08-31 11:18 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +											txt.Text = fmt.Sprintf("%d%s", timeBehind, unit)
kindly try purchasing a new ticket and you will see this
![image](https://user-images.githubusercontent.com/27733432/131493555-1c0cc6f7-0ed9-40dc-9ddc-8b96b21fba26.png)

2021-09-14 23:19 UTC, Clariceco commented
@tuhalang what is the status of this?

2021-09-15 06:18 UTC, Sirmorrison commented
Most of the changes here have been addressed on PR #567. We will be closing this when #567 is merged.

2021-09-15 19:41 UTC, closed without merging