Add main page
planetdecred/godcr pull request #459
Opened 2021-06-04 08:28 UTC by C-ollins

This pr adds a new page, `MainPage`, and its job is to manage the app toolbar, navigation bar, and back stack history of other pages and it also moves the independent management of the page navigation from the pages to `MainPage`.

2021-06-04 10:51 UTC, dreacot commented
1. Navigating to the tickets page crashes the app

2. Clicking on the wallet selector doesn't work on both the send and receive page
<img width="564" alt="Screenshot 2021-06-04 at 11 27 19 AM" src="https://user-images.githubusercontent.com/25265396/120788072-f59c7500-c527-11eb-94fa-700ebf75eadc.png">

3. clicking on the send page, then the receive page right after, the x button closes the receive page but not the send page
<img width="193" alt="Screenshot 2021-06-04 at 11 31 56 AM" src="https://user-images.githubusercontent.com/25265396/120788666-7e1b1580-c528-11eb-9ce7-bb6d44c4f2fa.png">

4. clicking clear all fields on the send page only clears the amount and not the address
<img width="568" alt="Screenshot 2021-06-04 at 11 34 00 AM" src="https://user-images.githubusercontent.com/25265396/120788962-dd792580-c528-11eb-842f-aaeafa4710d6.png">

5. clicking "got it" on the modal that displays on the security tools page does nothing
<img width="459" alt="Screenshot 2021-06-04 at 11 37 48 AM" src="https://user-images.githubusercontent.com/25265396/120789349-6d1ed400-c529-11eb-83d6-e94cea1aa4e7.png">

6. clicking the edit button on the account details page causes the app to crash
<img width="573" alt="Screenshot 2021-06-04 at 11 40 57 AM" src="https://user-images.githubusercontent.com/25265396/120789669-cedf3e00-c529-11eb-8cf6-9f8f5e400cd3.png">

7. clicking account[1] for my second wallet, shows the the account details of account[1] for my first wallet

8. The toast message doesn't disappear
<img width="292" alt="Screenshot 2021-06-04 at 11 45 20 AM" src="https://user-images.githubusercontent.com/25265396/120790102-66449100-c52a-11eb-81a4-8f3202313f07.png">

2021-06-04 20:04 UTC, oshorefueled requested changes

2021-06-04 20:04 UTC, oshorefueled commented on ui/window.go
>  }
This method doesn't seem to be doing anything, it can be removed. The win.refresh() method isn't needed as well. Each page can handle invalidating the page by calling op.InvalidateOp. The changePageAndRefresh doesn't seem to be doing anything either.

2021-06-04 20:04 UTC, oshorefueled commented on ui/wallet_page.go
> +	// }
This can be deleted if it's not needed.

2021-06-04 20:06 UTC, oshorefueled commented
The top bar doesn't seem to be updated until I restart the app. I changed the currency conversion option in the settings page and it doesn't get displayed on the top bar until I restart the app.

2021-06-05 10:09 UTC, oshorefueled approved these changes

2021-06-05 10:37 UTC, merged