Add modal interface and migrate existing modals
planetdecred/godcr pull request #460
Opened 2021-06-05 16:28 UTC by C-ollins

This pr adds a `Modal` interface, an interface for creating and managing custom modals made to replace the current modal manager which uses a global instance for all modals.  A `showModal` & `dismissModal` function is also added to MainPage and made available to all pages via `pageCommon`l. The `showModal` function allows displaying multiple modals at once which are stacked on each other and ordered with the latest modal on top and `dismissModal` helps with dismissing a specific modal.

2021-06-06 14:50 UTC, dreacot approved these changes, later dismissed

2021-06-09 14:25 UTC, oshorefueled requested changes

2021-06-09 14:25 UTC, oshorefueled commented on ui/create_watch_only_modal.go
> +func (cm *createWatchOnlyModal) callbackFunc(callback func(walletName, extPubKey string, m *createWatchOnlyModal) bool) *createWatchOnlyModal {
a better name for this would be `watchOnlyCreated` or `walletCreated`. You did something similar here https://github.com/planetdecred/godcr/pull/460/files#diff-a1dc465a2f07bd3ed4f26a53ae45bf1edd88004d5af4b2353493cb1b8e0cf14dR106

2021-06-09 14:25 UTC, oshorefueled commented on ui/modal.go
> +type Modal interface {
dismiss and show seems to be a common method on every modal and should be defined on the interface

2021-06-09 14:25 UTC, oshorefueled commented on ui/text_input_modal.go
> +	callback  func(string, *textInputModal) bool
a comment should probably be added that the callback here and in other modals where they appear would be optional on some modals and the main aim of the modal is to have it handle their intended functions within the modal.

2021-06-10 15:45 UTC, oshorefueled approved these changes

2021-06-10 22:34 UTC, merged