proposal voting modal
planetdecred/godcr pull request #468
Opened 2021-06-15 15:58 UTC by song50119

Resolves #463 
<img width="912" alt="Screen Shot 2021-06-15 at 22 54 42" src="https://user-images.githubusercontent.com/9800579/122085433-e91ff280-ce2c-11eb-8826-70ea81cc93e6.png">

2021-06-15 16:01 UTC, C-ollins requested changes

2021-06-15 16:01 UTC, C-ollins commented on ui/proposal_details_page.go
> +	}
This should be handled using the modal interface. The layout and handlers for the modal should not be in this file. Create a modal for this.

2021-06-15 16:04 UTC, C-ollins commented on ui/proposal_details_page.go
> +	}
Checkout this modal https://github.com/planetdecred/godcr/blob/master/ui/info_modal.go

2021-06-16 18:41 UTC, oshorefueled requested changes

2021-06-16 18:41 UTC, oshorefueled commented on ui/proposal_details_vote_modal.go
> +type inputVoteModal struct {
`voteModal` is just fine for the struct name. The file name can also be vote_modal or proposal_vote_modal.

2021-06-16 18:41 UTC, oshorefueled commented on ui/proposal_details_vote_modal.go
> +	inc        decredmaterial.IconButton
kindly use variable names that have meaning. `increment` and `decrement` means.

2021-06-16 18:41 UTC, oshorefueled commented on ui/proposal_details_vote_modal.go
> +func (cm *inputVoteModal) passwordCreated(callback func(password string, m *inputVoteModal) bool) *inputVoteModal {
the proposal vote modal doesn't create a password. This could be `passwordSubmitted`

2021-06-16 18:41 UTC, oshorefueled commented on ui/proposal_details_vote_modal.go
> +}
This method can be above the `handle` method and renamed to `handleVoteCountButtons`

2021-06-23 20:53 UTC, oshorefueled submitted a review, later dismissed

2021-06-24 06:54 UTC, C-ollins requested changes

2021-06-24 06:54 UTC, C-ollins commented on ui/proposal_vote_modal.go
> +}
These functions can be removed and you can use a default title since this modal is for one purpose.

2021-06-24 06:54 UTC, C-ollins commented on ui/proposal_vote_modal.go
> +func (cm *voteModal) setError(err string) {
This function is not used.

2021-06-24 06:54 UTC, C-ollins commented on ui/proposal_vote_modal.go
> +func (cm *voteModal) passwordSubmitted(callback func(password string, m *voteModal) bool) *voteModal {
This callback isn't required as the voting can be done in this modal.

2021-06-29 06:36 UTC, C-ollins approved these changes

2021-06-29 07:38 UTC, oshorefueled approved these changes

2021-06-29 07:39 UTC, merged