Add HTML Renderer
planetdecred/godcr pull request #469
Opened 2021-06-16 07:48 UTC by codemaestro64

fixes #461

2021-06-17 16:00 UTC, C-ollins requested changes
- No text is rendered if I pass a text without html tags.
<img src="https://user-images.githubusercontent.com/19960200/122431888-bee54680-cf8c-11eb-9c33-56f82b6de29e.png" width="400">

- Rendered text overflows the constrained width, the text should be wrapped to fit parent container.
<img src="https://user-images.githubusercontent.com/19960200/122432164-0075f180-cf8d-11eb-973e-3ed3f05c0477.png" width="400">

This is how the dialog displays when using regular text label `th.Body1`.

<img src="https://user-images.githubusercontent.com/19960200/122432442-3a46f800-cf8d-11eb-8395-72bf984c0e93.png" width="400">

2021-06-20 09:00 UTC, C-ollins requested changes
- Trying to render
```html
    Tap on <span style="text-color: primary">blue text</span> to copy the item.
```
results in:
<img src="https://user-images.githubusercontent.com/19960200/122667700-11507e00-d1ac-11eb-9834-43643a274b92.png" width="500">

2021-06-20 09:00 UTC, beansgum commented on ui/renderers/html.go
> +		nodeName := goquery.NodeName(node)
It looks every single element is rendered separately which is what resulted in this. Rendering should be done in a nested way.
```html
    <span>Tap on <span style="text-color: primary">blue text</span> to copy <strong>the</strong> item.</span>
```
<img src="https://user-images.githubusercontent.com/19960200/122667855-021e0000-d1ad-11eb-9e3d-4c2db888fcf7.png" width="500">

2021-06-20 09:00 UTC, beansgum commented on ui/renderers/html.go
> +		case "html", "head":
This is missing some basic html tags like bold `<b>`, italics `<i>`, font `<font>` & line-break `<br>`.

2021-06-25 05:25 UTC, C-ollins requested changes
The text size doesn't look correct
<img src="https://user-images.githubusercontent.com/19960200/123370796-5f80cb00-d578-11eb-8625-80c153707d11.png" width="400">

- Attempting to render a font tag produces this
```html
<font color="danger">INVALID</font>
```
<img src="https://user-images.githubusercontent.com/19960200/123371933-8dffa580-d57a-11eb-8c49-c901fb47f1d2.png" width="400">

- Line break does not work
```
<span style="text-color: primary">INVALID</span> <br/> <span style="text-color: gray">INVALID</span>
```
<img src="https://user-images.githubusercontent.com/19960200/123372385-5c3b0e80-d57b-11eb-99db-bfd297b29e67.png" width="400">

- The styling should end where the tag ends.
```html
Tap on <span style="text-color: primary">blue text</span> to copy the item.
```
![Screenshot 2021-06-25 at 06 08 23](https://user-images.githubusercontent.com/19960200/123372603-c9e73a80-d57b-11eb-8114-79e1d7ea9dc5.png)

2021-06-25 05:25 UTC, beansgum commented on ui/renderers/renderer.go
> +	//md "github.com/gomarkdown/markdown"
cleanup imports

2021-06-25 05:25 UTC, beansgum commented on ui/modal_templates.go
> +				 		<span style="text-color: primary; font-weight: bold">Nested span</span>
There's unrelated text in this html.

2021-06-25 05:25 UTC, C-ollins commented on ui/modal_templates.go
> +	text := `<div style="text-color: gray">
Use `span` for styling, `div` is not required anywhere in here.

2021-06-25 05:25 UTC, C-ollins commented on ui/modal_templates.go
> +			text := `<div style="text-color: success; font-weight: bold">
The styling here is off, reference the design mockup for the proper text style.

2021-06-25 05:25 UTC, C-ollins commented on ui/modal_templates.go
> +			<h4>This action cannot be undone.</h4>`
This text is actually bold and it should inherit the text size of the parent tag which means it should be inside the parent tag. Reference the design mockup for proper text styling.
```suggestion
			<b>This action cannot be undone.</b>`
```

2021-06-25 05:25 UTC, C-ollins commented on ui/modal_templates.go
> +
A sentence like this should be render as:
```html
<span style="text-color: gray">Tap on <span style="text-color: primary">blue text</span> to copy the item</span>
```

2021-06-25 05:25 UTC, C-ollins commented on ui/modal_templates.go
> +		renderers.RenderHTML(text, th).Layout,
How is text size set for rendered text?

2021-06-25 05:25 UTC, C-ollins commented on ui/renderers/html.go
> +	blockEls = []string{"div", "p", "h1", "h2", "h3", "h4", "h5", "h6", "ul"}
There's no point having a `<ul>` tag without `<ol>` and `<li>`.

2021-06-25 05:25 UTC, C-ollins commented on ui/renderers/renderer.go
> +	fmt.Println("ssss")
🐍

2021-06-25 16:15 UTC, C-ollins requested changes
- Color codes don't work in the font tag
```html
<font color="#2970FF">Confirmed</font> &centerdot; 6 Confirmations
```
<img src="https://user-images.githubusercontent.com/19960200/123453371-5d018e00-d5d7-11eb-820e-457e08471acb.png" width="400">

- styling does not recognize the color attribute
```html
<span style="color: gray">
    Signing a message with an address' private key allows you to prove that 
    you are the owner of a given address to a possible counterparty.
</span>
```

2021-06-28 06:03 UTC, C-ollins requested changes
- The renderer adds an empty space after a tag
```html
<font color="#ed6d47">INVALID</font>.
```
<img src="https://user-images.githubusercontent.com/19960200/123585764-a3273f00-d7db-11eb-97a0-0b475579bd59.png" width="400">

2021-06-29 06:25 UTC, C-ollins requested changes
- The renderer removes empty space included space after a tag
```html
<font color="#ed6d47">INVALID</font> Space.
```
<img src="https://user-images.githubusercontent.com/19960200/123746723-f1a30f00-d8a9-11eb-8752-345af737d7f1.png" width="400">

2021-06-29 09:58 UTC, C-ollins requested changes
The renderer removes empty space included space before a tag.

```html
otherwise <font color="#ed6d47">INVALID</font>.
```

<img src="https://user-images.githubusercontent.com/19960200/123778282-d98eb800-d8c8-11eb-8680-b60057ea5eda.png" width="400">

2021-07-02 06:34 UTC, C-ollins approved these changes
Header tags are supposed to render big and bold but we don't need those.
```html
<h1>This is heading 1</h1>
<h2>This is heading 2</h2>
<h3>This is heading 3</h3>			
<p>This is a paragraph.</p>
<p>This is a <br/> paragraph with a line break.</p>
<p style="color: #FF0000;">This is a red paragraph.</p>
<p><b>This text is bold</b></p>
<p><i>This text is italic</i></p>
<strong>This text is important!</strong>
```
<img src="https://user-images.githubusercontent.com/19960200/124230976-9d956600-db07-11eb-8637-10cbb536f910.png" width="400">

2021-07-02 07:43 UTC, oshorefueled approved these changes

2021-07-02 07:45 UTC, merged