Cleanup wallets page & its sub pages
planetdecred/godcr pull request #493
Opened 2021-06-25 14:44 UTC by C-ollins

Changes included in this pr:
 - Use dcrlibwallet directly in wallets, account details, sign message, privacy & wallet settings page
 - Use walletListItem to manage data displayed in the wallet and account list row.
 - Add ClickableList to handle click events for list items.
 - Hide staking balances in the account details page if all staking balances are 0.
 - Hide imported account if balance is 0.

2021-06-30 20:25 UTC, oshorefueled requested changes

2021-06-30 20:25 UTC, oshorefueled commented on ui/decredmaterial/list.go
> +func (t *Theme) NewClickableList(axis layout.Axis) *ClickableList {
The name of the file should probably be clickable_list.go so it isn't taken outrightly as the already existing list widget.

2021-06-30 22:18 UTC, oshorefueled commented
Menu for watch only wallets isn't easily accessible and properly aligned. Clicking the menu should display it upwards not downwards. 
Current Implementation
<img width="658" alt="Screenshot 2021-06-30 at 23 15 45" src="https://user-images.githubusercontent.com/15804688/124038526-283b6f80-d9f9-11eb-9a01-d688ab5b094b.png">

Mockup
![Screenshot 2021-06-30 at 23 18 02](https://user-images.githubusercontent.com/15804688/124038686-705a9200-d9f9-11eb-8fb9-ec17db004428.png)

2021-07-02 07:57 UTC, oshorefueled approved these changes

2021-07-02 11:19 UTC, dreacot approved these changes

2021-07-02 13:52 UTC, merged