Group pages and modals into packages
planetdecred/godcr pull request #512
Opened 2021-07-01 01:33 UTC by oshorefueled

This PRs groups pages and modals into their own packages. It also adds a load package which would replace the common struct shared among pages, modals and a number of other godcr components.

2021-07-07 05:23 UTC, C-ollins requested changes

2021-07-07 05:23 UTC, beansgum commented on ui/create_restore_page.go
> +				pg.common.changeWindowPage(newMainPage(pg.common, nil), false)
`nil` value passed for the load parameter can cause a nil pointer exception.

2021-07-07 05:23 UTC, beansgum commented on ui/main_page.go
> +	mp.updateBalance()
This probably got in from rebase, the `updateBalance` function have been moved to on resume and is called when notifications are received.

2021-07-07 05:23 UTC, beansgum commented on ui/main_page.go
> +	// todo: common methods will be removed when
Typo in comment.

2021-07-07 05:23 UTC, beansgum commented on ui/main_page.go
> +func (mp *mainPage) _changeFragment(page interface{}, id string) {
I think it's better to move the `Page` interface to the page package and let the pages in this package import it to avoid this anonymous cast.

2021-07-07 05:23 UTC, beansgum commented on ui/markdown.go
> +package ui
Delete this file, it has been moved to the `ui/renderers` package.

2021-07-07 05:23 UTC, beansgum commented on ui/modal/info_modal.go
> +type Common interface {
Remove unused interface.

2021-07-07 05:23 UTC, beansgum commented on ui/modal/modal.go
> +
This file does not contain any model-specific content, I guess it can be renamed to `utils.go`.

2021-07-07 05:23 UTC, beansgum commented on ui/modal_templates.go
> +			text := th.Body1("After you or your counterparty has genrated a signature, you can use this form to verify the" +
Fix error from rebasing, this text and the text in other functions in this file have been replaced with HTML.

2021-07-07 05:23 UTC, beansgum commented on ui/main_page.go
> +	mp.changeFragment(page.NewOverviewPage(mp.load), page.Overview)
Check for the current page before switching to overview.
```suggestion
	if pg, ok := mp.pages[mp.current]; ok {
		pg.OnResume()
	} else {
		mp.changeFragment(OverviewPage(mp.pageCommon), PageOverview)
	}
```

2021-07-07 05:23 UTC, beansgum commented on ui/page.go
> +	pages[PageWallet] = WalletPage(common, l)
Wallets page isn't part of this list.

2021-07-07 05:23 UTC, beansgum commented on ui/main_page.go
> +				mp.changeFragment(page.NewTransactionsPage(mp.load), page.Transactions)
Wallets page was included here and has been removed.

2021-07-07 05:23 UTC, beansgum commented on ui/page/about_page.go
> +const About = "About"
Why was the `Page` prefix remove from the page's name constant? This would get confusing as this constant will always show up when typing `About-`. I'd recommend that prefix should be restored or it can be changed to something better like `AboutPageID` since the constants are used as ids.

2021-07-07 05:23 UTC, beansgum commented on ui/page/components.go
> +)
Remove unused constants.

2021-07-07 05:23 UTC, beansgum commented on ui/page/components.go
> +//func (page *pageCommon) layoutBalance(gtx layout.Context, amount string, isSwitchColor bool) layout.Dimensions {
Delete unused codes.

2021-07-07 05:23 UTC, beansgum commented on ui/page/components.go
> +func displayToast(th *decredmaterial.Theme, gtx layout.Context, t *load.Toast) layout.Dimensions {
Remove unused function, this file needs cleanup.

2021-07-07 05:23 UTC, C-ollins commented on ui/page/markdown.go
> +
Not sure how this file got there but it doesn't belong to this folder.

2021-07-07 05:23 UTC, C-ollins commented on ui/page/more_page.go
> +														// todo: uncomment when security tools has been moved to the page package
Security tools have been moved to the page package, time to uncomment.

2021-07-07 05:23 UTC, C-ollins commented on ui/page/page.go
> +	title                     string
Remove unused structs.

2021-07-07 05:23 UTC, C-ollins commented on ui/page/transactions_page.go
> +	log.Infof("WALLETS GUY! MULTI %v\n", pg.Load)
😁

2021-07-07 05:23 UTC, C-ollins commented on ui/page/verify_message_page.go
> +			valid, err := pg.WL.Wallet.VerifyMessage(pg.addressInput.Editor.Text(), pg.messageInput.Editor.Text(), pg.signInput.Editor.Text())
```suggestion
			valid, err := pg.WL.MultiWallet.VerifyMessage(pg.addressInput.Editor.Text(), pg.messageInput.Editor.Text(), pg.signInput.Editor.Text())
```

2021-07-07 05:23 UTC, C-ollins commented on ui/send_page.go
> +
Cleanup imports.

2021-07-07 05:23 UTC, C-ollins commented on ui/window.go
> +	//}
Delete.

2021-07-08 10:37 UTC, C-ollins requested changes

2021-07-08 10:37 UTC, C-ollins commented on ui/page/verify_message_page.go
> +				pg.ChangePage(*pg.ReturnPage)
Wallet page have been moved.

2021-07-08 10:48 UTC, C-ollins requested changes

2021-07-08 10:48 UTC, C-ollins commented on ui/page/verify_message_page.go
> +	if *pg.ReturnPage == SecurityTools {
Remove this, verify message page isn't available in wallet's option.

2021-07-08 10:48 UTC, C-ollins commented on ui/page/page.go
> +	walletInfoButton          decredmaterial.IconButton
Delete unused structs.

2021-07-08 12:29 UTC, oshorefueled commented on ui/page/components.go
> +func displayToast(th *decredmaterial.Theme, gtx layout.Context, t *load.Toast) layout.Dimensions {
some methods were left commented or unused because they'll be called the pages calling them have been migrated to the page package.

2021-07-09 05:16 UTC, C-ollins requested changes

2021-07-09 05:16 UTC, C-ollins commented on ui/page/license_page.go
> +const license = `ISC LicenseText
```suggestion
const license = `ISC License
```

2021-07-09 05:16 UTC, C-ollins commented on ui/page/wallet_page.go
> +const Wallet = "Wallets"
```suggestion
const WalletPageID = "Wallets"
```

2021-07-09 05:16 UTC, C-ollins commented on ui/privacy_page.go
> +	"github.com/planetdecred/godcr/ui/page"
Cleanup imports

2021-07-09 05:16 UTC, C-ollins commented on ui/window.go
> +	"github.com/planetdecred/godcr/ui/load"
Cleanup imports

2021-07-13 06:25 UTC, dreacot approved these changes

2021-07-13 08:54 UTC, C-ollins approved these changes

2021-07-13 08:55 UTC, merged