Cleanup proposals page
planetdecred/godcr pull request #513
Opened 2021-07-02 23:21 UTC by C-ollins

- Use clickable list to layout tabs and proposals list.
- Remove redundant tabs structs.
- Load proposals directly when dcrlibwallet.
- Register for politeia sync notifications and reload proposals when synced.
- Add list divider to clickable list and apply to proposals list.
- Pass proposal data to proposal details page.
- Remove global proposal variables.

2021-07-05 11:08 UTC, dreacot approved these changes, later dismissed

2021-07-08 00:05 UTC, oshorefueled requested changes

2021-07-08 00:05 UTC, oshorefueled commented on ui/proposals_page.go
> +	str := "No " + strings.ToLower(proposalCategoryTitles[selectedCategory]) + " proposals"
```suggestion
	str := fmt.Sprintf("No %s proposals", strings.ToLower(proposalCategoryTitles[selectedCategory]))
```

2021-07-08 09:10 UTC, oshorefueled approved these changes

2021-07-08 15:28 UTC, dreacot approved these changes

2021-07-08 15:29 UTC, merged