Notify popup
planetdecred/godcr pull request #518
Opened 2021-07-13 06:04 UTC by Sirmorrison

Fix #498 
This PR adds desktop notification when a new transaction or proposal is received.

2021-07-13 06:16 UTC, C-ollins requested changes

2021-07-13 06:16 UTC, C-ollins commented on wallet/commands.go
> +func (wal *Wallet) ClearProposals() {
This function isn’t needed, it’s accessible directly from the multi wallet variable.

2021-07-13 06:16 UTC, C-ollins commented on ui/listeners.go
> +		case t.Direction == dcrlibwallet.TxDirectionSent:
Remove options  for sent and transferred  transactions and add options for stake transactions.

2021-08-02 16:16 UTC, dreacot commented on ui/listeners.go
> +		//get distination account
```suggestion
		//get destination account
```

2021-08-16 08:06 UTC, C-ollins approved these changes

2021-08-16 12:06 UTC, dreacot approved these changes

2021-08-16 12:08 UTC, merged