Show status for pending transactions
planetdecred/godcr pull request #526
Opened 2021-07-14 22:38 UTC by devchoplife

Fixes #523 
This PR fixes status of pending transactions now showing up on the transaction details page as shown below:
![125679743-f604425c-1814-460b-944d-ae735890a5ef](https://user-images.githubusercontent.com/66803475/125701825-86753ad6-df20-4079-bbf2-0d3d61352c94.png)

2021-07-16 08:27 UTC, C-ollins submitted a review, later dismissed

2021-07-19 06:56 UTC, Sirmorrison requested changes
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/126115910-9c97eec6-a3ba-4651-99b7-7e8af8382bda.png">

align the pending and confirm icon with the text. See the mockup below

<img width="480" alt="image" src="https://user-images.githubusercontent.com/27733432/126116279-6693f938-cd7e-4443-916b-b8d888a71e93.png">

2021-07-19 20:37 UTC, devchoplife commented
The transaction status icon has been aligned with the transaction status as shown below:
![Screenshot from 2021-07-19 21-31-47](https://user-images.githubusercontent.com/66803475/126223923-171a6024-1ad7-4955-a8cc-72fef45fe248.png)

2021-07-20 19:16 UTC, Sirmorrison submitted a review, later dismissed

2021-07-21 13:44 UTC, oshorefueled requested changes

2021-07-21 13:44 UTC, oshorefueled commented on ui/page/transaction_details_page.go
>  									Right: values.MarginPadding5,
The right margin should be 4dp as well

<img width="405" alt="Screenshot 2021-07-21 at 14 43 37" src="https://user-images.githubusercontent.com/15804688/126498827-a941c997-2c16-423f-ac18-94c25340f0f8.png">

2021-07-22 08:07 UTC, oshorefueled approved these changes

2021-07-22 08:09 UTC, C-ollins approved these changes

2021-07-22 08:11 UTC, merged