Move wallet setting page to page package
planetdecred/godcr pull request #528
Opened 2021-07-19 03:29 UTC by JustinBeBoy

Resolve #522 
Move wallet setting page to page package
Re-enable wallet setting

2021-07-19 05:02 UTC, C-ollins requested changes

2021-07-19 05:02 UTC, beansgum commented on ui/page/wallet_settings_page.go
>  			walletName: pg.wallet.Name,
https://github.com/planetdecred/godcr/blob/master/ui/page/page.go#L41

Pass the load variable to SubPage to avoid nil pointer crash.

2021-07-19 05:02 UTC, C-ollins commented on ui/page/wallet_settings_page.go
> +						if !pg.WL.Info.Wallets[*pg.SelectedWallet].IsWatchingOnly {
```suggestion
						if !pg.wallet.IsWatchingOnlyWallet() {
```

2021-07-20 16:32 UTC, C-ollins approved these changes

2021-07-20 16:34 UTC, oshorefueled approved these changes

2021-07-20 16:34 UTC, merged