cleanup markdown tables
planetdecred/godcr pull request #529
Opened 2021-07-20 05:09 UTC by codemaestro64

This cleans up the loop of markdown tables by using equal cell widths. It also uses alternating row colors.
It fixes an issue with lists where formatted list content is displayed below It's bullet.

2021-07-20 07:31 UTC, C-ollins requested changes
- Line break does not work. Two spaces followed by a new line is supposed to break to the next line.

```markdown
First line  
Second line   
third line
```
<img src="https://user-images.githubusercontent.com/19960200/126275606-bafb5953-5249-4368-82fd-50bb08d0dbae.png" width="400">

- Strikethrough doesn't work either.
```markdown
~~The world is flat.~~
```
Expected:
~~The world is flat.~~

<img src="https://user-images.githubusercontent.com/19960200/126275913-25e4e6c1-ebb2-4093-bdbd-3ec3bf86189d.png" width="400">

- Ruler does not work.
```markdown
before ruler
---
after ruler
```
Expected:  

before ruler
---
after ruler

<img src="https://user-images.githubusercontent.com/19960200/126276654-4384a29c-d105-4d16-a0c1-f6bb6fabb11b.png" width="400">

- The app crashes when trying to render this table. https://pastebin.com/YvymiZNb
```md
| Syntax | Description |
| ----------- | ----------- |
| Header | Title |
| Paragraph | Text |
```

- Emphasis does not work
```
Emphasis, aka italics, with *asterisks* or _underscores_.
```

Expected:
Emphasis, aka italics, with *asterisks* or _underscores_.

<img src="https://user-images.githubusercontent.com/19960200/126279638-d5e9e169-e116-4039-b9b7-7da751a0ece8.png" width="400">

- Trying to use bold causes all the text to be bold and double underscores breaks to the next line.

```md
Emphasis, aka italics, with *asterisks* or _underscores_.
Strong emphasis, aka bold, with **asterisks** or __underscores__.
```

Expected:
Emphasis, aka italics, with *asterisks* or _underscores_.
Strong emphasis, aka bold, with **asterisks** or __underscores__.

<img src="https://user-images.githubusercontent.com/19960200/126280035-b8262f38-ea49-4d9b-87f7-bc9ccbfd0cea.png" width="400">

2021-08-16 06:49 UTC, C-ollins requested changes, later dismissed
The bugs listed in the first 3 bullet points of the inital review are not fixed.

2021-09-14 23:11 UTC, Clariceco commented
@C-ollins Now that Codemaestro is no longer working on this what is needed? Who should be dealing with it?

2021-09-14 23:13 UTC, C-ollins commented
This pr is waiting for review.

2021-09-16 08:18 UTC, dreacot approved these changes

2021-09-16 11:49 UTC, Sirmorrison commented
I am not mistaking, this text here are supposed to be rendered as links right and not what is in the screenshot.
![image](https://user-images.githubusercontent.com/27733432/133607042-11e7743d-6698-4356-a716-6b2017a0ea8e.png)

2021-09-16 12:03 UTC, C-ollins commented
No those are codeblocks, they’re meant to be rendered as code though we’re not doing syntax highlighting.

2021-09-16 14:04 UTC, Sirmorrison approved these changes

2021-09-16 14:05 UTC, merged