Move stake shuffle page to the page package
planetdecred/godcr pull request #534
Opened 2021-07-21 15:08 UTC by song50119

Resolves #519

2021-07-26 02:42 UTC, C-ollins requested changes

2021-07-26 02:42 UTC, C-ollins commented on log.go
> +	pageLog   = backendLog.Logger("PAGE")
Rebase with master, this change has already been made https://github.com/planetdecred/godcr/blob/master/log.go#L58

2021-07-26 02:42 UTC, C-ollins commented on ui/page/privacy_page.go
> +const PagePrivacyID = "Privacy"
```suggestion
const PrivacyPageID = "Privacy"
```

2021-07-26 02:42 UTC, C-ollins commented on ui/page/privacy_page.go
>  	default:
Remove this block and the `pg.acctMixerStatus` variable, it's no longer in use.

2021-07-28 16:00 UTC, oshorefueled approved these changes

2021-07-28 20:26 UTC, C-ollins approved these changes

2021-07-28 20:29 UTC, merged