fix mixer toggle button bug
planetdecred/godcr pull request #550
Opened 2021-08-06 16:23 UTC by Sirmorrison

Close #549

2021-08-12 11:10 UTC, oshorefueled requested changes

2021-08-12 11:10 UTC, oshorefueled commented on ui/page/privacy_page.go
> +	pg.toggleMixer.SetChecked(pg.wallet.IsAccountMixerActive())
does this need to be wrapped in a method?

2021-08-12 11:10 UTC, oshorefueled commented on ui/page/privacy_page.go
> +	pg.updateMixerOptions()
This should be in the OnResume method

2021-08-12 11:10 UTC, oshorefueled commented on ui/page/privacy_page.go
> +	pg.allowUnspendUnmixedAcct.Disabled()
This would probably be in the OnResume method

2021-08-16 07:03 UTC, C-ollins approved these changes

2021-08-16 11:16 UTC, oshorefueled approved these changes

2021-08-16 11:16 UTC, merged