Fix top nav highlight bug when send or receive button is selected
planetdecred/godcr pull request #562
Opened 2021-08-18 11:42 UTC by Sirmorrison

Resolves #555 
The first issue with the address card has been resolved.
This PR resolves bug with Highlighting selected top Nav page button.

* Old UI
![image](https://user-images.githubusercontent.com/27733432/129891917-2d5537e6-6842-4045-8535-6459c4808bd2.png)

*New UI
![image](https://user-images.githubusercontent.com/27733432/129892102-23210a06-79f9-4a73-979b-2381b17eb441.png)

2021-08-18 15:09 UTC, C-ollins requested changes
The highlight ripple animation doesn't show when the buttons are pressed, unlike other clickables.

2021-08-18 20:53 UTC, Sirmorrison commented
> The highlight ripple animation doesn't show when the buttons are pressed, unlike other clickables.

After troubleshooting this request, it was observed that the reason for this was that the card widget used to highlight the currently selected tab was overlaying the button effect.
We will create a task for the button effect and fix this from another PR after #563 is merged.

2021-08-18 20:57 UTC, C-ollins approved these changes

2021-08-19 07:48 UTC, oshorefueled approved these changes

2021-08-19 07:49 UTC, merged