Add LinearLayout
planetdecred/godcr pull request #563
Opened 2021-08-18 13:23 UTC by C-ollins

LinearLayout serves as a wrapper for several gio layout structs and it reduces the amount of code required when applying basic attributes like padding, margin, border, etc to a layout. The number of lines of code used for the most basic layouts can sometimes look very complex due to the multiple nested functions.

This layout code:
```go
return layout.Inset{Top: values.MarginPadding10}.Layout(gtx, func(gtx C) D {
	return layout.Stack{}.Layout(gtx,
		layout.Expanded(func(gtx C) D {
			// // draw background and and clip the background to border radius
			tr := float32(gtx.Px(unit.Dp(Border.Radius.TopRight)))
			tl := float32(gtx.Px(unit.Dp(Border.Radius.TopLeft)))
			br := float32(gtx.Px(unit.Dp(Border.Radius.BottomRight)))
			bl := float32(gtx.Px(unit.Dp(Border.Radius.BottomLeft)))
			clip.RRect{
				Rect: f32.Rectangle{Max: f32.Point{
					X: float32(gtx.Constraints.Min.X),
					Y: float32(gtx.Constraints.Min.Y),
				}},
				NW: tl, NE: tr, SE: br, SW: bl,
			}.Add(gtx.Ops)
			return fill(gtx, bgColor)
		}),
		layout.Stacked(func(gtx C) D {
			return Border{Color: borderColor, Width: values.MarginPadding2}.Layout(gtx, func(gtx C) D {
				return layout.Inset{Top: values.MarginPadding10}.Layout(gtx, func(gtx C) D {
					return layout.E.Layout(gtx, func(gtx C) D {
						return layout.Flex{Axis: layout.Vertical}.Layout(gtx, children...)
					})
				})
			})
		}),
	)
})
```
Can be replaced by this using the LinearLayout:
```
decredmaterial.LinearLayout{
	Width:       decredmaterial.MATCH_PARENT,
	Height:      decredmaterial.WRAP_CONTENT,
	Orientation: layout.Vertical,
	Background:  pg.Theme.Color.Orange,
	Margin:      layout.Inset{Top: values.MarginPadding16},
	Padding:     layout.UniformInset(values.MarginPadding16),
	Border:      decredmaterial.Border{Width: values.MarginPadding1, Color: pg.Theme.Color.Danger},
	Direction:   layout.Center,
}
```
I created an example of LinearLayout here and this is the result:
<img src="https://user-images.githubusercontent.com/19960200/129905606-bf0bfce7-7b56-4638-8a26-5ec584b141ca.png" width="600">

2021-08-18 20:43 UTC, Sirmorrison commented
<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/129969366-00b2c7fe-4cee-4d9a-abd3-61c03d45f95a.png">

clicking on the receive page, this is the UI that shows up.
I believe you where testing out what you implemented. 
This can be done on the testapp package.

2021-08-18 20:44 UTC, Sirmorrison requested changes

2021-08-18 20:44 UTC, Sirmorrison commented on ui/page/more_page.go
> +			}.Layout(gtx)
move test layout codes to testApp package.

2021-08-19 07:35 UTC, Sirmorrison requested changes
You did not add the sample layout code to the `test` package for code reference.

2021-08-19 07:35 UTC, Sirmorrison commented on ui/decredmaterial/linearlayout.go
> +				// // draw background and and clip the background to border radius
```suggestion
				// draw background and clip the background to border radius
```

2021-08-20 11:01 UTC, Sirmorrison submitted a review, later dismissed

2021-08-20 11:31 UTC, dreacot submitted a review, later dismissed

2021-08-20 16:19 UTC, dreacot approved these changes

2021-08-21 09:05 UTC, Sirmorrison approved these changes

2021-08-21 09:05 UTC, merged