Resolve Log Race
planetdecred/godcr pull request #574
Opened 2021-08-20 14:02 UTC by devchoplife

Ths PR resolves #455
This PR fixes the Log race issue and also resolves the disappeareance of logs on log page in #571

2021-08-23 11:02 UTC, Sirmorrison requested changes
This is the display if i open the log page.
![image](https://user-images.githubusercontent.com/27733432/130436631-683e3500-4eb0-4cff-9abc-a023bc1498d9.png)

no logs are available as the `/home/devchoplife/.godcr/logs/godcr.log` does not exist in my machine.

![image](https://user-images.githubusercontent.com/27733432/130436740-f50a63fd-a3f0-4654-9337-d73afe33ddc3.png)

The log path should not the be hard coded.

2021-08-23 11:02 UTC, Sirmorrison commented on log.go
> +		//internalLog <- string(p)
if this is no longer needed, kindly remove the go routine.

2021-08-23 11:02 UTC, Sirmorrison commented on ui/page/log_page.go
> +	logPath := "/home/devchoplife/.godcr/logs/godcr.log"
i am not sure i will be able to test with this path.

2021-08-23 11:11 UTC, devchoplife commented on log.go
> +		//internalLog <- string(p)
I added a //TODO there .
A function will be added later to get the log directory

2021-08-23 11:14 UTC, devchoplife commented on ui/page/log_page.go
> +	logPath := "/home/devchoplife/.godcr/logs/godcr.log"
I added a //TODO there .
A function will be added later to get the log directory

2021-08-23 13:59 UTC, Sirmorrison commented on ui/page/log_page.go
> +	logPath := "/home/devchoplife/.godcr/logs/godcr.log"
When is the function going to be added and by who? With out this, this PR is not ready for review as it cannot be tested for functionality. Marking it as work in progress till it is ready.

2021-09-14 23:07 UTC, Clariceco commented
@devchoplife what is the status of this? When will this be completed so that we can merge it?

2021-09-15 05:34 UTC, devchoplife commented
> @devchoplife what is the status of this? When will this be completed so that we can merge it?

Waiting on https://github.com/planetdecred/dcrlibwallet/pull/206. It includes a function that gets log file path.

2021-09-17 05:57 UTC, devchoplife commented
Works fine 
@C-ollins

2021-09-17 10:11 UTC, Sirmorrison approved these changes

2021-09-17 10:15 UTC, C-ollins approved these changes

2021-09-17 10:18 UTC, merged