Fix entire license row not clickable on about page
planetdecred/godcr pull request #578
Opened 2021-08-24 21:54 UTC by devchoplife

This PR fixes #575

2021-08-25 08:28 UTC, Sirmorrison requested changes

2021-08-25 08:28 UTC, Sirmorrison commented on ui/page/about_page.go
> +			}.Layout(gtx, func(gtx C) D {
This can be added into a method and called for every instance where it is used/needed.

2021-08-26 07:04 UTC, Sirmorrison requested changes

2021-08-26 07:04 UTC, Sirmorrison commented on ui/page/about_page.go
> +}
```suggestion
var inset = layout.Inset{
	Top:    values.MarginPadding20,
	Bottom: values.MarginPadding20,
	Left:   values.MarginPadding16,
	Right:  values.MarginPadding16,
}

func containerPadding() components.Container {
	return components.Container{
		Padding: inset,
	}
}

func padding() layout.Inset {
	return inset
}
```

2021-08-27 12:39 UTC, Sirmorrison submitted a review, later dismissed

2021-08-27 14:11 UTC, oshorefueled requested changes

2021-08-27 14:11 UTC, oshorefueled commented on ui/page/about_page.go
> +}
Do you think we this? The Container type is like a syntactic sugar to differentiate the use of an inset for margin or padding. When using an Inset as a padding, use Container type and when using it as a margin, use the Inset type as it is. In this case, they do the same thing.

2021-08-27 14:11 UTC, oshorefueled commented on ui/page/about_page.go
> +			})
Rather than create a method for container, you could use Container from the components package like so

```suggestion
			return components.Container{Padding: in}.Layout(gtx, func(gtx C) D {
				return components.EndToEndRow(gtx, pg.version.Layout, pg.versionValue.Layout)
			})
```

Where the variable `in` is a variable to the inset defined within the method `layoutRows()` as in
```go 
       in := layout.Inset{
		Top:    values.MarginPadding20,
		Bottom: values.MarginPadding20,
		Left:   values.MarginPadding16,
		Right:  values.MarginPadding16,
	}
```

2021-08-27 14:11 UTC, oshorefueled commented on ui/page/about_page.go
> +						return padding().Layout(gtx, pg.license.Layout)
You could do the same thing here

2021-08-30 09:15 UTC, Sirmorrison submitted a review, later dismissed

2021-08-30 09:29 UTC, oshorefueled approved these changes

2021-08-30 09:34 UTC, oshorefueled requested changes

2021-08-30 09:34 UTC, oshorefueled commented on ui/page/about_page.go
> +
make this a local variable in the layoutRows method

2021-08-30 10:37 UTC, oshorefueled approved these changes

2021-08-31 07:45 UTC, Sirmorrison approved these changes

2021-08-31 08:00 UTC, merged