Fix "clear all fields" popup position while full screen in Send page
planetdecred/godcr pull request #579
Opened 2021-08-25 04:07 UTC by JustinBeBoy

Resolve #576 
This PR allows:

Fix a bug where the "clear all fields" popup position is not correct while full screen.

2021-08-25 06:50 UTC, Sirmorrison requested changes

2021-08-25 06:50 UTC, Sirmorrison commented on ui/page/send/layout.go
> +										})
```suggestion
										layout.Inset{Top: values.MarginPadding25, Left: unit.Dp(-90)}.Layout(gtx, pg.clearAllBtn.Layout)
```

2021-08-25 06:50 UTC, Sirmorrison commented on ui/page/send/layout.go
> +										layout.Inset{Top: values.MarginPadding25, Left: unit.Dp(-90)}.Layout(gtx, func(gtx C) D {
move `unit.Dp(-90)` to dimensions.go file.
it should look something like this `values.MarginPaddingMinus90`

2021-08-25 06:50 UTC, Sirmorrison commented on ui/page/send/layout.go
> -							return border.Layout(gtx, pg.clearAllBtn.Layout)
The border acts as a temporary shadow pending when the shadow widget/functionality is implemented.
With out this, this is what you have.
![image](https://user-images.githubusercontent.com/27733432/130740495-0c389d47-b57d-4803-94f8-332114edd22b.png)

2021-08-26 06:24 UTC, Sirmorrison approved these changes

2021-08-26 13:55 UTC, beansgum approved these changes

2021-08-26 13:55 UTC, merged