Format transactions row and details
planetdecred/godcr pull request #582
Opened 2021-08-26 07:32 UTC by C-ollins

Closes #561 

- Fix minus sign not showing on some sent transactions
<img src="https://user-images.githubusercontent.com/19960200/130920602-605a1b36-ca84-4beb-9ea4-cdf5e0d58e40.png" width="600">

- Fix transferred transactions showing as sent
<img src="https://user-images.githubusercontent.com/19960200/130920629-762df9e6-d0b2-4cee-8de7-b5151a5c6fff.png" width="600">

- Add mixed transaction filter to dropdown selector
<img src="https://user-images.githubusercontent.com/19960200/130920637-8bbe0e70-6a68-4da0-9f21-3c4cccc0e784.png" width="600">

- Format mixed transaction details
<img src="https://user-images.githubusercontent.com/19960200/130920657-c2fd47fa-87b2-481e-a4b1-39548b6a5e19.png" width="600">

- Format stake transaction row
<img src="https://user-images.githubusercontent.com/19960200/130920660-c91057f9-b171-4fcf-a064-fcc59fff6569.png" width="600">

- Format vote transaction details
<img src="https://user-images.githubusercontent.com/19960200/130959404-254ea00e-4793-496b-aec5-9a466419bb22.png" width="600">

2021-08-27 10:03 UTC, Sirmorrison requested changes
![image](https://user-images.githubusercontent.com/27733432/131110233-63b4ed8e-7450-40de-9c6a-c0ff614918aa.png)

The ticket type/direction should not be on the tx list page the Icon is enough. It should be on the Tx details page.

2021-08-27 10:03 UTC, Sirmorrison commented on ui/load/load.go
> +	List, ListGridIcon, DecredSymbolIcon, DecredSymbol2 *widget.Image
Rename `DecredSymbol2` to `DecredSymbolIconTwo`

2021-08-27 10:03 UTC, Sirmorrison commented on ui/load/load.go
> +	ArrowForwardIcon, Next, TransactionFingerPrintIcon, SettingsIcon, SecurityIcon, HelpIcon,
`Next` to `NextIcon`

2021-08-27 10:03 UTC, Sirmorrison commented on ui/load/load.go
> +	ReceiveIcon, Transferred, TransactionIcon, TransactionIconInactive, SendIcon, MoreIcon, MoreIconInactive,
`Transferred` to `TransferredIcon`

2021-08-27 10:12 UTC, oshorefueled requested changes

2021-08-27 10:12 UTC, oshorefueled commented on ui/page/components/components.go
> +			title = "Sent"
Can the texts here be added to the strings file so language translation can be supported?

2021-08-27 10:28 UTC, oshorefueled requested changes

2021-08-27 10:28 UTC, oshorefueled commented on ui/page/transaction_details_page.go
> +	return pg.theme.Separator().Layout(gtx)
Is this separator wrapper needed?

2021-08-27 14:18 UTC, beansgum commented on ui/load/load.go
> +	ArrowForwardIcon, Next, TransactionFingerPrintIcon, SettingsIcon, SecurityIcon, HelpIcon,
It's redundant to have `Icon` in the variable since the struct name already contains that.

2021-08-27 14:40 UTC, oshorefueled approved these changes

2021-08-30 08:55 UTC, Sirmorrison approved these changes

2021-08-30 08:58 UTC, merged