Fix issues with click effect not showing up on the side and top Nav when button is clicked
planetdecred/godcr pull request #586
Opened 2021-08-31 11:16 UTC by Sirmorrison

2021-09-06 13:14 UTC, dreacot approved these changes, later dismissed

2021-09-07 05:41 UTC, C-ollins requested changes

2021-09-07 05:41 UTC, C-ollins commented on ui/page/main_page.go
> +	direction layout.Direction
Create a NavDrawer struct in the components package to house the nav handlers and these properties.

2021-09-07 05:41 UTC, C-ollins commented on ui/page/main_page.go
> +func (mp *MainPage) layoutCard(gtx layout.Context, background color.NRGBA, Clickable *widget.Clickable, body layout.Widget) layout.Dimensions {
Tgus can be renamed to `layoutNavRow`.

2021-09-07 05:41 UTC, C-ollins commented on ui/page/main_page.go
>  func (mp *MainPage) LayoutNavDrawer(gtx layout.Context) layout.Dimensions {
The content of this function should also be part of the NavDrawer component.

2021-09-09 06:23 UTC, C-ollins requested changes

2021-09-09 06:23 UTC, C-ollins commented on ui/page/main_page.go
> +func (mp *MainPage) defaultNavDims() {
This function should be in components/nav_drawer.go

2021-09-09 06:23 UTC, C-ollins commented on ui/page/main_page.go
> +		mp.drawerNav.Axis = layout.Vertical
Add a toggle function in components/nav_drawer.go to switch between maximized and minimized attributes.

2021-09-09 10:54 UTC, C-ollins approved these changes

2021-09-09 11:58 UTC, dreacot approved these changes

2021-09-09 15:30 UTC, merged