Split combined backup flow to multiple pages and cleanup interface design
planetdecred/godcr pull request #587
Opened 2021-09-01 18:07 UTC by C-ollins

This pr adds a new package `seedbackup`  and splits the seed backup page into backup instructions page, save seed page, verify seed page, and backup success page. The user interface is also cleaned up to apply proper styling and dimensions.

<img src="https://user-images.githubusercontent.com/19960200/131721091-74f1a362-de97-425f-8a32-7be3121d3261.png" width="600">
<img src="https://user-images.githubusercontent.com/19960200/131721406-79ed6270-f457-47c4-b2b5-cc4286866415.gif" width="600">
<img src="https://user-images.githubusercontent.com/19960200/131721119-2b76f226-0d77-438e-904e-c287fab2fda9.png" width="600">
<img src="https://user-images.githubusercontent.com/19960200/131721124-6f2d5254-830f-44d1-a2a1-118d2a4b54ea.png" width="600">

2021-09-01 20:26 UTC, oshorefueled commented on ui/page/seedbackup/backup_success.go
> +// - Layout
was this added here intentionally?

2021-09-01 20:26 UTC, oshorefueled commented on ui/page/seedbackup/save_seed.go
> +	itemWidth := gtx.Constraints.Max.X / 3
could adding a comment here make the value 3 look less like a magic number?

2021-09-01 20:31 UTC, oshorefueled commented
There should probably be a little bit of space between the fixed bottom pane and the side navigation similar to how it's done on the send page.

###### Current Seed backup implementation 
<img width="600" alt="Screenshot 2021-09-01 at 21 28 10" src="https://user-images.githubusercontent.com/15804688/131740362-972af548-724d-4050-bbcb-16113cd31f1a.png">

###### Send page mockup
![Screenshot 2021-09-01 at 20 54 48](https://user-images.githubusercontent.com/15804688/131740727-171403c4-2442-430d-b590-eabfec6e73b4.png)

2021-09-02 16:25 UTC, C-ollins commented on ui/page/seedbackup/backup_success.go
> +// - Layout
Yes

2021-09-03 07:23 UTC, oshorefueled submitted a review, later dismissed

2021-09-03 09:39 UTC, Sirmorrison requested changes
Since this is a clean up PR,

When the page is expanded, the verify button is overly large in width.
Following recent review by Raedah, the button should have a maximum with which is preferably the width of the button on the default screen.

![image](https://user-images.githubusercontent.com/27733432/131981650-bb5e0f9e-f43b-4ce1-85cc-c1298f4859c4.png)

this button size is perfect
![image](https://user-images.githubusercontent.com/27733432/131982125-06cc5ed1-3537-4746-9956-b76ad7a1f494.png)

- the button color when it is grayed out does not correspond to the other buttons on the app.
the color should be `t.Color.InactiveGray = rgb(0xc4cbd2)`

- On the Write down seed phrase page, the confirm button is also overly large on full screen. it should have a maximum width and center aligned with the text on full screen.
![image](https://user-images.githubusercontent.com/27733432/131983448-8a8d3ba0-143f-40aa-8acc-7cc81adcfc66.png)

- On the seed phrase page, the action button width is overly expanded also and the color is not uniform to the application (see recommended color above.
- Then i noticed a pattern with the seed phrase arrangement. it does not seem to be random as it has a pattern. The first 10 are on thesame line, the next 10 on the next line and so on...
![image](https://user-images.githubusercontent.com/27733432/131984343-f8eaf5be-8595-4cdf-a726-aff72c4d40eb.png)

![image](https://user-images.githubusercontent.com/27733432/131984422-0b7ee1b1-8319-4817-9e18-040252b13134.png)

![image](https://user-images.githubusercontent.com/27733432/131984705-be2eb408-8f1d-44e9-8d4d-da980c1262fc.png)

- Clicking on the back button on the back button on the `Verify seed phrase page 2/2` page takes me back to the `wallet page` instead of `page 1/2`.

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/components/sub_page.go
> +					if sp.SubTitle == "" {
```suggestion
					if components.StringNotEmpty(sp.SubTitle) {
```

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/seedbackup/backup_instructions.go
> +					if infoText == "" {
```suggestion
					if components.StringNotEmpty(infoText) {
```

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/seedbackup/backup_instructions.go
> +
Remove white space

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/seedbackup/backup_success.go
> +}
```suggestion
func (pg *BackupSuccessPage) OnResume() {}
```

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/seedbackup/verify_seed.go
> +
Remove whitespace

2021-09-03 09:39 UTC, Sirmorrison commented on ui/page/seedbackup/verify_seed.go
> +
Remove whitespace

2021-09-07 09:18 UTC, Sirmorrison requested changes
- Clicking on the back button on the back button on the Verify seed phrase page 2/2 page takes me back to the wallet page instead of page 1/2. (see screen recording below.)
![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/27733432/132319212-1799581b-2ba7-4a19-93a6-611cbc26a503.gif)

- furthermore, this issues is only noticed on windows machine for me.. On Mac it seems to work fine.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/27733432/132319434-130414df-a31f-4b26-a0e0-97c151df6ca9.png">

2021-09-07 09:18 UTC, Sirmorrison commented on ui/page/components/sub_page.go
> +	zeroInset := layout.UniformInset(values.MarginPadding4)
Please rename as the value is not longer `values.MarginPadding0`

2021-09-07 10:56 UTC, Sirmorrison approved these changes

2021-09-07 13:31 UTC, dreacot approved these changes

2021-09-07 13:32 UTC, merged