Change wallet password
planetdecred/godcr pull request #61
Opened 2020-03-28 20:56 UTC by Sirmorrison

### Resolves

Issue #58

### What's new

This PR adds the ability change wallet passphrase.

### Relevant screenshots or logs

_If applicable, add screenshots or log entries to help explain your problem._

### Additional context

_Add any other context about the problem here._

2020-04-11 14:52 UTC, metaclips requested changes
Use single line editor when changing wallet name so that this wont occur.
<img width="802" alt="Screenshot 2020-04-11 at 15 47 15" src="https://user-images.githubusercontent.com/31141573/79046958-b9af9d80-7c0b-11ea-89e4-7eb7eadc2543.png">

When changing wallet name and error occurs, you should show error thrown.

2020-04-11 18:17 UTC, Sirmorrison commented
> Use single line editor when changing wallet name so that this wont occur.
> <img alt="Screenshot 2020-04-11 at 15 47 15" width="802" src="https://user-images.githubusercontent.com/31141573/79046958-b9af9d80-7c0b-11ea-89e4-7eb7eadc2543.png">
> 
> When changing wallet name and error occurs, you should show error thrown.

Out of scope of work.

2020-04-11 18:44 UTC, metaclips commented
> > Use single line editor when changing wallet name so that this wont occur.
> > <img alt="Screenshot 2020-04-11 at 15 47 15" width="802" src="https://user-images.githubusercontent.com/31141573/79046958-b9af9d80-7c0b-11ea-89e4-7eb7eadc2543.png">
> > When changing wallet name and error occurs, you should show error thrown.
> 
> Out of scope of work.

True. An issue should be created so we dont miss it later.

2020-04-12 16:08 UTC, metaclips reviewed
UI functionality looks good by the way.

2020-04-12 16:08 UTC, metaclips commented on ui/handle_input.go
> +		}
Do remove all password strength text as it's no longer needed

2020-04-12 16:08 UTC, metaclips commented on ui/dialogs.go
> +func (win *Window) passwordStrenght() {
passwordStrength

2020-04-12 16:08 UTC, metaclips commented on ui/handle_input.go
> +	if win.inputs.changePasswordDiag.Clicked(win.gtx) {
```suggestion
	for win.inputs.changePasswordDiag.Clicked(win.gtx) {
```
So as to catch subsequent clicks

2020-04-12 16:08 UTC, metaclips commented on ui/handle_input.go
> +	if win.inputs.savePassword.Clicked(win.gtx) {
Use a for loop instead

2020-04-12 16:08 UTC, metaclips commented on ui/handle_input.go
> +			if err.Error() == "invalid_passphrase" {
```suggestion
			if err.Error() == dcrlibwallet.ErrInvalidPassphrase {
```

2020-04-13 12:12 UTC, metaclips submitted a review, later dismissed

2020-04-13 12:41 UTC, oshorefueled requested changes

2020-04-13 12:41 UTC, oshorefueled commented on ui/decredmaterial/progressbar.go
>  }
any reason for making modifications to the progressbar code?

2020-04-13 15:38 UTC, oshorefueled commented on ui/widgets.go
> +	passwordStgth                                                                 *decredmaterial.ProgressBar
kindly rename this

2020-04-13 15:48 UTC, oshorefueled commented on ui/handle_input.go
> +		strength := (dcrlibwallet.ShannonEntropy(win.inputs.spendingPassword.Text()) / 4.0)
parentheses around "dcrlibwallet.ShannonEntropy(win.inputs.spendingPassword.Text()) / 4.0" is redundant.

2020-04-14 10:02 UTC, oshorefueled submitted a review, later dismissed

2020-04-14 10:12 UTC, oluwandabira requested changes

2020-04-14 10:12 UTC, RogueElement commented on ui/decredmaterial/theme.go
> +		Average    color.RGBA
Should be a page color

2020-04-14 12:43 UTC, oshorefueled submitted a review, later dismissed

2020-04-16 19:15 UTC, oluwandabira requested changes

2020-04-16 19:15 UTC, RogueElement commented on ui/handle_input.go
> +		return
This is unsafe. `AfterFunc` calls the func on its own go routine

2020-04-18 09:30 UTC, oluwandabira requested changes

2020-04-18 09:30 UTC, RogueElement commented on ui/handle_input.go
> +func (win *Window) valOldAndNewPasswords() string {
I don't see why this is necessary. Password requirements are for dcrlibwallet to handle.

2020-04-20 20:47 UTC, oluwandabira requested changes

2020-04-20 20:47 UTC, RogueElement commented on ui/handle_input.go
> +		return ""
Let `dcrlibwallet` handle empty passwords

2020-04-25 19:19 UTC, oluwandabira approved these changes

2020-04-25 19:19 UTC, merged