tooltip alignment in proposals page
planetdecred/godcr pull request #613
Opened 2021-09-05 03:37 UTC by JustinBeBoy

2021-09-06 09:54 UTC, Sirmorrison requested changes
Also, the tooltip from the screenshot below should be center aligned as in the mockup below.

![image](https://user-images.githubusercontent.com/27733432/132198396-96de95e8-bf9d-4c17-92d1-081124a3f389.png)

![image](https://user-images.githubusercontent.com/27733432/132198589-7cce8f1b-26f7-411f-a3fb-0387d5be3472.png)

It should be like this.

![image](https://user-images.githubusercontent.com/27733432/132197817-1a4d1bd6-e6db-4a97-ba65-da3534abfcb8.png)

2021-09-06 09:54 UTC, Sirmorrison commented on ui/page/proposal/proposals_page.go
> +	inset := layout.Inset{Top: values.MarginPadding20, Left: unit.Dp(-195)}
Move this to the dimensions.go file.

```suggestion
	inset := layout.Inset{Top: values.MarginPadding20, Left: values.MarginPaddingMinus195}
```

2021-09-06 09:54 UTC, Sirmorrison commented on ui/page/proposal/proposals_page.go
> +		gtx.Constraints.Max.X = gtx.Px(unit.Dp(195))
move `unit.Dp(195)` to dimensions.go

2021-09-09 09:58 UTC, Sirmorrison approved these changes

2021-09-09 10:14 UTC, C-ollins approved these changes

2021-09-09 10:14 UTC, merged