Add menu item and link send page to utxo page
planetdecred/godcr pull request #614
Opened 2021-09-05 09:09 UTC by JustinBeBoy

Resolve #588 
This PR link send page to utxo page

![image](https://user-images.githubusercontent.com/19331824/132121623-d48544ba-3fd9-4301-b8ec-e0a447cb62cd.png)

2021-09-06 09:17 UTC, Sirmorrison requested changes

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/components/utils.go
> +}
This already exist on the `theme.go` file but not exported. 

This method is also repeating across multiple files (links below).
Kindly remove all instances of this method and make use of the method you implemented on the components >> utils.go file.

other instance of the `mustIcon` methods can be found here.
https://github.com/planetdecred/godcr/blob/5603d402151a1ecad15cec83dbc2d041dc50c1bd/ui/util.go#L35

https://github.com/planetdecred/godcr/blob/5603d402151a1ecad15cec83dbc2d041dc50c1bd/ui/load/utils.go#L10

https://github.com/planetdecred/godcr/blob/5603d402151a1ecad15cec83dbc2d041dc50c1bd/ui/page/utils.go#L34

https://github.com/planetdecred/godcr/blob/5603d402151a1ecad15cec83dbc2d041dc50c1bd/ui/decredmaterial/theme.go#L226

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/layout.go
> +	"gioui.org/widget/material"
Not needed... we already have `decredmaterial.Clickable()`

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/layout.go
> +							return material.Clickable(gtx, pg.moreItems[i].button, func(gtx C) D {
```suggestion
							return decredmaterial.Clickable(gtx, pg.moreItems[i].button, func(gtx C) D {
```

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/layout.go
> +								return layout.Inset{Top: m10, Bottom: m10, Left: m10, Right: m10}.Layout(gtx, func(gtx C) D {
```suggestion
								return layout.UniformInset(values.MarginPadding10).Layout(gtx, func(gtx C) D {
```

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/page.go
> +
remove white space

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/page.go
>  }
There are multiple instance of this already... Kindly remove and use on from the either the component/utils.go 

See comments above.

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/utxo_page.go
> +		//pg.log.Error(err)
Why was this commented out?

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/utxo_page.go
> +		//pg.log.Error(err)
This also.

2021-09-06 09:17 UTC, Sirmorrison commented on ui/page/send/utxo_page.go
>  							)
Why was all these changed?

2021-09-06 09:17 UTC, Sirmorrison commented on ui/values/localizable/en.go
> +"clearAllFields" = "Clear all fields"
Please revert this... Use the strings value locally.

2021-09-06 09:17 UTC, Sirmorrison commented on ui/values/strings.go
> +	StrClearFeilds                 = "clearAllFields"
Revert this also. Use the strings locally. 
The localized strings file is not to be edited.

2021-09-07 16:10 UTC, C-ollins requested changes

2021-09-07 16:10 UTC, C-ollins commented on ui/page/send/page.go
> +
Put this in initLayoutWidgets() function.

2021-09-07 16:10 UTC, C-ollins commented on ui/page/send/page.go
> +				pg.ChangeFragment(NewUTXOPage(pg.Load))
This can be in the action function of the moreItem.

2021-09-07 16:10 UTC, C-ollins commented on ui/page/send/layout.go
> +				pg.amount.clearAmount()
Use `resetFields()`

2021-09-08 13:53 UTC, Sirmorrison requested changes
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/27733432/132522362-01d7cbfe-78dc-41af-b883-ba3e0b3fd3fe.png">

app crash with the following error.

2021-09-08 13:53 UTC, Sirmorrison commented on ui/page/components/utils.go
> +)
Please revert this.

2021-09-08 13:53 UTC, Sirmorrison commented on ui/page/send/layout.go
> +	"gioui.org/unit"
Remove this.. Use the values defined in the Dimensions.go file.

2021-09-08 13:53 UTC, Sirmorrison commented on ui/page/send/layout.go
> +		Left: unit.Dp(-120),
```suggestion
		Top: values.MarginPadding30,
		Left: values.MarginPaddingMinus120,
```
Add them to the Dimensions.go file if they dont exist.

2021-09-09 09:51 UTC, C-ollins approved these changes

2021-09-09 12:19 UTC, dreacot approved these changes

2021-09-09 13:42 UTC, Sirmorrison approved these changes

2021-09-09 15:27 UTC, merged