Add backdrop for dropdown
planetdecred/godcr pull request #616
Opened 2021-09-05 14:36 UTC by JustinBeBoy

This PR resolve #581 with detail:
- Add backdrop for dropdown
- Implement pages which using dropdown

2021-09-05 15:48 UTC, Sirmorrison requested changes

2021-09-05 15:48 UTC, Sirmorrison commented on ui/page/tickets/list_page.go
> +					layout.Expanded(pg.walletDropDown.BackDrop),
This should be added to the `dropdown` widget as part of the layout method.

2021-09-05 15:48 UTC, Sirmorrison commented on ui/page/transactions_page.go
> +			layout.Expanded(pg.walletDropDown.BackDrop),
This should be part of the `dropdown` widget not the page the dropdown is used.

2021-09-05 21:03 UTC, Sirmorrison approved these changes, later dismissed

2021-09-06 13:24 UTC, dreacot commented
@JustinBeBoy This hasn't been implemented in the ticket activity page

2021-09-06 15:17 UTC, Sirmorrison commented
> @JustinBeBoy This hasn't been implemented in the ticket activity page

This is now resolved.

2021-09-06 22:34 UTC, dreacot approved these changes, later dismissed

2021-09-07 05:24 UTC, C-ollins requested changes

2021-09-07 05:24 UTC, C-ollins commented on ui/page/tickets/activity_page.go
> +							return pg.backdrop.Layout(gtx)
This implementation requires each page to have a backdrop, the backdrop should be handled by the dropdown instead.

2021-09-10 08:32 UTC, Sirmorrison requested changes
![image](https://user-images.githubusercontent.com/27733432/132824743-170c7239-1e66-4077-b698-05effbbfd9e2.png)

 on the ticket page this is what the dropdowns look like at the far right.

Same for ticket activity page.

![image](https://user-images.githubusercontent.com/27733432/132825026-ff2f9542-e71e-4df9-9b9f-9f17807b8f8f.png)

Same for transactions page.
![image](https://user-images.githubusercontent.com/27733432/132824925-82033014-153b-4ce7-bc83-3d07d7ac57ad.png)

2021-09-10 08:32 UTC, Sirmorrison commented on ui/page/transactions_page.go
> +				post := float32(gtx.Constraints.Max.X - 315)
rename all occurrence of `post` to `position` or `pos`

2021-09-10 08:52 UTC, JustinBeBoy commented
> ![image](https://user-images.githubusercontent.com/27733432/132824743-170c7239-1e66-4077-b698-05effbbfd9e2.png)
> 
> on the ticket page this is what the dropdowns look like at the far right.
> 
> Same for ticket activity page.
> 
> ![image](https://user-images.githubusercontent.com/27733432/132825026-ff2f9542-e71e-4df9-9b9f-9f17807b8f8f.png)
> 
> Same for transactions page.
> ![image](https://user-images.githubusercontent.com/27733432/132824925-82033014-153b-4ce7-bc83-3d07d7ac57ad.png)

I cant reproduce it in computer, can you tell me steps to reproduce it

2021-09-10 08:59 UTC, C-ollins commented
@Sirmorrison I can't also reproduce the ui bug.

2021-09-10 09:01 UTC, Sirmorrison commented
> @Sirmorrison I can't also reproduce the ui bug.

Let me try from my mac machine it was noticed on windows

this is what i get on my macbook

transaction page

<img width="794" alt="image" src="https://user-images.githubusercontent.com/27733432/132829630-73a5c9e0-f5b3-4cc5-966d-16b6c8d9386d.png">

ticket page

<img width="795" alt="image" src="https://user-images.githubusercontent.com/27733432/132829905-596d2d5c-4662-4bfd-9e8d-fe5820c0371a.png">

2021-09-10 10:14 UTC, Sirmorrison requested changes

2021-09-10 10:14 UTC, Sirmorrison commented on ui/page/tickets/activity_page.go
> +						return pg.ticketTypeDropDown.Layout(gtx, post)
So doing troubleshooting, this seems to be where the issue is coming from.

Changing the values as suggested below, give me the screenshots below.
![image](https://user-images.githubusercontent.com/27733432/132838330-2cd80f51-5392-4a09-995b-cd852760a527.png)

```suggestion
					layout.Expanded(func(gtx C) D {
						return pg.walletDropDown.Layout(gtx, 0)
					}),
					layout.Expanded(func(gtx C) D {
						post := float32(gtx.Constraints.Max.X - 450)
						return pg.orderDropDown.Layout(gtx, post)
					}),
					layout.Expanded(func(gtx C) D {
						post := float32(gtx.Constraints.Max.X - 300)
						return pg.ticketTypeDropDown.Layout(gtx, post)
```

I think the issue here has to do with the screen size of the machine. you will need to use `gtx.Px()` for positioning and scaling.

2021-09-13 07:43 UTC, Sirmorrison commented
<img width="801" alt="image" src="https://user-images.githubusercontent.com/27733432/133043683-6da7ffea-9a75-4d1d-86c6-4e9b68f5717f.png">

the space between the dropdown is too much... See the red section on the screenshot.

2021-09-14 09:03 UTC, Sirmorrison approved these changes
PR looks good.

2021-09-14 09:58 UTC, C-ollins approved these changes

2021-09-14 09:59 UTC, merged