Update currency and language setting on the Setting page
planetdecred/godcr pull request #626
Opened 2021-09-14 15:31 UTC by JustinBeBoy

This PR resolve #603 

- Remove cancel and confirm buttons on the modals setting language and currency on setting page
- Get the setting of language and currency when starting app

2021-09-14 18:52 UTC, Sirmorrison requested changes
This methods are no longer needed.

https://github.com/planetdecred/godcr/blob/9898ea5afb4e1050fdf36742b34684db59e799a9/ui/preference/list_preference.go#L77

https://github.com/planetdecred/godcr/blob/9898ea5afb4e1050fdf36742b34684db59e799a9/ui/preference/list_preference.go#L84

https://github.com/planetdecred/godcr/blob/9898ea5afb4e1050fdf36742b34684db59e799a9/ui/preference/list_preference.go#L187

2021-09-14 18:52 UTC, Sirmorrison commented on ui/page/main_page.go
> +}
Is there any specific reason this method is here? This should be in the settings page or components page.

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	isAutoUpdate bool
This is redundant. What exactly is it supposed to be used for?

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	if lp.positiveButtonStrKey != "" && !lp.isAutoUpdate {
The`positiveButtonStrKey` is no longer as we are no longer using the buttons. Kindly remove.
The entire `if` condition  can be removed.

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	if lp.negativeButtonStrKey != "" && !lp.isAutoUpdate {
The `negativeButtonStrKey` is no longer as we are no longer using the buttons. Kindly remove.
The entire `if` condition  can be removed.

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	autoUpdateButtonClicked func()
Remove every instance of `negativeButton` and `positiveButton` since we are no longer using the buttons, they are all redundant.

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +		if lp.isAutoUpdate {
This not needed kindly remove

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +			lp.autoUpdateButtonClicked()
This not needed kindly remove

2021-09-14 18:52 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	lp.isAutoUpdate = true
remove this as it is redundant.

2021-09-14 18:52 UTC, Sirmorrison commented on ui/page/settings_page.go
> +		AutoUpdate(func() {
This should be renamed to `UpdateValues` or  `UpdateSettings`

2021-09-15 00:00 UTC, dreacot requested changes

2021-09-15 00:00 UTC, dreacot commented on ui/page/main_page.go
> +	if langPre == "" {
```suggestion
	if components.StringNotEmpty(langPre) {
```

2021-09-15 00:00 UTC, dreacot commented on ui/page/main_page.go
> +	if currencyPre == "" {
```suggestion
	if components.StringNotEmpty(currencyPre) {
```

2021-09-15 04:25 UTC, JustinBeBoy commented on ui/page/main_page.go
> +}
this method is neccessary to get the saved setting and to apply for the app. it is not the app setting

2021-09-15 04:43 UTC, JustinBeBoy commented on ui/preference/list_preference.go
> +	isAutoUpdate bool
It use to add title for modal

2021-09-15 06:04 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +	isAutoUpdate bool
I was referring to the `isAutoUpdate`

2021-09-15 06:08 UTC, Sirmorrison requested changes
This PR failed github build...

Kindly run `go fmt ./...` it should resolve the issue.

2021-09-15 06:08 UTC, Sirmorrison commented on ui/preference/list_preference.go
> +
Remove whitespace

2021-09-15 07:39 UTC, Sirmorrison approved these changes

2021-09-15 07:43 UTC, dreacot approved these changes

2021-09-15 07:46 UTC, merged