[wip]
planetdecred/godcr pull request #644
Opened 2021-09-25 01:22 UTC by amass01

This diff fixes two issues with the USD balance in the top nav where:

 - [ ] Main page's USD balance is not showing once you switch the
   setting from none to USD.

 - [x] USD conversion setting doesn't persist.

---

Closes #641.

2021-10-04 11:33 UTC, Sirmorrison requested changes
Turning on the USD balance from the settings page, adds the additional editor on the send page as it should be. 
![image](https://user-images.githubusercontent.com/27733432/135844056-a5373363-edf9-452e-afab-360304dfb4f1.png)

However, when the USD balance is set to none from settings page, the send page is not updated correctly until the app is restarted.
![image](https://user-images.githubusercontent.com/27733432/135844136-8b58e6e7-cb4f-4051-9491-bc69b436e3f9.png)

The send page should revert to screenshot below, when the USD toggle is off.
![image](https://user-images.githubusercontent.com/27733432/135844446-8178efce-e640-4d53-8692-dd111c9abf82.png)

2021-10-04 15:08 UTC, amass01 commented
@Sirmorrison addressed.

2021-10-04 15:14 UTC, dreacot submitted a review, later dismissed
LGTM

2021-10-04 15:31 UTC, Sirmorrison commented on ui/page/send/layout.go
> +			ReadStringConfigValueForKey(dcrlibwallet.CurrencyConversionConfigKey)
There is some form of delay in updating this setting when the page is opened. 
I believe moving this to the `handle()` should improve the performance.

2021-10-05 07:13 UTC, Sirmorrison commented
<img width="796" alt="image" src="https://user-images.githubusercontent.com/27733432/135976064-ab5507fa-51cc-47f3-b4e4-f2f2395e71a2.png">
What the send page looks before the USD setting is set.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/27733432/135976494-ca35e76e-76c1-4ff7-b9cc-876b644070da.png">
After setting the USD values

When the setting is turned off, the tx fee details are not updated.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/27733432/135976673-55b917d8-64f0-4985-8b4b-2ba7e6854f18.png">

the confirmation modal as well is not updated correctly after the USD values are turned off.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/27733432/135976792-4b33c3bf-113e-4029-a77f-d0479c72ec86.png">

What it should look like when the USD value is not set.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/27733432/135976919-a93bc2d4-7a2e-4414-89a1-7b572b175eeb.png">

2021-10-05 12:06 UTC, amass01 commented
@Sirmorrison Addressed.

2021-10-05 13:22 UTC, Sirmorrison approved these changes

2021-10-05 15:49 UTC, dreacot approved these changes

2021-10-05 15:52 UTC, merged