User agent summary update
planetdecred/godcr pull request #645
Opened 2021-09-27 07:39 UTC by Sirmorrison

fix #604
- update user agent summary message
- change passphrase text to password

2021-09-27 14:19 UTC, C-ollins requested changes, later dismissed

2021-09-27 14:19 UTC, C-ollins commented on ui/page/settings_page.go
> +							} else {
```suggestion
							if err.Error() == dcrlibwallet.ErrInvalidPassphrase {
								error = "Invalid password"
							} else {
```

2021-09-27 14:19 UTC, C-ollins commented on ui/page/main_page.go
> +					if err.Error() == "invalid password" {
```suggestion
					if err.Error() == dcrlibwallet.ErrInvalidPassphrase {
```

2021-09-27 14:19 UTC, C-ollins commented on ui/page/settings_page.go
> +						pg.Toast.Notify("Startup password activated")
```suggestion
						pg.Toast.Notify("Startup password enabled")
```

2021-09-27 14:19 UTC, C-ollins commented on ui/page/settings_page.go
> +						pg.Toast.Notify("Startup password deactivated")
```suggestion
						pg.Toast.Notify("Startup password disabled")
```

2021-09-27 19:43 UTC, dreacot requested changes

2021-09-27 19:43 UTC, dreacot commented on ui/page/settings_page.go
> +									txt := pg.Theme.Body2(values.String("For HTTP request"))
```suggestion
									txt := pg.Theme.Body2("For HTTP request")
```

2021-09-27 19:44 UTC, dreacot commented
currently a default user agent isn't shown if there is no custom agent set

2021-09-28 05:51 UTC, Sirmorrison commented
> currently a default user agent isn't shown if there is no custom agent set

Yeah at the moment, there is no default user agent from the config settings.

2021-09-29 18:55 UTC, dreacot requested changes
This says enter your seed phrase

![Screenshot from 2021-09-29 19-38-12](https://user-images.githubusercontent.com/25265396/135331147-ec8165ff-da3a-4491-b7ef-8f632813f54a.png)

2021-10-04 15:22 UTC, dreacot submitted a review, later dismissed

2021-10-05 15:48 UTC, dreacot approved these changes

2021-10-06 18:58 UTC, merged