Implement scrollbar to list
planetdecred/godcr pull request #664
Opened 2021-10-08 15:14 UTC by JustinBeBoy

Resolve #609
- Upgrade gioui new version
- Implement scrollbar for list
- Update current component for gioui new version
- Custom Icon

![scroll1](https://user-images.githubusercontent.com/19331824/136903488-24bee0a3-8e07-498d-878e-e75f1edb59fc.PNG)

![scroll2](https://user-images.githubusercontent.com/19331824/136903410-7b216665-6d38-4a10-b358-5005e8c9c231.PNG)

![scroll3](https://user-images.githubusercontent.com/19331824/136903441-7af2ce10-5cf5-4790-94f0-22ee70df5821.PNG)

2021-10-09 05:44 UTC, Sirmorrison commented
I dont think you will need those custom widgets you are adding since the recent updates to the gioui package has a scrollbar widget attached.
https://github.com/gioui/gio/blob/main/widget/list.go
Correct me if i am wrong but i believe this is what we want.

2021-10-12 06:40 UTC, Sirmorrison commented
Close #665

2021-10-13 11:23 UTC, Sirmorrison commented
Kindly rebase this Pr as the gioui library has been updated to a more recent version.

also, from the first screenshot your dropped, the scrollbar widget does not align with the page content area.. that the the area that is to scroll.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/27733432/137122990-60118b65-03a2-4192-bcef-8c3395429e1b.png">

The second screenshot aligns well to the scroll area, however, it is too close to the content card.. there should be some padding in-between.
<img width="93" alt="image" src="https://user-images.githubusercontent.com/27733432/137123358-bd73a2b7-022e-42e7-93e8-63fe629e71c2.png">

The 3rd screenshot has it scroll bar inside the content area. It should be outside like the others.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/27733432/137123561-e2cbe065-df1b-4e59-9fb9-b72c6cb48dd1.png">

2021-10-18 15:48 UTC, Sirmorrison requested changes
Kindly pay attention to reviews on the icons size parameter.

2021-10-18 15:48 UTC, Sirmorrison commented on ui/decredmaterial/icon.go
> +	Size  int
This is redundant. Kindly remove.

2021-10-18 15:48 UTC, Sirmorrison commented on ui/decredmaterial/icon.go
> +func (icon *Icon) Layout(gtx C) D {
```suggestion
func (icon *Icon) Layout(gtx C, iconSize unit.Value) D {
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/decredmaterial/icon.go
> +	}
```suggestion
	gtx.Constraints.Min.X = gtx.Px(iconSize)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/modal/info_modal.go
> +				return in.dialogIcon.Layout(gtx)
```suggestion
				return in.dialogIcon.Layout(gtx, values.MarginPadding50)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/modal/info_modal_layouts.go
> +					return ic.Layout(gtx)
```suggestion
					return ic.Layout(gtx, values.MarginPadding8)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/modal/info_modal_layouts.go
> +					return ic.Layout(gtx)
```suggestion
					return ic.Layout(gtx, values.MarginPadding8)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/modal/text_input_modal.go
> +						return img.Layout(gtx)
```suggestion
						return img.Layout(gtx, values.MarginPadding20)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/about_page.go
> +								return pg.chevronRightIcon.Layout(gtx)
```suggestion
								return pg.chevronRightIcon.Layout(gtx, values.MarginPadding20)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +							return ic.Layout(gtx)
```suggestion
							return ic.Layout(gtx, values.MarginPadding20)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +						return ic.Layout(gtx)
```suggestion
						return ic.Layout(gtx,values.MarginPadding20)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/debug_page.go
> +					return ic.Layout(gtx)
```suggestion
					return ic.Layout(gtx, values.MarginPadding22)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +			pg.walletStatusIcon.Size = 5
```suggestion
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +				return pg.walletStatusIcon.Layout(gtx)
```suggestion
				return pg.walletStatusIcon.Layout(gtx, values.MarginPadding5)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +		//clr = pg.Theme.Color.Success
Remove if no longer needed.

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +	pg.walletStatusIcon.Size = 14
```suggestion
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +					return pg.walletStatusIcon.Layout(gtx)
```suggestion
					return pg.walletStatusIcon.Layout(gtx, values.MarginPadding14)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +							return pg.cachedIcon.Layout(gtx)
```suggestion
							return pg.cachedIcon.Layout(gtx, values.MarginPadding16)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/overview_page.go
> +		return syncStatusIcon.Layout(gtx)
```suggestion
		return syncStatusIcon.Layout(gtx, values.MarginPadding24)
```

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/proposal_details_page.go
> +		//voteBar:            l.Theme.VoteBar(decredmaterial.NewIcon(l.Icons.ActionInfo), decredmaterial.NewIcon(l.Icons.ImageBrightness1)),
Remove if no longer needed

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/proposal_details_page.go
> +					return icon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/proposal_details_page.go
> +					return icon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/proposals_page.go
> +									return pg.infoIcon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/proposals_page.go
> +			return pg.updatedIcon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/votebar_widget.go
> +					return v.legendIcon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/votebar_widget.go
> +				return v.infoIcon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/wallet_selector.go
> +										return ic.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/proposal/wallet_selector.go
> +									return ic.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/seedbackup/backup_success.go
> +						return successIcon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/send/send_confirm_modal.go
> +								return icon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/send/send_confirm_modal.go
> +						return icon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/settings_page.go
> +						return row.icon.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/tickets/utils.go
> +										return ic.Layout(gtx)
Same as above

2021-10-18 15:48 UTC, Sirmorrison commented on ui/page/tickets/vsp_selector.go
> +										return ic.Layout(gtx)
Same as above

2021-10-21 11:30 UTC, Sirmorrison requested changes, later dismissed
Scrollbar not visible on the Overview page.
![image](https://user-images.githubusercontent.com/27733432/138266872-715d5975-13b5-4076-b71d-0d52e94fb4da.png)

No scroll bar on tx details page.
![image](https://user-images.githubusercontent.com/27733432/138267104-5c336267-38be-4092-bd14-06f004948378.png)

No scroll bar on wallet page when all the wallets are expanded.
![image](https://user-images.githubusercontent.com/27733432/138267282-603a2df7-bb79-414e-9b68-7e2c5c64a07f.png)

Not so sure why this icon is on the left of your page instead of the right.
![image](https://user-images.githubusercontent.com/27733432/138267523-65e46b2a-892b-4d92-bb0d-5decb4ed473c.png)

The scroll padding on the proposals page is not uniform as the against tx and ticket pages.
![image](https://user-images.githubusercontent.com/27733432/138267863-d6df7e23-69f4-4c6d-aad0-9ba1d94d4f25.png)

Proposal details content area does not have a scroll bar.
![image](https://user-images.githubusercontent.com/27733432/138268088-1e47978a-b833-4985-9d07-d0c3137d88a9.png)

Setting page does not have a scroll bar.
![image](https://user-images.githubusercontent.com/27733432/138268171-063a1e1c-3362-4a52-91f3-0536992a6000.png)

* Wallet Log Page and statistics page do not also have scroll bars.

The idea of this PR is to add scroll bars to all pages that scrolls. Meaning any page that has the `list` layout.

2021-10-21 11:30 UTC, Sirmorrison commented on ui/decredmaterial/clickable_list.go
> +		HideScroll:     false,
Rename to `IsHiddenScrollBer`

2021-10-21 11:30 UTC, Sirmorrison commented on ui/page/proposal/proposals_page.go
> +	pg.categoryList.HideScroll = true
```suggestion
	pg.categoryList.IsHiddenScrollbar = true
```

2021-10-21 11:30 UTC, Sirmorrison commented on ui/page/wallet_page.go
> +	//pg.layoutAddWalletSection(gtx)
If not needed, kindly remove.

2021-10-21 11:30 UTC, Sirmorrison commented on ui/page/wallet_page.go
> +			//}),
If not needed, kindly remove.

2021-10-21 11:30 UTC, Sirmorrison commented on ui/decredmaterial/clickable_list.go
> +	return material.List(cl.theme.Base, cl.list).Layout(gtx, count, func(gtx C, i int) D {
Why use `gio material` directly? Kindly add this as a file on the `decredmaterial` package. `list.go`.
See here for examples.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/checkbox.go.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/label.go.

2021-10-21 11:30 UTC, Sirmorrison commented on ui/page/seedbackup/verify_seed.go
> +						return material.List(pg.Theme.Base, pg.list).Layout(gtx, len(pg.multiSeedList), func(gtx C, i int) D {
Why are we using `material.List`? Kindly add this as a file on the decredmaterial package. list.go.
See here for examples.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/checkbox.go.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/label.go.

2021-10-21 11:30 UTC, Sirmorrison commented on ui/page/tickets/overview.go
> +		return material.List(pg.Theme.Base, pg.list).Layout(gtx, len(widgets), func(gtx C, i int) D {
Why use gio material directly? Kindly add this as a file on the decredmaterial package. list.go.
See here for examples.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/checkbox.go.
https://github.com/planetdecred/godcr/blob/master/ui/decredmaterial/label.go.

2021-10-21 11:35 UTC, dreacot commented on ui/decredmaterial/clickable_list.go
> +		HideScroll:     false,
`isScrollBarHidden` seems like a better variable name

2021-10-25 17:33 UTC, dreacot reviewed
The all tickets page shows a long scrollbar, but the remainder of the page is blank
<img width="792" alt="Screenshot 2021-10-25 at 6 21 20 PM" src="https://user-images.githubusercontent.com/25265396/138741273-fe9f229a-ffb7-461e-8c80-89489c01c634.png">

This page should have a scrollbar
<img width="798" alt="Screenshot 2021-10-25 at 6 23 54 PM" src="https://user-images.githubusercontent.com/25265396/138741651-2cd8a4f2-4891-4c8f-8eed-0c44aa740c3e.png">

This modal should have a scrollbar
<img width="386" alt="Screenshot 2021-10-25 at 6 24 43 PM" src="https://user-images.githubusercontent.com/25265396/138741753-2e173c25-81a9-4d3c-8494-65810e8b47ae.png">

This page is scrolled to the bottom but the scrollbar isn't
<img width="798" alt="Screenshot 2021-10-25 at 6 26 37 PM" src="https://user-images.githubusercontent.com/25265396/138742020-bfc50b56-883f-4db0-aca2-056723aaf462.png">

2021-10-26 18:49 UTC, dreacot submitted a review, later dismissed
LGTM

2021-10-26 18:49 UTC, dreacot commented on ui/page/transactions_page.go
> +		// container:       layout.Flex{Axis: layout.Vertical},
remove unused code

2021-10-26 18:52 UTC, dreacot approved these changes
LGTM

2021-10-26 18:54 UTC, merged