Update Transactions Page to reflect new mockup
planetdecred/godcr pull request #666
Opened 2021-10-12 19:56 UTC by devchoplife

Closes #651 
This PR implements the following:
- Adds year to the time format on transactions row
- Adds DurationAgo function that gets exact time since a txn has been made 
- Adds the time ago for txn on transactions row

This PR will not address the trnansaction details hash as the page is still undergoing changes

2021-10-18 17:54 UTC, dreacot commented
![Screenshot from 2021-10-18 18-45-13](https://user-images.githubusercontent.com/25265396/137781307-0d85bf04-e7a1-45da-bc3a-3d4a8a874780.png)

@devchoplife we have December and August showing 1 year ago, is that intended, or shouldn't the month ago also be added?

2021-10-18 18:01 UTC, devchoplife commented
> ![Screenshot from 2021-10-18 18-45-13](https://user-images.githubusercontent.com/25265396/137781307-0d85bf04-e7a1-45da-bc3a-3d4a8a874780.png)
> 
> @devchoplife we have December and August showing 1 year ago, is that intended, or shouldn't the month ago also be added?

Not intended 
A condition is missing 
Working on that

2021-10-18 18:10 UTC, dreacot requested changes

2021-10-18 18:10 UTC, dreacot commented on ui/page/components/components.go
> +	//Split current date and time, and  txn date and time then store in variables
```suggestion
	// Convert timestamp to date in string format (yyyy:mm:dd hr:m:s +0000 UTC)
	currentTimestamp := time.Now().UTC().String()
	txnTimestamp := time.Unix(timestamp, 0).UTC().String()
	// Split the date so we can sepparate into date and time for current time and time of txn
	currentTimeSplit := strings.Split(currentTimestamp, " ")
	txnTimeSplit := strings.Split(txnTimestamp, " ")
	// Split current date and time, and  txn date and time then store in variables
```
Leave a space before typing the comments

2021-10-18 18:10 UTC, dreacot commented on ui/page/components/components.go
> +			ans := "Yesterday"
what's `ans` ? rename `ans` to something more appropriate

2021-10-18 18:20 UTC, dreacot reviewed
also the transaction hash hasn't been truncated as requested

2021-10-20 19:02 UTC, dreacot requested changes
- 2 weeks ago16days, should be 2 weeks 16 days ago
- after having 2weeksago16days, the next line decreases and says 2 weeks, that's not right
- Last month should read 1 month ago
![Screenshot from 2021-10-20 19-57-53](https://user-images.githubusercontent.com/25265396/138154759-047d8d35-6857-4931-811f-533ab2cd9892.png)

- Last year should say 1 year ago
![Screenshot from 2021-10-20 20-01-29](https://user-images.githubusercontent.com/25265396/138155303-bd66ef8c-5b4f-4afc-9b06-7482cbd5e6b8.png)

2021-10-25 18:34 UTC, dreacot approved these changes

2021-10-25 18:36 UTC, merged