Update Proposal UI to new Mock up
planetdecred/godcr pull request #691
Opened 2021-11-10 19:14 UTC by Sirmorrison

Fix #598 
Fix #600
Add governance splace screen
- Set default label colour.
- Set font weight from Bold to semibold based on mockup
- Fix html renderer indentation bug.

2021-11-16 16:03 UTC, dreacot requested changes
1. This page shouldn't be on the governance page, but rather on the overview page, just the same way you have the recent transactions card with the see all button
![Screenshot from 2021-11-16 16-47-01](https://user-images.githubusercontent.com/25265396/142018136-f43f264f-4ca9-4f7a-912f-4219c734b9da.png)

2. after proposals are update there's a green checkmark that should show, it's currently not implemented
![Screenshot from 2021-11-16 16-50-13](https://user-images.githubusercontent.com/25265396/142018723-d205d9f3-c1fe-4d51-94f5-5616c001ad89.png)

3. going to the governance page, and filtering for approved proposals, the scrollbar starts at the bottom of the screen
![Screenshot from 2021-11-16 16-52-59](https://user-images.githubusercontent.com/25265396/142019143-7644810b-0402-429d-8847-344c7e564946.png)

2021-11-16 16:03 UTC, dreacot commented on ui/load/load.go
> +		GovernanceActiveIcon:     decredmaterial.NewImage(decredIcons["governance_a"]),
```suggestion
		GovernanceActiveIcon:     decredmaterial.NewImage(decredIcons["governance_active"]),
```
Why isn't this governance_active

also it seems two images were added `governance_a` and `governance_active`

2021-11-16 16:07 UTC, dreacot commented
The info icon as seen on the mockup doesn't seem to be implemented
![Screenshot from 2021-11-16 17-06-00](https://user-images.githubusercontent.com/25265396/142021553-97f61c58-e286-48ba-b9fe-7f0121342d6d.png)

2021-11-16 16:57 UTC, Sirmorrison commented
>     1. This page shouldn't be on the governance page, but rather on the overview page, just the same way you have the recent transactions card with the see all button
>        ![Screenshot from 2021-11-16 16-47-01](https://user-images.githubusercontent.com/25265396/142018136-f43f264f-4ca9-4f7a-912f-4219c734b9da.png)
> 
>     2. after proposals are update there's a green checkmark that should show, it's currently not implemented
>        ![Screenshot from 2021-11-16 16-50-13](https://user-images.githubusercontent.com/25265396/142018723-d205d9f3-c1fe-4d51-94f5-5616c001ad89.png)
> 
>     3. going to the governance page, and filtering for approved proposals, the scrollbar starts at the bottom of the screen
>        ![Screenshot from 2021-11-16 16-52-59](https://user-images.githubusercontent.com/25265396/142019143-7644810b-0402-429d-8847-344c7e564946.png)

From the mockup, the overview page is the governance page.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/27733432/142029790-1bda8389-d2e2-43df-944b-2bcc8bf96e25.png">

and the page you proposals page holds the proposals filters.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/27733432/142030067-06872e9c-70af-4917-9300-27bd1483285e.png">

2021-11-19 20:09 UTC, dreacot approved these changes

2021-11-19 20:09 UTC, merged