Fixes account mixer bug
planetdecred/godcr pull request #692
Opened 2021-11-12 04:46 UTC by AdimekweEbuka

This PR fixes account mixer bug. Fixes #686 
![godcr (testnet) 2021-11-03 00-465-00](https://user-images.githubusercontent.com/76660305/141410139-9efef8f1-a9aa-4c0a-a59b-22be0b9540ae.gif)

Please note this PR also makes some changes in-order to avoid this (clicking outside the modal cancels the modal leaving the switch key still active):
![fingodcr (testnet) 2021-11-03 00-46-00](https://user-images.githubusercontent.com/76660305/141410252-7d0767e2-3535-4b1a-be77-7de7eefe6e57.gif)

**FIX**
![godcr (testnet) 2021-11-12 05-43-14](https://user-images.githubusercontent.com/76660305/141411142-c279ca3b-c84f-4e5e-8c3d-b353bc24b2f0.gif)

2021-11-12 05:51 UTC, devchoplife reviewed
This looks and works fine on my end

2021-11-12 06:34 UTC, Sirmorrison requested changes

2021-11-12 06:34 UTC, Sirmorrison commented on ui/modal/password_modal.go
> -		isCancelable: true,
Revert this.

2021-11-12 06:34 UTC, Sirmorrison commented on ui/modal/info_modal.go
> +		isCancelable: false,
Revert this.
due to this, the below modal cannot be minimized by clicking the background.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/141420172-f2f823e8-cc48-4816-9dc6-76ef0add8465.png">

2021-11-12 06:34 UTC, Sirmorrison commented on ui/modal/create_password_modal.go
> +		isCancelable:     false,
Revert this.

2021-11-12 06:34 UTC, Sirmorrison commented on ui/page/wallets/privacy_page.go
> +		}).
```suggestion
		NegativeButton("Cancel", func() {
			pg.toggleMixer.SetChecked(false)
		}).
```
this is all you need as the mixing process has not started.

To set exit the info modal, you will need to add it here https://github.com/planetdecred/godcr/blob/977d09b6c16b4bd758b751c1e596e37aa0e4115f/ui/page/privacy_page.go#L347.

2021-11-12 06:35 UTC, Sirmorrison commented
Should you not want a modal to be canceled from the background, you can use the `SetCancelable(false)`

2021-11-12 09:11 UTC, dreacot commented
Modals should be cancellable by clicking the backdrop, we already spent time creating a PR that solves that issue, we shouldn't be reverting it here

2021-11-13 23:04 UTC, Sirmorrison requested changes

2021-11-13 23:04 UTC, Sirmorrison commented on ui/modal/password_modal.go
> +		pm.negativeButtonClicked()
This should be inside the condition.

2021-11-14 17:12 UTC, AdimekweEbuka commented
`in.negativeButtonClicked()` removed from info_modal (line 181). All info modals kept crashing the app when backdrop is clicked. Info modals working correctly now.

2021-11-15 11:35 UTC, Sirmorrison requested changes

2021-11-15 11:35 UTC, Sirmorrison commented on ui/modal/password_modal.go
> +			pm.negativeButtonClicked()
Kindly revert this as its not related to this PR.

2021-11-15 11:35 UTC, Sirmorrison commented on ui/modal/password_modal.go
> +			pm.negativeButtonClicked()
Kindly revert this as its not related to this PR.

2021-11-16 09:19 UTC, Sirmorrison approved these changes

2021-11-16 09:41 UTC, merged