Open one dropdown menu at a time
planetdecred/godcr pull request #693
Opened 2021-11-15 07:10 UTC by devchoplife

FIxes #688 
This PR ensures that only one dropdown menu is open at a time.

2021-11-17 14:51 UTC, dreacot requested changes
Also noticed when the status filter dropdown is opened, you can't click other dropdowns until it's closed.
Other dropdowns should be clickable without having to close the status filter first

![Screenshot from 2021-11-17 15-48-29](https://user-images.githubusercontent.com/25265396/142222807-17fa37cb-9c4a-40e5-9cc5-8dd7cf48b7c4.png)

2021-11-17 14:51 UTC, dreacot commented on ui/decredmaterial/dropdown.go
> +
remove comment

2021-11-17 14:51 UTC, dreacot commented on ui/decredmaterial/dropdown.go
> +//Reslice the dropdowns
```suggestion
// Reslice the dropdowns
```

2021-11-17 14:51 UTC, dreacot commented on ui/decredmaterial/dropdown.go
> +//Display one dropdown at a time
```suggestion
// Display one dropdown at a time
```

2021-11-17 21:35 UTC, devchoplife commented
> Also noticed when the status filter dropdown is opened, you can't click other dropdowns until it's closed. Other dropdowns should be clickable without having to close the status filter first
> 
> ![Screenshot from 2021-11-17 15-48-29](https://user-images.githubusercontent.com/25265396/142222807-17fa37cb-9c4a-40e5-9cc5-8dd7cf48b7c4.png)

I can reproduce this on master too. I will try to find the source of the issue. However, I think the backdrop might be responsible

2021-11-17 21:43 UTC, dreacot commented
Yeah, it's on master, i was just stating since you were working on the dropdowns, if it's something complex to fix then we can merge this PR and create and issue for it, just let me know

2021-11-17 21:44 UTC, devchoplife commented
> Yeah, it's on master, i was just stating since you were working on the dropdowns, if it's something complex to fix then we can merge this PR and create and issue for it, just let me know

Duly noted

2021-11-29 20:35 UTC, dreacot approved these changes
LGTM

2021-11-29 20:38 UTC, merged