Fixes wallet dropdown bug
planetdecred/godcr pull request #695
Opened 2021-11-20 12:55 UTC by AdimekweEbuka

Fixes #689
![godcr (testnet) 2021-11-20 13-44-17](https://user-images.githubusercontent.com/76660305/142727050-0f1e95b5-74e5-4bea-89ec-8909b3433588.gif)

2021-11-20 14:35 UTC, devchoplife requested changes
This fix is not implemented on tickets list page

2021-11-22 05:51 UTC, devchoplife submitted a review, later dismissed
Looks good

2021-11-22 07:34 UTC, Sirmorrison requested changes

2021-11-22 07:34 UTC, Sirmorrison commented on ui/load/wallet.go
> +} //
Why is the `//`?

2021-11-22 07:34 UTC, Sirmorrison commented on ui/page/transaction/transaction_details_page.go
> +	//
What is this for?

2021-11-22 08:30 UTC, AdimekweEbuka commented on ui/page/transaction/transaction_details_page.go
> +	//
Sorry, forgot to take it out.

2021-11-22 10:38 UTC, Sirmorrison approved these changes

2021-11-22 10:39 UTC, merged