Ensure that amount is revalidated when source account is changed
planetdecred/godcr pull request #749
Opened 2022-01-04 11:08 UTC by devchoplife

Closes #743 
This PR:

- Ensures that send amount is revalidated when source account is changed 
- Keep the send button grey until amount is succesfully validated

2022-01-04 13:14 UTC, Sirmorrison requested changes

2022-01-04 13:14 UTC, Sirmorrison commented on ui/page/send/page.go
> +	}
is this needed?

2022-01-04 13:55 UTC, devchoplife commented on ui/page/send/page.go
> +	}
It was a debugging code I ommited when cleaning up code

2022-01-05 08:47 UTC, Sirmorrison requested changes

2022-01-05 08:47 UTC, Sirmorrison commented on ui/page/send/page.go
> +	currentAccountNumber  int32
Rather than have this here, you can simple add an `OnChanged()` to the account selector modal, and returns a bool when ever the account changes.

2022-01-05 08:47 UTC, Sirmorrison commented on ui/page/send/page.go
> +	pg.defaultAcccountNumber = pg.sourceAccountSelector.SelectedAccount().Number
same applies here.

2022-01-05 08:47 UTC, Sirmorrison commented on ui/page/send/page.go
> +		pg.defaultAcccountNumber = pg.currentAccountNumber
this then will be 
```suggestion
        // this is just a sample code
	if pg.sourceAccountSelector.Changed(){
```

2022-01-07 05:46 UTC, Sirmorrison requested changes

2022-01-07 05:46 UTC, Sirmorrison commented on ui/page/send/page.go
> +			fmt.Println("Validated")
Remove.

2022-01-07 06:07 UTC, Sirmorrison requested changes

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +	defaultAcccountNumber int32
not needed remove please.

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +	isDefaultSet          bool
```suggestion
	changed          bool
```

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +		isDefaultSet: false,
remove

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +	return false
```suggestion
	changed := as.changed
	as.changed = false
	return changed
```

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
> +
Remove

2022-01-07 06:07 UTC, Sirmorrison commented on ui/page/components/account_selector.go
>  			title(as.dialogTitle).
replace this with

```
for as.openSelectorDialog.Clicked() {
		newAccountSelectorModal(as.Load, as.selectedAccount, as.wallets).
			title(as.dialogTitle).
			accountValidator(as.accountIsValid).
			accountSelected(func(account *dcrlibwallet.Account) {
				if as.selectedAccount.Number != account.Number{
					as.changed = true
				}
				as.setupSelectedAccount(account)
				as.callback(account)
			}).Show()
	}
```

2022-01-08 05:48 UTC, Sirmorrison commented
So an end test case.

When on currency = none, and i am to send max without an address, i get prompted to set an address since it is needed to calculate the max balance.

When this address is removed, the max balance is still active.
Navigating to `My account`, the max amount is set since it is still active from the address tab.
navigating back to `address`, the max amount is returned even without an address set.

![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/27733432/148633190-4cbde72c-c13e-4185-bb44-fc5736a73776.gif)

2022-01-10 15:30 UTC, Sirmorrison approved these changes

2022-01-10 15:31 UTC, merged