Send page password/Key event Bug
planetdecred/godcr pull request #753
Opened 2022-01-06 09:32 UTC by crux25

This PR restructures how Key events are delivered to the modals and Pages, fixes the bug where pages and modals listen to key events on the same channel and try to handle the same events simultaneously. It also fixes #739  where the password confirmation editor goes out of focus when sending DCR to accounts.

2022-01-07 05:11 UTC, Sirmorrison requested changes
On the send page, when the send confirmation modal is opened, and the tab Key is pressed a couple of times, queues up the key events and closing the modal makes the tabs to jump.

![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/27733432/148495046-6d9825c0-bdc4-4c03-8ea1-39d00151a2c8.gif)

2022-01-07 11:41 UTC, crux25 commented
> 

It is functioning according to design. The cursor goes between the input fields because the events was queued up when the App was pulling exchange rate and tx fees from network.

2022-01-07 11:44 UTC, Sirmorrison commented
> > 
> 
> It is functioning according to design. The cursor goes between the input fields because the events was queued up when the App was pulling exchange rate and tx fees from network.

This is a wrong design then because if i push the tab 20 times when the confirm modal is open, closing the modal, the tab event goes round all the input fields until the 20 queued tab events are completed.

2022-01-07 11:48 UTC, crux25 commented
> > > 
> > 
> > 
> > It is functioning according to design. The cursor goes between the input fields because the events was queued up when the App was pulling exchange rate and tx fees from network.
> 
> This is a wrong design then because if i push the tab 20 times when the confirm modal is open, closing the modal, the tab event goes round all the input fields until the 20 queued tab events are completed. When the Confirmation modal is opened, there should be no queued event on the send page.

I didn't realize you mean that the send page is receiving tab events for the confirm password input. 
I'll fix it.

2022-01-08 05:18 UTC, Sirmorrison commented
![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/27733432/148632504-3ea9acbb-6aba-4149-970c-fb8416c46425.gif)

Same behaviour is noticed when i switch to my address, and tap the tab button a couple of time when currency conversion is set to `none` and change back to address.

2022-01-10 07:02 UTC, Sirmorrison approved these changes

2022-01-10 07:03 UTC, merged