make watch-only wallets show on wallets page
planetdecred/godcr pull request #759
Opened 2022-01-13 14:30 UTC by itswisdomagain

2022-01-13 14:30 UTC, itswisdomagain commented on ui/decredmaterial/button.go
>  func (ib IconButton) ChangeColorStyle(colorStyle *values.ColorStyle) {
We'll need an issue to investigate other uses of this method which likely won't be working as expected.

2022-01-22 04:45 UTC, itswisdomagain commented
Can test with this pub key `tpubVokqVVuZgvPWNuVQXUPMt3znUFJMqArBtuy4m8Xw2GGqBdXCWRqvPua21adM99n43CTn3dMnXnVVrncqkeCs4GukzgdxPRaFF2L322vdog6`.

2022-01-22 06:06 UTC, Sirmorrison requested changes
The PR looks good... Just a few changes.
The option pop up width is too much to the right.
<img width="242" alt="image" src="https://user-images.githubusercontent.com/27733432/150627086-92b53421-7d33-46ef-a749-2e61cd4db72f.png">

it should also have same alignment with the wallet pop up.
**wallet**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/27733432/150627114-e504adb1-4da6-4dcf-9b92-934a7d4e2845.png">

**watch only**
<img width="613" alt="image" src="https://user-images.githubusercontent.com/27733432/150627139-9f85bad4-9fa0-4649-94f7-c42ead85ee3b.png">

2022-01-22 06:06 UTC, Sirmorrison commented on ui/decredmaterial/button.go
> +// it is temporarily changed but when ib.Layout is called, it returns to nil.
When will these `TODO`s be resolved? is this something that can go in to this PR?

2022-01-22 06:19 UTC, Sirmorrison commented
Please add a description to this PR.

2022-01-24 17:08 UTC, itswisdomagain commented on ui/decredmaterial/button.go
> +// it is temporarily changed but when ib.Layout is called, it returns to nil.
Will need to go into a separate issue to be examined separately.

2022-01-25 08:46 UTC, Sirmorrison approved these changes
LGTM

2022-01-25 08:47 UTC, merged