use updated dcrlibwallet PurchaseTicket method
planetdecred/godcr pull request #769
Opened 2022-01-21 16:40 UTC by itswisdomagain

Also add a (temporary) feature to log vsp ticket info from the staking page to confirm the status of purchased tickets. This will help with debugging ticket purchase issues especially pertaining to vsp fee payment.

Uses https://github.com/planetdecred/dcrlibwallet/pull/225.

2022-02-02 06:49 UTC, Sirmorrison requested changes
I get this error when running the app.
```
HEAD is now at 7b24e77 log vsp ticket info when possible
sirmorrison@sirmorrisons-MacBook-Pro godcr-gio % ./godcr --network==testnet
Config file (/Users/sirmorrison/Library/Application Support/Godcr/godcr.conf) does not exist. Using defaults.
2022-02-02 07:48:25.954 [ERR] UI: init multiwallet error: invalid net type

```

2022-02-02 06:49 UTC, Sirmorrison commented on ui/load/wallet.go
> +}
This is similar to what we currently have `Multiwallet.TicketPrice()`. I dont think we need it.

2022-02-02 07:42 UTC, itswisdomagain commented on ui/page/staking/overview.go
> +				err := pg.ticketBuyerWallet.StartTicketBuyer(tbConfig.VspHost, nil, tbConfig.PurchaseAccount, tbConfig.BalanceToMaintain, []byte(password))
I'm going to modify this to only take the password. The other values can be gotten from wallet config.

2022-02-02 16:08 UTC, Sirmorrison requested changes

2022-02-02 16:08 UTC, Sirmorrison commented on ui/page/staking/purchase_modal.go
> +		// because the last used vsp is always updated.
If this is not affected and will not be modified, we really don't need this comment.

2022-02-02 16:08 UTC, Sirmorrison commented on ui/page/staking/vsp_selector.go
> +	for _, vsp := range vsps {
```suggestion
	for _, vsp := range v.WL.MultiWallet.KnownVSPs() {
```

I dont think there is need assigning this to a variable when it is only used once.

2022-02-02 16:22 UTC, Sirmorrison commented
PR functionality looks good just the few changes.

2022-02-03 14:15 UTC, Sirmorrison approved these changes

2022-02-03 14:16 UTC, merged