FIx bug that delay the display of USD balance when GoDcr opens
planetdecred/godcr pull request #784
Opened 2022-02-08 20:02 UTC by devchoplife

This PR closes #783.
This PR ensures that the USD balance is displayed as soon as the app is open.

2022-02-10 18:54 UTC, Sirmorrison requested changes

2022-02-10 18:54 UTC, Sirmorrison commented on ui/page/main_page.go
> +			if mp.usdExchangeSet && mp.dcrUsdtBittrex.LastTradeRate != "" && len(mp.totalBalanceUSD) > 0 {
I really dont think this is the solution to this issue. What you seem to have implemented is a temporary fix to hide USD layout if no total USD Bal.

However, total USD bal is supposed to have data since there exist fetched USD value as can be seen from the send page currency conversion.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/153476920-4b530cc3-cdec-418c-a268-70717db27423.png">

2022-02-13 14:25 UTC, Sirmorrison commented
You need to find a way to refresh the view to display the USD balance the moment it is available.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/27733432/153757519-56b1cd78-4201-48c2-ba89-cf0e94dcbec2.png">

currently, there is USD value but not USD total bal. It is only displayed after the app is restarted.

2022-02-13 21:53 UTC, devchoplife commented
> You need to find a way to refresh the view to display the USD balance the moment it is available. <img alt="image" width="797" src="https://user-images.githubusercontent.com/27733432/153757519-56b1cd78-4201-48c2-ba89-cf0e94dcbec2.png">
> 
> currently, there is USD value but not USD total bal. It is only displayed after the app is restarted.

Address is needed to calculate the transaction fee and address is not set. Testing from my end, It works fine when address is set. Please set address and test again to check if we have the same behavior.

2022-02-16 07:12 UTC, Sirmorrison requested changes

2022-02-16 07:12 UTC, Sirmorrison commented on ui/page/main_page.go
> +	go load.GetUSDExchangeValue(&mp.dcrUsdtBittrex)
the `UpdateBalance` looks to be called multiple times, which will start up multiple go routines... not good. 
You can simply add a condition to check if the usd values is available. if it is not, the fetch it and refresh window. if it is, skip fetching it.

Issue i see here is that if the USD exchange val is updated, the total bal will still be same as `UpdateBalance` is called when there is a new block and tx from the listener.go file.

You would need a way to track and ensure that the USD exchange value is updated with each new block and tx.

2022-02-21 08:05 UTC, Sirmorrison commented on ui/page/main_page.go
> +	mp.UpdateBalance()
Looking carefully, i dont think this should be in the `LayoutUSDBalance` reason is this is meant for just the USD balance display.

What happens if it is moved to the `Layout`?

2022-02-22 06:36 UTC, Sirmorrison requested changes

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/main_page.go
> +	}
```suggestion
func (mp *MainPage) UpdateBalance(fetchExch bool) {
	if len(mp.totalBalanceUSD) == 0 || fetchExch {
		load.GetUSDExchangeValue(&mp.dcrUsdtBittrex)
	}
```

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/listeners.go
>  	mp.UpdateBalance()
```suggestion
	mp.UpdateBalance(true)
```

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/listeners.go
>  	mp.UpdateBalance()
```suggestion
	mp.UpdateBalance(true)
```

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/listeners.go
>  	mp.UpdateBalance()
```suggestion
	mp.UpdateBalance(true)
```

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/listeners.go
>  	mp.UpdateBalance()
```suggestion
	mp.UpdateBalance(true)
```

2022-02-22 06:36 UTC, Sirmorrison commented on ui/page/main_page.go
> +	mp.UpdateBalance()
```suggestion
	mp.UpdateBalance(false)
```

2022-02-22 08:18 UTC, Sirmorrison approved these changes

2022-02-22 08:19 UTC, merged