Show ticket associated with Vote/Revocation transaction
planetdecred/godcr pull request #800
Opened 2022-03-01 23:17 UTC by devchoplife

Closes #792 
This PR fixes the bug that hinders the `View associated ticket` button from showing the details of the ticket associated with a Vote/Revocation transaction.

2022-03-01 23:51 UTC, devchoplife commented
From my investigation, the `View associated tickets` button does not navigate to the ticket details page because it is trying to create another instance of the transaction details page because the current page is also an instance of the transaction details page. By the design of the page functionality, the two instances share the same page ID. The condition below (with the ChangeFragment function which handles page navigation) checks if the current page and the new page have the same IDsm then exits the function if they do:
https://github.com/planetdecred/godcr/blob/733b3411857f604c49d23d501ac9e680906c4dd9/ui/page/main_page.go#L431

The two commits in this PR present two approaches:
- The first ensures that the condition evaluates to false if the current page ID points to the transaction details page 
- The second adds a boolean argument to the ChangeFragment function which when set to true evaluates the condition to false. I believe this is a better approach because it narrows the scope to the specific navigation requirement.

2022-03-07 07:17 UTC, Sirmorrison requested changes
First of all i have a challenge with the approach used for viewing the related ticket. You call the transaction details page from inside the transactions details page this is bad development and not scalable.

From my review, the `ticketSpent` is a transaction on its own. why not just update the page to view the `ticketSpent` details than recalling the transaction details page.

First approach will be to clean up the entire code to accommodate this.
* Add this `txBackStack *dcrlibwallet.Transaction // track original tx` to the `TxDetailsPage` struct.

* Move these codes from line 102 to 122 to a new function

```
func (pg *TxDetailsPage) getTXSourceAccountAndDirection() {
	// find source account
	if pg.transaction.Direction == dcrlibwallet.TxDirectionSent ||
		pg.transaction.Direction == dcrlibwallet.TxDirectionTransferred {
		for _, input := range pg.transaction.Inputs {
			if input.AccountNumber != -1 {
				accountName, err := pg.wallet.AccountName(input.AccountNumber)
				if err != nil {
					// log.Error(err)
				} else {
					pg.txSourceAccount = accountName
				}
			}
		}
	}
	//	find destination address
	if pg.transaction.Direction == dcrlibwallet.TxDirectionSent {
		for _, output := range pg.transaction.Outputs {
			if output.AccountNumber == -1 {
				pg.txDestinationAddress = output.Address
			}
		}
	}
}
```
*  move `pg.txnWidgets = initTxnWidgets(pg.Load, pg.transaction)` to the `OnNavigatedTo`.
`OnNavigatedTo` should look like this.

```
// OnNavigatedTo is called when the page is about to be displayed and
// may be used to initialize page features that are only relevant when
// the page is displayed.
// Part of the load.Page interface.
func (pg *TxDetailsPage) OnNavigatedTo() {
	if pg.transaction.TicketSpentHash != "" {
		pg.ticketSpent, _ = pg.wallet.GetTransactionRaw(pg.transaction.TicketSpentHash)
	}

	if ok, _ := pg.wallet.TicketHasVotedOrRevoked(pg.transaction.Hash); ok {
		pg.ticketSpender, _ = pg.wallet.TicketSpender(pg.transaction.Hash)
	}

	pg.getTXSourceAccountAndDirection()
	pg.txnWidgets = initTxnWidgets(pg.Load, pg.transaction)
}
```

Finally, in the `Layout()` add this to `Back:`
```
InfoButton: pg.infoButton,
Back: func() {
if pg.txBackStack == nil {
	pg.PopFragment()
	return
}
pg.transaction = pg.txBackStack
pg.getTXSourceAccountAndDirection()
pg.txnWidgets = initTxnWidgets(pg.Load, pg.transaction)
pg.txBackStack = nil
pg.RefreshWindow()
},
```

this issue should be fixed...

2022-03-07 07:17 UTC, Sirmorrison commented on ui/page/transaction/transaction_details_page.go
> +			pg.ChangeFragment(NewTransactionDetailsPage(pg.Load, pg.ticketSpent), true)
```suggestion
			if pg.ticketSpent != nil {
			pg.txBackStack = pg.transaction
			pg.transaction = pg.ticketSpent

			pg.getTXSourceAccountAndDirection()
			pg.txnWidgets = initTxnWidgets(pg.Load, pg.transaction)
			pg.RefreshWindow()
		}
```

2022-03-08 06:14 UTC, Sirmorrison approved these changes

2022-03-08 06:18 UTC, merged