Update Dex registration function
planetdecred/godcr pull request #801
Opened 2022-03-02 16:00 UTC by song50119

Work towards https://github.com/planetdecred/godcr/issues/619.
Related https://github.com/planetdecred/godcr/pull/722#issuecomment-1046795051

- Add selector fee asset modal
- Choose fee asset when add new DEX

2022-03-05 22:00 UTC, devchoplife reviewed
On the dex server selection modal, when I toggle the green tick to activate the dex server, the modal and button edges behave abnormally. See the video below for more information:
https://streamable.com/qbwu31

2022-03-08 12:02 UTC, itswisdomagain requested changes
First pass. More later.

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +	appPassword    decredmaterial.Editor
I'm not familiar with a concept of "default app pass"; just app pass.
```suggestion
	// dexClientPassword will be used if set, without requesting password input on UI.
	dexClientPassword string
	dexClientPasswordEditor    decredmaterial.Editor
```

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +	listServerClickable map[string]*decredmaterial.Clickable
`knownServers`

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +	customServerBtn     decredmaterial.Button
`pickServerFromListBtn` and `useCustomServerBtn`

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +	for i := 0; i < len(dexServers); i++ {
```suggestion
	for _, server := range dexServers {
```

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +		}
```suggestion
		if canSubmit {
			md.doAddDexServer(dexServer, appPass)
		} else if md.defaultAppPass == "" {
			md.appPassword.Editor.Focus()
		}
```

2022-03-08 12:02 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +func (md *addDexModal) validateInputs() (bool, string, string) {
Without checking the fields, return `false, "", ""` if `md.isSending` is true.

2022-03-14 15:32 UTC, dreacot commented
![Screenshot from 2022-03-14 16-32-05](https://user-images.githubusercontent.com/25265396/158206224-932438b4-6621-459e-8e4d-64c618c89e46.png)


After choosing Decred as a means of paying the registration fee, the app crashes.

see log below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12dd1ce]

goroutine 6288 [running]:
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).UpdateSelectedAccountBalance(0xc004e8d810)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:122 +0x2e
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).ListenForTxNotifications.func1(0xc004e8d810, 0x1eab158, 0xc0062b4940)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:225 +0x1bd
created by github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).ListenForTxNotifications
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:203 +0x53
```

2022-04-01 08:31 UTC, Sirmorrison commented
This PR contains codes from master that hides the dex navigation option. Kindly undo this on this PR.

2022-04-13 12:49 UTC, itswisdomagain requested changes
Will review selector_fee_asset_modal.go in my next round. This is looking really good.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +	}
Will this list of known dex servers change after the modal is created? I think these can be initialized when the modal is created rather than on resume.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +				}
I wondered why `confirmRegistration` referenced properties from the original add dex modal but it seems the idea is to show progress on the initial modal. I'm not sure it's working as intended, perhaps because `md` was dismissed above.

In any case, here's a flow that appeals more to me:
- The smooth flow, as you've implemented: After the user selects a dex or inputs a dex address, he's required to pick an asset to use to pay the fee and then he's asked to confirm the registration before the fee is paid and registration is done.
- If the user is required to add a wallet after selecting a particular fee asset, but cancels the add wallet modal, the user should be taken back to the asset selection modal.
- If the user cancels the confirm reg modal, it should be interpreted to mean the user doesn't want to pay the fee; and the asset selection modal should be re-displayed in case the user would want to pay with another asset. If that asset selection modal is canceled, the entire process is then aborted.

I experimented with a `payFeeAndRegister` function in [this commit](https://github.com/itswisdomagain/godcr-1/commit/bffa38536b4d9ff508eae90ba90097fe7d148a7e) that achieves those objective. You can peruse that commit and copy over select changes or cherry-pick the commit in its entirety to your branch.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
> +					int32(cfReg.dexServer.Fee.ID),
`dexServer.Fee` is deprecated, should be using `regFeeAsset := dexServer.RegFees[feeAsset.Symbol]` and `regFeeAsset.Amt/.ID`.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/add_dex_modal.go
>  }
This long confirmation text should no longer be necessary with the addition of the fee asset selector modal also showing the available markets and lot sizes. Can leave this for now but ultimately, this message should only show `fmt.Sprintf("Confirm DEX registration. When you submit this form, %s will be spent from your wallet to pay registration fees.", feeAmt)`.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/create_wallet_modal.go
> +		if md.dexClientPassword != "" && canSubmit {
Don't need this duplicate check, if `canSubmit` is true, then a dex client password is provided.
```suggestion
		if canSubmit {
```

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/create_wallet_modal.go
> +		} else {
Only focus the app password editor `if md.dexClientPassword == ""`.
```suggestion
		} else if md.dexClientPassword == "" {
```

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/markets.go
> +		shouldStartDex: l.Dexc().Core() == nil,
This shouldn't be a property, can always do `if l.Dexc().Core() == nil` wherever necessary.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/markets.go
> +	dexServer *core.Exchange
This should be a method that returns the first exchange in `pg.Dexc().DEXServers()`, doesn't need to be a variable stored on the page struct.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/dexclient/markets.go
> +			}
You're calling `pg.setDexServer()` when you've just confirmed that `pg.setDexServer != nil`? Don't get the idea here.

2022-04-13 12:49 UTC, itswisdomagain commented on ui/page/main_page.go
> -			// Temp disabling. Will uncomment after release
Also restore the debug reset dex client feature.

2022-04-23 08:03 UTC, song50119 commented on ui/page/dexclient/markets.go
> +	dexServer *core.Exchange
dexServer added meaning last choose Dex when app supported multiple Dex selector.

2022-04-23 08:04 UTC, song50119 commented on ui/page/dexclient/markets.go
> +	dexServer *core.Exchange
Ok can leave it for now, will implement at next PR

2022-04-24 14:01 UTC, closed without merging

2022-04-24 15:55 UTC, song50119 commented
reopen