multi: add shadow widget to debug and about page
planetdecred/godcr pull request #835
Opened 2022-03-26 07:51 UTC by AdimekweEbuka

Resolves #818 
![godcr (testnet) 2022-03-26 08-31-59](https://user-images.githubusercontent.com/76660305/160229880-089565bb-4426-49d2-b494-89e57ff02fdf.gif)

2022-03-26 08:18 UTC, devchoplife requested changes
The page layout still fades on Debug and About page.
Debug page:
![Screenshot from 2022-03-26 09-13-34](https://user-images.githubusercontent.com/66803475/160231003-31a74172-a5ae-488e-8399-a1f2254b999c.png)

About page:
![Screenshot from 2022-03-26 09-13-45](https://user-images.githubusercontent.com/66803475/160231019-c1bbcd73-8a7f-406c-9215-1671470e16a5.png)

Looking at the More page, I believe this is more suitable as the shadow completely wraps the row and makes it distinct when hovered on.
More Page:
![Screenshot from 2022-03-26 09-12-04](https://user-images.githubusercontent.com/66803475/160231071-f82331ea-b777-4645-9a8a-40eb2aaa3f9b.png)

2022-03-28 21:23 UTC, AdimekweEbuka commented
Regarding @devchoplife  review, I was able to recreate the debug page following the more page and I was able to get the shadow effect exactly as requested. See below: 
![godcr (testnet) 2022-03-28 21-30-25](https://user-images.githubusercontent.com/76660305/160486729-72edf5b4-e975-400b-9fc1-001ab97dee5b.gif)


>However this is not the design that was on the original debug page, as on the original page there was no space between rows, inorder to get that design I removed the margins and after doing so the shadow effect got reverted to this. Please see below: 
![godcr (testnet) 2022-03-28 21-33-53](https://user-images.githubusercontent.com/76660305/160487060-1c56a2d5-aea1-43e0-a687-dddbe068db89.gif)

>I have noticed that in pages where the rows are smooched together like that the shadow effect is faded but when seperated, its more prominent. Please see the transaction page, about page and recent transactions on the overview page: 

![godcr (testnet) 2022-03-28 21-31-37 (1)](https://user-images.githubusercontent.com/76660305/160487604-02c7e80d-87cb-4db6-8f29-feba8b807bd9.gif)


>I'm having trouble figuring out the reason for this discrepancy. 
>@SirMorrison Please can we get your take on this.

2022-03-29 06:23 UTC, Sirmorrison requested changes

2022-03-29 06:23 UTC, Sirmorrison commented on ui/page/debug_page.go
> -	list       *decredmaterial.ClickableList
Undo this. The clickable list has `IsShadowEnabled` Param. Use it instead see example use case here.
.https://github.com/planetdecred/godcr/blob/928443619efe397e68133e2692ca5ee1675bb315/ui/page/transaction/transactions_page.go#L51.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/27733432/160543594-c5e84537-8ae9-4a56-ad0e-6ed380892223.png">

2022-03-29 06:23 UTC, Sirmorrison commented on ui/page/about_page.go
>  					layout.Rigid(func(gtx C) D {
You are repeating codes. At the very best avoid repeating codes. instead use function and call them where needed.

```suggestion
			licenseRow := func(gtx C) D {
				return pg.licenseRow.Layout(gtx, func(gtx C) D {
					return layout.Flex{}.Layout(gtx,
						layout.Rigid(func(gtx C) D {
							return in.Layout(gtx, pg.license.Layout)
						}),
						layout.Flexed(1, func(gtx C) D {
							return layout.E.Layout(gtx, func(gtx C) D {
								return in.Layout(gtx, func(gtx C) D {
									pg.chevronRightIcon.Color = pg.Theme.Color.Gray1
									return pg.chevronRightIcon.Layout(gtx, values.MarginPadding20)
								})
							})
						}),
					)
				})
			}

			if pg.licenseRow.IsHovered() {
				return pg.shadowBox.Layout(gtx,licenseRow)
			}
			return  licenseRow(gtx)
		},
	}

	return pg.container.Layout(gtx, len(w), func(gtx C, i int) D {
		return layout.Inset{Bottom: values.MarginPadding3}.Layout(gtx, func(gtx C) D {
```
Take note of the insert Bottom  added.

2022-03-30 06:40 UTC, Sirmorrison requested changes
This looks ok from the test. Just a little change and we are good to go.

2022-03-30 06:40 UTC, Sirmorrison commented on ui/page/about_page.go
> +}
make this an inline func() by moving it to the section it was used. 

It was only ever used within that section. I don't see the need for this. except there is a reason though kindly share

2022-03-30 06:40 UTC, Sirmorrison commented on ui/page/about_page.go
> +			return pg.licenseRowLayout(gtx, in)
```suggestion
licenseRow := func(gtx C) D {
				return pg.licenseRow.Layout(gtx, func(gtx C) D {
					return layout.Flex{}.Layout(gtx,
						layout.Rigid(func(gtx C) D {
							return in.Layout(gtx, pg.license.Layout)
						}),
						layout.Flexed(1, func(gtx C) D {
							return layout.E.Layout(gtx, func(gtx C) D {
								return in.Layout(gtx, func(gtx C) D {
									pg.chevronRightIcon.Color = pg.Theme.Color.Gray1
									return pg.chevronRightIcon.Layout(gtx, values.MarginPadding20)
								})
							})
						}),
					)
				})
			}
			if pg.licenseRow.IsHovered() {
				return pg.shadowBox.Layout(gtx,licenseRow)
			}
			return  licenseRow(gtx)
		},
	}
	return pg.container.Layout(gtx, len(w), func(gtx C, i int) D {
		return layout.Inset{Bottom: values.MarginPadding3}.Layout(gtx, func(gtx C) D {
```

2022-03-30 06:40 UTC, Sirmorrison commented on ui/page/about_page.go
> +			return pg.licenseRowLayout(gtx, in)
very important... note `return layout.Inset{Bottom: values.MarginPadding3}`

2022-03-30 21:18 UTC, AdimekweEbuka commented
Please note adding the bottom margin padding causes the license row to look like this when its hovered. 
![godcr (testnet) 2022-03-30 21-29-16](https://user-images.githubusercontent.com/76660305/160932475-ba663e2d-c971-406f-8b92-ceaec3e3fe24.gif)

2022-03-31 06:28 UTC, Sirmorrison approved these changes

2022-03-31 06:29 UTC, merged