Fix seed editor bugs
planetdecred/godcr pull request #860
Opened 2022-03-30 20:39 UTC by devchoplife

Resolves #828 
This PR fixes the bugs listed below:

2022-04-04 07:10 UTC, Sirmorrison requested changes
i get this error about empty seeds.
<img width="793" alt="image" src="https://user-images.githubusercontent.com/27733432/161491355-b29f4ca0-abd6-455c-b49b-6e8cab20f5d3.png">
This was reproduced a couple of times.

Then this 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/27733432/161491502-1cd34263-5500-4745-b275-f97838ff94bc.png">

2022-04-06 06:51 UTC, Sirmorrison requested changes
Initially, using the tab key, the editor is populated however, this does not seem to work anymore.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/161913068-77541192-0d17-40ae-971e-aa231e897cd4.png">

2022-04-06 06:51 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +			focus := pg.seedEditors.focusIndex
This should go into the `if` statement.

2022-04-06 06:51 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +func (pg *Restore) isSeedEditorChanged() bool {
Please add comment on what this does.

2022-04-09 17:02 UTC, dreacot commented on ui/page/wallets/restore_page.go
> +	caretCoordXTracker float32
what this variable does is unclear, please add a comment

2022-04-11 16:34 UTC, Sirmorrison commented
This still does not populate the editor with the first suggestion when tab is pressed.

![ezgif com-gif-maker(13)](https://user-images.githubusercontent.com/27733432/162787925-9e2c1bd1-5e91-43df-83e1-9c212b669aa1.gif)

2022-04-11 17:03 UTC, Sirmorrison commented
<img width="391" alt="image" src="https://user-images.githubusercontent.com/27733432/162790537-8878e206-e3a0-4f60-a032-76690295fa78.png">

<img width="329" alt="image" src="https://user-images.githubusercontent.com/27733432/162790834-d4d69d26-fe05-4eb3-8cc9-24cfaa503b47.png">

When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first.

Also, when the focus shifts to the next editor, the highlight is also on the last item instead of the first as well.
This is also reproducible in master.

I believe we can have it resolved here as well.
![ezgif com-gif-maker(14)](https://user-images.githubusercontent.com/27733432/162792572-301d4690-9e43-4ada-b8dd-471e26bd1289.gif)

2022-04-13 21:05 UTC, dreacot commented
1. `When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first.` this issue still occurs
2. `This still does not populate the editor with the first suggestion when tab is pressed.` this now populates the first suggestion, but when on the second suggestion, and tab is pressed the first suggestion is populated instead of the second

2022-04-13 21:06 UTC, dreacot commented on ui/page/wallets/restore_page.go
> +			fmt.Println(pg.selected)
i believe this was used for debugging, if so, it can be removed

2022-04-14 08:36 UTC, dreacot commented
When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first. this issue still occurs

2022-04-15 16:42 UTC, Sirmorrison requested changes
PR functionality looks good so far. Just a little more update to be carried out.

When navigating to a previous editor, the suggestion should be based on the words already existing in the editor. This can be reproduced in master


<img width="567" alt="image" src="https://user-images.githubusercontent.com/27733432/163596607-e5cd6765-811a-4f14-848f-1997dfe17119.png">

2022-04-18 18:38 UTC, dreacot commented
> "When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first". this issue still occurs

i'm still experiencing this

2022-04-20 06:54 UTC, Sirmorrison requested changes

2022-04-20 06:54 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
>  	caretPosition     int // current caret position
I believe these 2 have same function from the use case also, you have a method `caretPositionChanged()`. Why not leverage in this to carry out the change state. 

It leaves too many seemingly redundant types.

2022-04-20 06:54 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +	seedPhraseStore := ""
kindly comment this so we know what it does... not sure what `seedPhraseStore` is and can we use a better variable name?

2022-04-20 06:54 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +
Remove whitespace

2022-04-20 06:54 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +	seedEditorTracker int // stores the current focus index of seed editors
```suggestion
	nextCaretPosition  int // caret position when seed editor is switched
	currentCaretPosition     int // current caret position
	selectedSeedEditor int // stores the current focus index of seed editors
```

2022-04-21 07:43 UTC, Sirmorrison approved these changes

2022-04-21 07:45 UTC, merged