create modal for votebar infobutton, remove tooltip
planetdecred/godcr pull request #901
Opened 2022-04-24 21:09 UTC by AdimekweEbuka

Resolve #822 

- Change info icon to clickable icon button
- Replace info tooltip with info modal

![godcr (testnet) 2022-04-24 22-05-12](https://user-images.githubusercontent.com/76660305/164996610-7e1323d4-7884-4876-b678-d97bd12647f2.gif)

2022-04-24 22:00 UTC, devchoplife requested changes
The info icon should be on the same line with the vote options as it was initially. Also, it should be aligned right (maintain the same line with the progress bar)
![Screenshot from 2022-04-24 22-55-52](https://user-images.githubusercontent.com/66803475/164998467-9af9b77c-0874-43c0-9791-b5d2d68ef315.png)

2022-04-25 09:06 UTC, Sirmorrison requested changes
<img width="579" alt="image" src="https://user-images.githubusercontent.com/27733432/165056947-65a08507-8f0a-4c07-ac51-6b82c44e5d65.png">

Kindly revert the changes that added the padding below and removed the text in front of the info icon. See original page info.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/27733432/165057298-ed30a612-2836-45d0-a27e-743ad8ff7c98.png">

This issue/Pr is meant to only move the tooltip info to a modal.

2022-04-25 09:06 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +// 		gtx.Constraints.Min.X = gtx.Constraints.Max.X
If these are no longer needed, lets remove them.

2022-04-25 09:06 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +		Title("").
Title should be the vote title.

2022-04-26 07:36 UTC, Sirmorrison requested changes

2022-04-26 07:36 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +		Title("Vote title").
pass the proposal title to the vote bar info button and use the proposal title.

Better still just use `Proposal vote details`

2022-04-26 10:43 UTC, dreacot commented
please add the proper screenshots

2022-04-26 11:36 UTC, AdimekweEbuka commented
> please add the proper screenshots

Noted, will add now.

2022-04-26 11:44 UTC, AdimekweEbuka commented
![godcr (testnet) 2022-04-26 12-37-01](https://user-images.githubusercontent.com/76660305/165292153-3365980e-9813-41c4-bdd2-556459b8f446.gif)


> > please add the proper screenshots
> 
> Noted, will add now.
![godcr (testnet) 2022-04-26 12-37-01](https://user-images.githubusercontent.com/76660305/165292794-046c47e2-2aa7-408f-9ce2-69d1b0c817b2.gif)

2022-04-26 11:45 UTC, AdimekweEbuka commented
> > please add the proper screenshots
> 
> Noted, will add now.
![godcr (testnet) 2022-04-26 12-37-01](https://user-images.githubusercontent.com/76660305/165293008-8eb32bc7-5d8d-4a05-bd13-ba67ee4225af.gif)

2022-04-26 17:08 UTC, dreacot commented
@AdimekweEbuka edit the original description and add it there

2022-04-27 08:41 UTC, Sirmorrison requested changes

2022-04-27 08:41 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +		newInfoButton: l.Theme.IconButton(l.Theme.Icons.ActionInfo),
```suggestion
```

2022-04-27 08:41 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +	vb.newInfoButton.Inset = layout.Inset{}
```suggestion
_, pg.infoButton = components.SubpageHeaderButtons(l)
	pg.infoButton.Size = values.MarginPadding20
```

2022-04-27 08:41 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +	newInfoButton decredmaterial.IconButton
```suggestion
	infoButton decredmaterial.IconButton
```

2022-04-27 08:41 UTC, Sirmorrison commented on ui/page/components/votebar_widget.go
> +				return v.newInfoButton.Layout(gtx)
```suggestion
				return v.infoButton.Layout(gtx)
```

2022-04-27 16:18 UTC, Sirmorrison approved these changes

2022-04-27 16:19 UTC, merged