localize string variables
planetdecred/godcr pull request #906
Opened 2022-04-28 07:10 UTC by Sirmorrison

Fix #854

2022-05-26 16:20 UTC, dreacot requested changes

2022-05-26 16:20 UTC, dreacot commented on ui/page/components/utils.go
> +			log.Errorf("waiting %s to retry function %s after error: %v\n", sleepDur, funcDesc, err)
shouldn't we localize this?

2022-05-26 16:20 UTC, dreacot commented on ui/page/governance/proposal_details_page.go
> +					log.Errorf("Error loading proposal description: %v", err)
seems like all error formatting are intentionally left localized, can you shed more light?

2022-05-26 16:20 UTC, dreacot commented on ui/page/governance/splash_screen.go
> +							text := values.StringF(values.StrGovernanceInfo, `<span style="text-color: gray">`, `<br>`, `</span>`)
this seems like it would produce an error on the UI

2022-05-26 16:20 UTC, dreacot commented on ui/page/main_page.go
> +// Layout draws the page UI components into the provided C
i think the previous comment is still valid

2022-05-26 16:20 UTC, dreacot commented on ui/page/security_tools_page.go
> +// Layout draws the page UI components into the provided C
i think the previous comment is still valid and more explanatory, for all instance of this

2022-05-26 16:20 UTC, dreacot commented on ui/page/staking/auto_ticket_modal.go
> +	// "fmt"
can delete if not needed

2022-05-26 16:20 UTC, dreacot commented on ui/page/staking/auto_ticket_modal.go
> +	// "fmt"
can delete if not needed

2022-05-26 16:21 UTC, dreacot commented on ui/page/governance/proposal_details_page.go
> +					log.Errorf("Error loading proposal description: %v", err)
okay seem like we want all the logs in english, disregard

2022-05-26 16:21 UTC, dreacot commented on ui/page/components/utils.go
> +			log.Errorf("waiting %s to retry function %s after error: %v\n", sleepDur, funcDesc, err)
okay seem like we want all the logs in english, disregard

2022-05-26 18:02 UTC, dreacot commented on ui/page/governance/splash_screen.go
> +							text := values.StringF(values.StrGovernanceInfo, `<span style="text-color: gray">`, `<br>`, `</span>`)
![Screenshot from 2022-05-26 17-11-42](https://user-images.githubusercontent.com/25265396/170548359-5a484c4f-fa2d-415b-89e1-972a36304933.png)

2022-05-26 18:03 UTC, dreacot commented
proposals aren't showing
![Screenshot from 2022-05-26 17-15-44](https://user-images.githubusercontent.com/25265396/170548461-dab664f0-d511-4ef1-aba4-2d42ed48f5a3.png)

2022-05-26 18:22 UTC, dreacot commented
The info icon on the governance splash page doesn't work

2022-05-26 18:27 UTC, devchoplife requested changes
![image](https://user-images.githubusercontent.com/66803475/170552427-1a0d03db-d696-49f0-bd39-73951f4b2d06.png)

2022-06-02 15:04 UTC, dreacot approved these changes

2022-06-02 15:05 UTC, merged