add option to import watch only wallet from the splash screen
planetdecred/godcr pull request #943
Opened 2022-05-22 21:46 UTC by dreacot

Resolves #938 

This PR adds the option to import a watch only wallet from the splash screen.

**Screenshots**
![Screenshot from 2022-05-22 22-43-44](https://user-images.githubusercontent.com/25265396/169717276-617d0991-0742-46e3-a48d-fb5f85a5133d.png)
![Screenshot from 2022-05-22 22-43-55](https://user-images.githubusercontent.com/25265396/169717281-3f6e279a-189c-4f3d-8907-1947264202c4.png)

2022-05-22 21:56 UTC, devchoplife requested changes

2022-05-22 21:56 UTC, devchoplife commented on ui/modal/create_watch_only_modal.go
> +		decredmaterial.SwitchEditors(cm.keyEvent, cm.extendedPubKey.Editor)
One editor cannot be switched
I feel this is not necessary

2022-05-22 22:02 UTC, devchoplife reviewed
LGTM

2022-05-24 16:19 UTC, Sirmorrison approved these changes, later dismissed

2022-05-24 17:59 UTC, Sirmorrison approved these changes
LGTM

2022-05-24 17:59 UTC, merged