Restore wallet using hex
planetdecred/godcr pull request #950
Opened 2022-05-25 21:15 UTC by crux25

This PR allows the import of wallet using hex private key. It also shows the hex private key on the wallet backup page.
Closes #767.

2022-05-27 07:54 UTC, Sirmorrison requested changes
<img width="596" alt="image" src="https://user-images.githubusercontent.com/27733432/170655018-ea099d72-f503-4174-962c-e71a7877d843.png">

So i have my reservation to this design as we have to be production ready with every commit to master.

That said, when a user decides to restore with hex, this should open a modal (text input moda), that takes the hex rather than the center aligned editor widget used.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/27733432/170655674-c9406ae9-8689-40ac-b7df-5cf9f87aee4d.png">

I am so sure why we need to validate the hex like this, however, i believe the hex validation can be done in the background and error from validation displayed on the UI of the modal.

2022-05-27 07:54 UTC, Sirmorrison commented on ui/page/seedbackup/save_seed.go
> +				}),
```suggestion
				layout.Flexed(1, pg.hexLayout),
```

2022-05-27 07:54 UTC, Sirmorrison commented on ui/page/seedbackup/save_seed.go
> +		}),
```suggestion
		layout.Rigid(func(gtx C) D {
			return layout.Flex{Alignment: layout.Middle}.Layout(gtx,
				layout.Rigid(func(gtx C) D {
					card.Radius = decredmaterial.CornerRadius{TopRight: 0, TopLeft: 8, BottomRight: 0, BottomLeft: 8}

					return card.Layout(gtx, func(gtx C) D {
						return layout.UniformInset(values.MarginPadding16).Layout(gtx, func(gtx layout.Context) layout.Dimensions {
							seedString := pg.seed
							if seedString != "" {
								hexString, _ := load.SeedWordsToHex(pg.seed)
								pg.hexLabel.Text = hexString
							}
							return pg.hexLabel.Layout(gtx)
						})
					})
				}),
				layout.Rigid(func(gtx C) D {
					card.Radius = decredmaterial.CornerRadius{TopRight: 8, TopLeft: 0, BottomRight: 8, BottomLeft: 0}
					return layout.Inset{Left: values.MarginPadding1}.Layout(gtx, func(gtx C) D { 
						return card.Layout(gtx, pg.copy.Layout)
					})
				}),
			)
		}),
```

2022-05-27 10:10 UTC, crux25 commented
> Kindly provide a test HEX code.
> 
> <img alt="image" width="596" src="https://user-images.githubusercontent.com/27733432/170655018-ea099d72-f503-4174-962c-e71a7877d843.png">
> 
> So i have my reservation to this design as we have to be production ready with every commit to master.
> 
> That said, when a user decides to restore with hex, this should open a modal (text input moda), that takes the hex rather than the center aligned editor widget used.
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/27733432/170655674-c9406ae9-8689-40ac-b7df-5cf9f87aee4d.png">
> 
> I am so sure why we need to validate the hex like this, however, i believe the hex validation can be done in the background and error from validation displayed on the UI of the modal.

Create a wallet. Try to back up it's seed. You'll find the wallet's hex code on the seed backup page.

2022-05-27 10:13 UTC, crux25 commented
You said you have your reservation to the design? Can you list the reservations so I can fix it and have it production ready by next review. So if I understand you correctly, I should maintain the tabs but instead of showing the current hex page I should use a modal instead?

2022-05-27 10:40 UTC, Sirmorrison commented
> You said you have your reservation to the design? Can you list the reservations so I can fix it and have it production ready by next review. So if I understand you correctly, I should maintain the tabs but instead of showing the current hex page I should use a modal instead?

This can work or we could make use of buttons that performs different actions like what we have on the privacy page for both manual setup and automatic setup.

Manual setup redirects to a page while the automatic opens up a modal.

2022-05-28 18:54 UTC, dreacot commented
I tried to restore an already existing wallet using hex, i first got the "wallet with identical seed error" error after inputting the hex code into the modal, but i was still presented with a modal for inputting wallet name and password.

I was ultimately able to create a wallet using the hex for a wallet that already existed

2022-05-28 18:56 UTC, dreacot commented on ui/modal/hex_wallet_restore_modal.go
> +}
```suggestion
func (hm *HexRestoreModal) OnDismiss() {}
```

2022-05-28 19:02 UTC, crux25 commented
> I tried to restore an already existing wallet using hex, i first got the "wallet with identical seed error" error after inputting the hex code into the modal, but i was still presented with a modal for inputting wallet name and password.
> 
> I was ultimately able to create a wallet using the hex for a wallet that already existed

I'll verify this. I'll run a test and comment in a bit.

2022-05-30 07:35 UTC, Sirmorrison requested changes
Will test and review further after these are resolved.

2022-05-30 07:35 UTC, Sirmorrison commented on ui/modal/hex_wallet_restore_modal.go
> +	return hm.modal.Layout(gtx, w)
We dont need this modal. We already have the `text input modal` to handle scenarios of this nature.

2022-05-30 07:35 UTC, Sirmorrison commented on ui/load/utils.go
> +	return sha256.Sum256(intermediateHash[:])[0]
Let move this lets move these lines of code to `components package utils.go`

2022-05-31 10:53 UTC, Sirmorrison requested changes
functionality looks good. just for the requested changes

2022-05-31 10:53 UTC, Sirmorrison commented on ui/page/seedbackup/save_seed.go
> +	}
```suggestion
	pg.copy.Inset = layout.UniformInset(values.MarginPadding16)
```

2022-05-31 10:53 UTC, Sirmorrison commented on ui/page/seedbackup/save_seed.go
> +		}),
```suggestion
		layout.Rigid(func(gtx C) D {
			return layout.Flex{Alignment: layout.Middle}.Layout(gtx,
				layout.Rigid(func(gtx C) D {
					card.Radius = decredmaterial.CornerRadius{TopRight: 0, TopLeft: 8, BottomRight: 0, BottomLeft: 8}
					return card.Layout(gtx, func(gtx C) D {
						return layout.UniformInset(values.MarginPadding16).Layout(gtx, func(gtx layout.Context) layout.Dimensions {
							seedString := pg.seed
							if seedString != "" {
								hexString, _ := load.SeedWordsToHex(pg.seed)
								pg.hexLabel.Text = hexString
							}
							return pg.hexLabel.Layout(gtx)
						})
					})
				}),
				layout.Rigid(func(gtx C) D {
					card.Radius = decredmaterial.CornerRadius{TopRight: 8, TopLeft: 0, BottomRight: 8, BottomLeft: 0}
					return layout.Inset{Left: values.MarginPadding1}.Layout(gtx, func(gtx C) D { 
						return card.Layout(gtx, pg.copy.Layout)
					})
				}),
			)
		}),
```

2022-05-31 10:53 UTC, Sirmorrison commented on ui/page/wallets/restore_page.go
> +				})
```suggestion
				return layout.Inset{Top: values.MarginPadding5}.Layout(gtx, pg.indexLayout)
```

2022-06-02 15:39 UTC, dreacot commented
1. I chose to restore using HEX;
![Screenshot from 2022-06-02 16-35-01](https://user-images.githubusercontent.com/25265396/171666446-ac909d4b-e15c-416d-8982-b823605cbf89.png)

when i got to the above screen, i decided to cancel the process.

Now i'm unable to select hex again until i first switch to seed words tab
![Screenshot from 2022-06-02 16-35-56](https://user-images.githubusercontent.com/25265396/171666651-04ec1c07-b531-457b-9c68-cfa45884185a.png)

2. When I put in an invalid HEX, the modal closes and shows a Toast. The expected behavior is for the modal to remain open and the input field should notify of the error
![Screenshot from 2022-06-02 16-37-07](https://user-images.githubusercontent.com/25265396/171666938-c9cdbb0d-aaba-4b3d-9893-aacae56787c8.png).

See example below
![Screenshot from 2022-06-02 16-38-25](https://user-images.githubusercontent.com/25265396/171667045-7a14268b-b96e-465e-8bca-7b58cc9e2b5c.png)

2022-06-02 15:41 UTC, dreacot commented on ui/page/components/utils.go
> +// encoding.  The "checksum" is the first byte of the double SHA256.
```suggestion
// encoding. The "checksum" is the first byte of the double SHA256.
```

2022-06-06 07:15 UTC, Sirmorrison requested changes

2022-06-06 07:15 UTC, Sirmorrison commented on ui/page/wallets/seed_restore_page.go
> +
remove white space

2022-06-06 07:15 UTC, Sirmorrison commented on ui/page/seedbackup/save_seed.go
> +		})
```suggestion
		time.AfterFunc(time.Second*3, func() {
			pg.copy.Text = "Copy"
			pg.copy.Color = pg.Theme.Color.Primary
			pg.RefreshWindow()
		})
```

After 3 secs you need to refresh the window for the changes to be displayed.

2022-06-10 08:29 UTC, Sirmorrison requested changes
https://user-images.githubusercontent.com/27733432/173023870-14fcd5db-199e-4837-a08c-5b932105212a.mov

* so i am noticing some unexpected behaviors.. How are hex validated? are we just checking for the length because if i change the last `n digits` of the hex, it still imports a wallet.
* Why does errors from validating the hex minimize the modal eg (invalid hex)? the errors should be displayed under hex input editor.
* lastly, when i i have input a wrong hex (ie editing the original hex key values), it opens up the wallet editor.. if i click on cancel to minimize the wallet creation modal, clicking on the hex nav button again, does not open the modal.

2022-06-11 17:34 UTC, crux25 commented
> 



> Screen.Recording.2022-06-10.at.09.21.53.mov
> 
>     * so i am noticing some unexpected behaviors.. How are hex validated? are we just checking for the length because if i change the last `n digits` of the hex, it still imports a wallet.
> 
>     * Why does errors from validating the hex minimize the modal eg (invalid hex)? the errors should be displayed under hex input editor.
> 
>     * lastly, when i i have input a wrong hex (ie editing the original hex key values), it opens up the wallet editor.. if i click on cancel to minimize the wallet creation modal, clicking on the hex nav button again, does not open the modal.

Hex validation is handled by dcrwallet basically it checks that the supplied hex is valid; that is the character contains [0-9][a-f], it also checks the hex length. If you're interested in the algo you can look at https://github.com/decred/dcrwallet/blob/4ed5a4c677f9bdb1b8e70ceccf476fbff413cd79/walletseed/seed.go#L71

2022-06-12 14:21 UTC, crux25 commented
> 



> Screen.Recording.2022-06-10.at.09.21.53.mov
> 
>     * so i am noticing some unexpected behaviors.. How are hex validated? are we just checking for the length because if i change the last `n digits` of the hex, it still imports a wallet.
> 
>     * Why does errors from validating the hex minimize the modal eg (invalid hex)? the errors should be displayed under hex input editor.
> 
>     * lastly, when i i have input a wrong hex (ie editing the original hex key values), it opens up the wallet editor.. if i click on cancel to minimize the wallet creation modal, clicking on the hex nav button again, does not open the modal.

Hex validation is handled by dcrwallet basically it checks that the supplied hex is valid; that is the character contains [0-9][a-f], it also checks the hex length. If you're interested in the implementation you can look at https://github.com/decred/dcrwallet/blob/4ed5a4c677f9bdb1b8e70ceccf476fbff413cd79/walletseed/seed.go#L71

2022-06-13 18:57 UTC, Sirmorrison approved these changes

2022-06-13 18:58 UTC, merged