receive page new layout setup
planetdecred/godcr pull request #99
Opened 2020-05-10 13:25 UTC by Sirmorrison

### Resolves

Issue #

### What's new

_A detailed description of what this pull request adds_

### Relevant screenshots or logs

_If applicable, add screenshots or log entries to help explain your problem._

### Additional context

_Add any other context about the problem here._

2020-05-12 08:55 UTC, oluwandabira requested changes

2020-05-12 08:55 UTC, RogueElement commented on ui/page.go
> +	page.accountsTab.Position = decredmaterial.Top
This should be set in `addPages`

2020-05-12 08:55 UTC, RogueElement commented on ui/recieve_page.go
> +		log.Debug("Error generating address qrCode: " + err.Error())
log.Error

2020-05-12 08:55 UTC, RogueElement commented on ui/recieve_page.go
> +	copyBtnW, infoBtnW, moreBtnW, gotItBtnW, newAddrBtnW widget.Button
"gotIt" is not a good variable name

2020-05-14 11:43 UTC, oshorefueled commented on ui/recieve_page.go
> +func (p *receivePage) selectedAcountColumn(common pageCommon) {
There's a typo on the method name.

2020-05-14 11:48 UTC, oshorefueled approved these changes

2020-05-14 11:48 UTC, oshorefueled commented on ui/decredmaterial/icon.go
> +	_ "image/png" // fixes unknown format error when trying to decode png images
this comment should be rephrased. It makes png a decodable format, it doesn't fix an error.

2020-05-14 11:54 UTC, oshorefueled requested changes

2020-05-14 11:54 UTC, oshorefueled commented on ui/decredmaterial/icon.go
> +	_ "image/png" // fixes unknown format error when trying to decode png images
this comment should be rephrased. It makes png a decodable format, it doesn't fix an error.

2020-05-15 13:06 UTC, oshorefueled submitted a review, later dismissed

2020-05-16 09:51 UTC, oluwandabira approved these changes

2020-05-16 11:36 UTC, merged