update security tools page
planetdecred/godcr pull request #998
Opened 2022-06-18 16:36 UTC by AdimekweEbuka

Close #988 
This PR updates the security tools page to current design.

2022-06-19 05:50 UTC, devchoplife requested changes
Clicking on the `Sign message` button does nothing, It should lead to the sign message page

2022-06-20 09:07 UTC, AdimekweEbuka commented
> Clicking on the `Sign message` button does nothing, It should lead to the sign message page

Yes, I left that out because I was also working on the sign message page but I'll do that now.

2022-06-24 07:28 UTC, Sirmorrison requested changes

2022-06-24 07:28 UTC, Sirmorrison commented on ui/values/localizable/en.go
> +"securityToolsInfo" = "%v Various tools that help in different aspects of cryptocurrency security will be located here. %v"
move this to the bottom so we know string that need other language translations.

2022-06-28 12:43 UTC, Sirmorrison requested changes

2022-06-28 12:43 UTC, Sirmorrison commented on ui/page/wallets/wallet_page.go
> +					pg.ParentNavigator().Display(NewSignMessagePage(pg.Load))
This option should be removed since it has been migrated to the security tools page.

2022-06-28 12:51 UTC, Sirmorrison requested changes

2022-06-28 12:51 UTC, Sirmorrison commented on ui/values/localizable/en.go
> +"securityToolsInfo" = "%v Various tools that help in different aspects of cryptocurrency security will be located here. %v"
```suggestion
"securityToolsInfo" = "%v Various tools for enhancing your fund security, are located here. %v"
```

2022-06-29 08:45 UTC, Sirmorrison requested changes

2022-06-29 08:45 UTC, Sirmorrison commented on ui/values/localizable/en.go
> +"securityToolsInfo" = "%v Various tools for enhancing your fund security are, located here. %v"
```suggestion
"securityToolsInfo" = "%v Various tools for enhancing your fund security, are located here. %v"
```

2022-06-29 09:30 UTC, Sirmorrison approved these changes

2022-06-29 09:31 UTC, merged